#include <stratego.h>
#include <stratego-lib.h>
#include <stratego-ext.h>
DOIT_START
cur_rule_counter = 0;
  Rpush(x_1);
  goto main;
  main :
  Epushd(0,0);
  BuildStr("as-pattern-test");
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("test suite: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(a_0);
  goto r_29;
  a_0 :
  Tpop();
  Epopd(1,0);
  Rpush(b_0);
  goto s_29;
  b_0 :
  Rpush(c_0);
  goto x_29;
  c_0 :
  Rpush(d_0);
  goto d_30;
  d_0 :
  Rpush(e_0);
  goto t_29;
  e_0 :
  Rpush(f_0);
  goto v_29;
  f_0 :
  Epopd(0,0);
  Return();
  r_29 :
  Epushd(0,0);
  _ST_printnl();
  Epopd(0,0);
  Return();
  s_29 :
  Epushd(0,0);
  BuildInt(0);
  Tpush();
  BuildInt(0);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(0,0);
  Return();
  t_29 :
  Epushd(0,0);
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("successes: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(g_0);
  goto r_29;
  g_0 :
  Tpop();
  Epopd(1,0);
  OneNextSon();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("failures: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(h_0);
  goto r_29;
  h_0 :
  Tpop();
  Epopd(1,0);
  OneNextSon();
  Rpush(i_0);
  goto u_29;
  i_0 :
  AllBuild();
  AllBuild();
  Epopd(0,0);
  Return();
  u_29 :
  MatchFun("TNil",0);
  Return();
  v_29 :
  Epushd(0,0);
  Cpush(k_0);
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  MatchInt(0);
  OneNextSon();
  Rpush(l_0);
  goto u_29;
  l_0 :
  AllBuild();
  AllBuild();
  BuildInt(0);
  Rpush(m_0);
  goto w_29;
  m_0 :
  Cpop();
  goto j_0;
  k_0 :
  BuildInt(1);
  Rpush(n_0);
  goto w_29;
  n_0 :
  j_0 :
  Epopd(0,0);
  Return();
  w_29 :
  Epushd(0,0);
  _ST_exit();
  Epopd(0,0);
  Return();
  x_29 :
  Epushd(0,2);
  Tdupl();
  BuildStr("as-pattern1");
  Rpush(o_0);
  goto b_30;
  o_0 :
  Tpop();
  Cpush(q_0);
  Tdupl();
  Cpush(s_0);
  BuildFun("B",0);
  Tpush();
  BuildFun("A",0);
  Tpush();
  BuildFun("C",0);
  Tpush();
  BuildFun("G",2);
  Tpush();
  BuildFun("F",2);
  Epushd(1,3);
  MatchFun("F",2);
  Arg(0);
  MatchVard(1,1);
  Tpop();
  Arg(1);
  MatchVard(1,2);
  MatchFun("G",2);
  Arg(0);
  MatchFun("A",0);
  Tpop();
  Arg(1);
  MatchVard(1,3);
  Tpop();
  Tpop();
  BuildVard(1,1);
  Tpush();
  BuildVard(1,2);
  Tpush();
  BuildVard(1,3);
  Tpush();
  BuildFun("H",3);
  Epopd(1,3);
  MatchVard(0,1);
  Cpop();
  goto r_0;
  s_0 :
  BuildStr("  failed");
  Rpush(t_0);
  goto b_30;
  t_0 :
  Rpush(u_0);
  goto c_30;
  u_0 :
  r_0 :
  BuildFun("B",0);
  Tpush();
  BuildFun("A",0);
  Tpush();
  BuildFun("C",0);
  Tpush();
  BuildFun("G",2);
  Tpush();
  BuildFun("C",0);
  Tpush();
  BuildFun("H",3);
  MatchVard(0,2);
  Cpush(w_0);
  BuildVard(0,2);
  MatchVard(0,1);
  Cpop();
  goto v_0;
  w_0 :
  BuildVard(0,1);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  result not equal: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(x_0);
  goto r_29;
  x_0 :
  Tpop();
  Epopd(1,0);
  BuildVard(0,2);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  expected: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(y_0);
  goto r_29;
  y_0 :
  Tpop();
  Epopd(1,0);
  Rpush(z_0);
  goto c_30;
  z_0 :
  v_0 :
  Tpop();
  Rpush(a_1);
  goto y_29;
  a_1 :
  Cpop();
  goto p_0;
  q_0 :
  Rpush(b_1);
  goto a_30;
  b_1 :
  p_0 :
  Epopd(0,2);
  Return();
  y_29 :
  Epushd(0,0);
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Epushd(1,1);
  MatchVard(1,1);
  BuildVard(1,1);
  Tpush();
  BuildInt(1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(c_1);
  goto z_29;
  c_1 :
  Epopd(1,1);
  OneNextSon();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  Rpush(d_1);
  goto u_29;
  d_1 :
  AllBuild();
  AllBuild();
  Epopd(0,0);
  Return();
  z_29 :
  Epushd(0,0);
  _ST_add();
  Epopd(0,0);
  Return();
  a_30 :
  Epushd(0,0);
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Epushd(1,1);
  MatchVard(1,1);
  BuildVard(1,1);
  Tpush();
  BuildInt(1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(e_1);
  goto z_29;
  e_1 :
  Epopd(1,1);
  OneNextSon();
  Rpush(f_1);
  goto u_29;
  f_1 :
  AllBuild();
  AllBuild();
  Epopd(0,0);
  Return();
  b_30 :
  Epushd(0,0);
  Tdupl();
  Epushd(1,1);
  MatchVard(1,1);
  Epushd(2,1);
  BuildVard(1,1);
  BuildFun("stderr",0);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(1,1);
  Epushd(4,1);
  MatchVard(4,1);
  BuildVard(4,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Epopd(4,1);
  MatchVard(3,1);
  BuildVard(2,1);
  Tpush();
  BuildVard(3,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(3,1);
  Epopd(2,1);
  Epopd(1,1);
  Rpush(g_1);
  goto r_29;
  g_1 :
  Tpop();
  Epopd(0,0);
  Return();
  c_30 :
  Epushd(0,1);
  MatchVard(0,1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  Epopd(0,1);
  Return();
  d_30 :
  Epushd(0,2);
  Tdupl();
  BuildStr("as-pattern2");
  Rpush(h_1);
  goto b_30;
  h_1 :
  Tpop();
  Cpush(j_1);
  Tdupl();
  Cpush(l_1);
  BuildFun("B",0);
  Tpush();
  BuildFun("C",0);
  Tpush();
  BuildFun("B",0);
  Tpush();
  BuildFun("G",2);
  Tpush();
  BuildFun("F",2);
  Cpush(n_1);
  Epushd(1,3);
  MatchFun("F",2);
  Arg(0);
  MatchVard(1,1);
  Tpop();
  Arg(1);
  MatchVard(1,2);
  MatchFun("G",2);
  Arg(0);
  MatchFun("A",0);
  Tpop();
  Arg(1);
  MatchVard(1,3);
  Tpop();
  Tpop();
  BuildVard(1,1);
  Tpush();
  BuildVard(1,2);
  Tpush();
  BuildVard(1,3);
  Tpush();
  BuildFun("H",3);
  Epopd(1,3);
  Cpop();
  goto m_1;
  n_1 :
  Epushd(1,2);
  MatchFun("F",2);
  Arg(0);
  MatchVard(1,1);
  Tpop();
  Arg(1);
  MatchFun("G",2);
  Arg(0);
  MatchVard(1,2);
  Tpop();
  Arg(1);
  MatchFun("B",0);
  Tpop();
  Tpop();
  BuildVard(1,1);
  Tpush();
  BuildVard(1,2);
  Tpush();
  BuildFun("B",0);
  Tpush();
  BuildFun("H",3);
  Epopd(1,2);
  m_1 :
  MatchVard(0,1);
  Cpop();
  goto k_1;
  l_1 :
  BuildStr("  failed");
  Rpush(o_1);
  goto b_30;
  o_1 :
  Rpush(p_1);
  goto c_30;
  p_1 :
  k_1 :
  BuildFun("B",0);
  Tpush();
  BuildFun("C",0);
  Tpush();
  BuildFun("B",0);
  Tpush();
  BuildFun("H",3);
  MatchVard(0,2);
  Cpush(r_1);
  BuildVard(0,2);
  MatchVard(0,1);
  Cpop();
  goto q_1;
  r_1 :
  BuildVard(0,1);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  result not equal: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(s_1);
  goto r_29;
  s_1 :
  Tpop();
  Epopd(1,0);
  BuildVard(0,2);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  expected: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(t_1);
  goto r_29;
  t_1 :
  Tpop();
  Epopd(1,0);
  Rpush(u_1);
  goto c_30;
  u_1 :
  q_1 :
  Tpop();
  Rpush(v_1);
  goto y_29;
  v_1 :
  Cpop();
  goto i_1;
  j_1 :
  Rpush(w_1);
  goto a_30;
  w_1 :
  i_1 :
  Epopd(0,2);
  Return();
  x_1 :
DOIT_END
