#include <stratego.h>
#include <stratego-lib.h>
#include <stratego-ext.h>
DOIT_START
cur_rule_counter = 0;
  Rpush(x_4);
  goto main;
  main :
  Epushd(0,0);
  BuildStr("unification-test");
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("test suite: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(a_0);
  goto w_6;
  a_0 :
  Tpop();
  Epopd(1,0);
  Rpush(b_0);
  goto x_6;
  b_0 :
  Rpush(h_0);
  goto c_7;
  h_0 :
  Rpush(i_0);
  goto l_7;
  i_0 :
  Rpush(j_0);
  goto y_6;
  j_0 :
  Rpush(k_0);
  goto a_7;
  k_0 :
  Epopd(0,0);
  Return();
  w_6 :
  Epushd(0,0);
  _ST_printnl();
  Epopd(0,0);
  Return();
  x_6 :
  Epushd(0,0);
  BuildInt(0);
  Tpush();
  BuildInt(0);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(0,0);
  Return();
  y_6 :
  Epushd(0,0);
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("successes: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(l_0);
  goto w_6;
  l_0 :
  Tpop();
  Epopd(1,0);
  OneNextSon();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("failures: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(m_0);
  goto w_6;
  m_0 :
  Tpop();
  Epopd(1,0);
  OneNextSon();
  Rpush(n_0);
  goto z_6;
  n_0 :
  AllBuild();
  AllBuild();
  Epopd(0,0);
  Return();
  z_6 :
  MatchFun("TNil",0);
  Return();
  a_7 :
  Epushd(0,0);
  Cpush(p_0);
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  MatchInt(0);
  OneNextSon();
  Rpush(q_0);
  goto z_6;
  q_0 :
  AllBuild();
  AllBuild();
  BuildInt(0);
  Rpush(r_0);
  goto b_7;
  r_0 :
  Cpop();
  goto o_0;
  p_0 :
  BuildInt(1);
  Rpush(s_0);
  goto b_7;
  s_0 :
  o_0 :
  Epopd(0,0);
  Return();
  b_7 :
  Epushd(0,0);
  _ST_exit();
  Epopd(0,0);
  Return();
  c_7 :
  Epushd(0,2);
  Tdupl();
  BuildStr("test0");
  Rpush(t_0);
  goto g_7;
  t_0 :
  Tpop();
  Cpush(v_0);
  Tdupl();
  Cpush(x_0);
  BuildStr("a");
  Tpush();
  BuildFun("Var",1);
  Tpush();
  BuildStr("b");
  Tpush();
  BuildStr("b");
  Tpush();
  BuildFun("TVar",1);
  Tpush();
  BuildFun("Forall",2);
  Tpush();
  BuildFun("Typed",2);
  Tpush();
  BuildStr("a");
  Tpush();
  BuildFun("Var",1);
  Tpush();
  BuildStr("b");
  Tpush();
  BuildStr("b");
  Tpush();
  BuildFun("TVar",1);
  Tpush();
  BuildFun("Forall",2);
  Tpush();
  BuildFun("Typed",2);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Rpush(y_0);
  goto i_7;
  y_0 :
  MatchVard(0,1);
  Cpop();
  goto w_0;
  x_0 :
  BuildStr("  failed");
  Rpush(z_0);
  goto g_7;
  z_0 :
  Rpush(m_1);
  goto h_7;
  m_1 :
  w_0 :
  BuildFun("Nil",0);
  MatchVard(0,2);
  Cpush(o_1);
  BuildVard(0,2);
  MatchVard(0,1);
  Cpop();
  goto n_1;
  o_1 :
  BuildVard(0,1);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  result not equal: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(p_1);
  goto w_6;
  p_1 :
  Tpop();
  Epopd(1,0);
  BuildVard(0,2);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  expected: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(q_1);
  goto w_6;
  q_1 :
  Tpop();
  Epopd(1,0);
  Rpush(r_1);
  goto h_7;
  r_1 :
  n_1 :
  Tpop();
  Rpush(s_1);
  goto d_7;
  s_1 :
  Cpop();
  goto u_0;
  v_0 :
  Rpush(t_1);
  goto f_7;
  t_1 :
  u_0 :
  Epopd(0,2);
  Return();
  d_7 :
  Epushd(0,0);
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Epushd(1,1);
  MatchVard(1,1);
  BuildVard(1,1);
  Tpush();
  BuildInt(1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(u_1);
  goto e_7;
  u_1 :
  Epopd(1,1);
  OneNextSon();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  Rpush(v_1);
  goto z_6;
  v_1 :
  AllBuild();
  AllBuild();
  Epopd(0,0);
  Return();
  e_7 :
  Epushd(0,0);
  _ST_add();
  Epopd(0,0);
  Return();
  f_7 :
  Epushd(0,0);
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Epushd(1,1);
  MatchVard(1,1);
  BuildVard(1,1);
  Tpush();
  BuildInt(1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(w_1);
  goto e_7;
  w_1 :
  Epopd(1,1);
  OneNextSon();
  Rpush(b_2);
  goto z_6;
  b_2 :
  AllBuild();
  AllBuild();
  Epopd(0,0);
  Return();
  g_7 :
  Epushd(0,0);
  Tdupl();
  Epushd(1,1);
  MatchVard(1,1);
  Epushd(2,1);
  BuildVard(1,1);
  BuildFun("stderr",0);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(1,1);
  Epushd(4,1);
  MatchVard(4,1);
  BuildVard(4,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Epopd(4,1);
  MatchVard(3,1);
  BuildVard(2,1);
  Tpush();
  BuildVard(3,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(3,1);
  Epopd(2,1);
  Epopd(1,1);
  Rpush(c_2);
  goto w_6;
  c_2 :
  Tpop();
  Epopd(0,0);
  Return();
  h_7 :
  Epushd(0,1);
  MatchVard(0,1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  Epopd(0,1);
  Return();
  i_7 :
  Epushd(0,0);
  Rpush(d_2);
  b_3 :
  Cpush(f_2);
  Epushd(1,2);
  MatchFun("Cons",2);
  Arg(0);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(1,1);
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(1,1);
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(1,2);
  Tpop();
  BuildVard(1,2);
  Epopd(1,2);
  Cpop();
  goto e_2;
  f_2 :
  Rpush(r_2);
  goto k_7;
  r_2 :
  e_2 :
  Cpush(y_2);
  Rpush(z_2);
  goto j_7;
  z_2 :
  Cpop();
  goto x_2;
  y_2 :
  Rpush(a_3);
  goto b_3;
  a_3 :
  x_2 :
  Return();
  d_2 :
  Epopd(0,0);
  Return();
  j_7 :
  MatchFun("Nil",0);
  Return();
  k_7 :
  Epushd(0,8);
  Epushd(1,1);
  MatchFun("Cons",2);
  Arg(0);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(0,5);
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(1,1);
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,4);
  Tpop();
  Tdupl();
  BuildVard(1,1);
  _ST_explode_term();
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(0,3);
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  Tpop();
  Epopd(1,1);
  Tdupl();
  BuildVard(0,5);
  _ST_explode_term();
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(0,2);
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  Tpop();
  BuildVard(0,2);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epushd(1,0);
  Rpush(c_3);
  l_3 :
  Cpush(g_3);
  Epushd(2,0);
  MatchFun("TCons",2);
  Arg(0);
  MatchFun("Nil",0);
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchFun("Nil",0);
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  BuildFun("Nil",0);
  Epopd(2,0);
  Cpop();
  goto f_3;
  g_3 :
  Epushd(2,4);
  MatchFun("TCons",2);
  Arg(0);
  MatchFun("Cons",2);
  Arg(0);
  MatchVard(2,1);
  Tpop();
  Arg(1);
  MatchVard(2,3);
  Tpop();
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchFun("Cons",2);
  Arg(0);
  MatchVard(2,2);
  Tpop();
  Arg(1);
  MatchVard(2,4);
  Tpop();
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  BuildVard(2,1);
  Tpush();
  BuildVard(2,2);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildVard(2,3);
  Tpush();
  BuildVard(2,4);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(2,4);
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Rpush(h_3);
  goto l_3;
  h_3 :
  OneNextSon();
  Rpush(i_3);
  goto z_6;
  i_3 :
  AllBuild();
  AllBuild();
  Epushd(2,2);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(2,1);
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(2,2);
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  BuildVard(2,1);
  Tpush();
  BuildVard(2,2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(2,2);
  f_3 :
  Return();
  c_3 :
  Epopd(1,0);
  MatchVard(0,6);
  BuildVard(0,6);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(0,8);
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(0,7);
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  BuildVard(0,8);
  Epushd(1,0);
  Rpush(j_3);
  u_3 :
  Cpush(v_3);
  MatchFun("Cons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  Rpush(w_3);
  goto u_3;
  w_3 :
  AllBuild();
  Cpop();
  goto k_3;
  v_3 :
  Rpush(x_3);
  goto j_7;
  x_3 :
  BuildVard(0,7);
  k_3 :
  Return();
  j_3 :
  Epopd(1,0);
  Epopd(0,8);
  Return();
  l_7 :
  Epushd(0,2);
  Tdupl();
  BuildStr("test1");
  Rpush(y_3);
  goto g_7;
  y_3 :
  Tpop();
  Cpush(a_4);
  Tdupl();
  Cpush(c_4);
  BuildStr("a");
  Tpush();
  BuildFun("Var",1);
  Tpush();
  BuildStr("b");
  Tpush();
  BuildStr("b");
  Tpush();
  BuildFun("TVar",1);
  Tpush();
  BuildFun("Forall",2);
  Tpush();
  BuildFun("Typed",2);
  Tpush();
  BuildStr("a");
  Tpush();
  BuildFun("Var",1);
  Tpush();
  BuildStr("c");
  Tpush();
  BuildStr("c");
  Tpush();
  BuildFun("TVar",1);
  Tpush();
  BuildFun("Forall",2);
  Tpush();
  BuildFun("Typed",2);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Epushd(1,0);
  Rpush(d_4);
  v_6 :
  Cpush(f_4);
  Epushd(2,2);
  MatchFun("Cons",2);
  Arg(0);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(2,1);
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(2,1);
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(2,2);
  Tpop();
  BuildVard(2,2);
  Epopd(2,2);
  Cpop();
  goto e_4;
  f_4 :
  Epushd(2,0);
  Cpush(h_4);
  MatchFun("Cons",2);
  TravInit();
  OneNextSon();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Epushd(3,2);
  MatchFun("Typed",2);
  Arg(0);
  MatchVard(3,1);
  Tpop();
  Arg(1);
  MatchVard(3,2);
  Tpop();
  BuildVard(3,1);
  Epopd(3,2);
  OneNextSon();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Epushd(3,2);
  MatchFun("Typed",2);
  Arg(0);
  MatchVard(3,1);
  Tpop();
  Arg(1);
  MatchVard(3,2);
  Tpop();
  BuildVard(3,1);
  Epopd(3,2);
  OneNextSon();
  Rpush(i_4);
  goto z_6;
  i_4 :
  AllBuild();
  AllBuild();
  OneNextSon();
  AllBuild();
  Cpop();
  goto g_4;
  h_4 :
  g_4 :
  Epopd(2,0);
  Rpush(j_4);
  goto k_7;
  j_4 :
  e_4 :
  Cpush(l_4);
  Rpush(m_4);
  goto j_7;
  m_4 :
  Cpop();
  goto k_4;
  l_4 :
  Rpush(n_4);
  goto v_6;
  n_4 :
  k_4 :
  Return();
  d_4 :
  Epopd(1,0);
  MatchVard(0,1);
  Cpop();
  goto b_4;
  c_4 :
  BuildStr("  failed");
  Rpush(o_4);
  goto g_7;
  o_4 :
  Rpush(p_4);
  goto h_7;
  p_4 :
  b_4 :
  BuildFun("Nil",0);
  MatchVard(0,2);
  Cpush(r_4);
  BuildVard(0,2);
  MatchVard(0,1);
  Cpop();
  goto q_4;
  r_4 :
  BuildVard(0,1);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  result not equal: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(s_4);
  goto w_6;
  s_4 :
  Tpop();
  Epopd(1,0);
  BuildVard(0,2);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  expected: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(t_4);
  goto w_6;
  t_4 :
  Tpop();
  Epopd(1,0);
  Rpush(u_4);
  goto h_7;
  u_4 :
  q_4 :
  Tpop();
  Rpush(v_4);
  goto d_7;
  v_4 :
  Cpop();
  goto z_3;
  a_4 :
  Rpush(w_4);
  goto f_7;
  w_4 :
  z_3 :
  Epopd(0,2);
  Return();
  x_4 :
DOIT_END
