#include <stratego.h>
#include <stratego-lib.h>
#include <stratego-ext.h>
DOIT_START
cur_rule_counter = 0;
  Rpush(f_5);
  goto main;
  main :
  Epushd(0,0);
  BuildStr("list-basic-test");
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("test suite: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(a_0);
  goto s_5;
  a_0 :
  Tpop();
  Epopd(1,0);
  Rpush(b_0);
  goto t_5;
  b_0 :
  Rpush(h_0);
  goto y_5;
  h_0 :
  Rpush(i_0);
  goto e_6;
  i_0 :
  Rpush(j_0);
  goto j_6;
  j_0 :
  Rpush(k_0);
  goto u_5;
  k_0 :
  Rpush(l_0);
  goto w_5;
  l_0 :
  Epopd(0,0);
  Return();
  s_5 :
  Epushd(0,0);
  _ST_printnl();
  Epopd(0,0);
  Return();
  t_5 :
  Epushd(0,0);
  BuildInt(0);
  Tpush();
  BuildInt(0);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(0,0);
  Return();
  u_5 :
  Epushd(0,0);
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("successes: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(m_0);
  goto s_5;
  m_0 :
  Tpop();
  Epopd(1,0);
  OneNextSon();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("failures: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(n_0);
  goto s_5;
  n_0 :
  Tpop();
  Epopd(1,0);
  OneNextSon();
  Rpush(o_0);
  goto v_5;
  o_0 :
  AllBuild();
  AllBuild();
  Epopd(0,0);
  Return();
  v_5 :
  MatchFun("TNil",0);
  Return();
  w_5 :
  Epushd(0,0);
  Cpush(q_0);
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  MatchInt(0);
  OneNextSon();
  Rpush(r_0);
  goto v_5;
  r_0 :
  AllBuild();
  AllBuild();
  BuildInt(0);
  Rpush(s_0);
  goto x_5;
  s_0 :
  Cpop();
  goto p_0;
  q_0 :
  BuildInt(1);
  Rpush(t_0);
  goto x_5;
  t_0 :
  p_0 :
  Epopd(0,0);
  Return();
  x_5 :
  Epushd(0,0);
  _ST_exit();
  Epopd(0,0);
  Return();
  y_5 :
  Epushd(0,2);
  Tdupl();
  BuildStr("test1");
  Rpush(u_0);
  goto c_6;
  u_0 :
  Tpop();
  Cpush(w_0);
  Tdupl();
  Cpush(y_0);
  BuildInt(1);
  Tpush();
  BuildInt(2);
  Tpush();
  BuildInt(3);
  Tpush();
  BuildInt(4);
  Tpush();
  BuildInt(5);
  Tpush();
  BuildInt(6);
  Tpush();
  BuildInt(7);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epushd(1,2);
  Rpush(z_0);
  e_3 :
  Cpush(b_1);
  MatchFun("Cons",2);
  TravInit();
  OneNextSon();
  MatchInt(4);
  OneNextSon();
  AllBuild();
  MatchFun("Cons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  MatchVard(1,1);
  AllBuild();
  BuildFun("Nil",0);
  Cpop();
  goto a_1;
  b_1 :
  MatchFun("Cons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  Rpush(c_1);
  goto e_3;
  c_1 :
  AllBuild();
  a_1 :
  Return();
  z_0 :
  MatchVard(1,2);
  Epushd(2,1);
  BuildVard(1,2);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(1,2);
  BuildVard(1,1);
  MatchVard(3,1);
  BuildVard(2,1);
  Tpush();
  BuildVard(3,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(3,1);
  Epopd(2,1);
  Epopd(1,2);
  MatchVard(0,1);
  Cpop();
  goto x_0;
  y_0 :
  BuildStr("  failed");
  Rpush(d_1);
  goto c_6;
  d_1 :
  Rpush(e_1);
  goto d_6;
  e_1 :
  x_0 :
  BuildInt(1);
  Tpush();
  BuildInt(2);
  Tpush();
  BuildInt(3);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildInt(5);
  Tpush();
  BuildInt(6);
  Tpush();
  BuildInt(7);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  MatchVard(0,2);
  Cpush(q_1);
  BuildVard(0,2);
  MatchVard(0,1);
  Cpop();
  goto p_1;
  q_1 :
  BuildVard(0,1);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  result not equal: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(r_1);
  goto s_5;
  r_1 :
  Tpop();
  Epopd(1,0);
  BuildVard(0,2);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  expected: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(s_1);
  goto s_5;
  s_1 :
  Tpop();
  Epopd(1,0);
  Rpush(t_1);
  goto d_6;
  t_1 :
  p_1 :
  Tpop();
  Rpush(u_1);
  goto z_5;
  u_1 :
  Cpop();
  goto v_0;
  w_0 :
  Rpush(x_1);
  goto b_6;
  x_1 :
  v_0 :
  Epopd(0,2);
  Return();
  z_5 :
  Epushd(0,0);
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Epushd(1,1);
  MatchVard(1,1);
  BuildVard(1,1);
  Tpush();
  BuildInt(1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(y_1);
  goto a_6;
  y_1 :
  Epopd(1,1);
  OneNextSon();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  Rpush(z_1);
  goto v_5;
  z_1 :
  AllBuild();
  AllBuild();
  Epopd(0,0);
  Return();
  a_6 :
  Epushd(0,0);
  _ST_add();
  Epopd(0,0);
  Return();
  b_6 :
  Epushd(0,0);
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Epushd(1,1);
  MatchVard(1,1);
  BuildVard(1,1);
  Tpush();
  BuildInt(1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(a_2);
  goto a_6;
  a_2 :
  Epopd(1,1);
  OneNextSon();
  Rpush(b_2);
  goto v_5;
  b_2 :
  AllBuild();
  AllBuild();
  Epopd(0,0);
  Return();
  c_6 :
  Epushd(0,0);
  Tdupl();
  Epushd(1,1);
  MatchVard(1,1);
  Epushd(2,1);
  BuildVard(1,1);
  BuildFun("stderr",0);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(1,1);
  Epushd(4,1);
  MatchVard(4,1);
  BuildVard(4,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Epopd(4,1);
  MatchVard(3,1);
  BuildVard(2,1);
  Tpush();
  BuildVard(3,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(3,1);
  Epopd(2,1);
  Epopd(1,1);
  Rpush(c_2);
  goto s_5;
  c_2 :
  Tpop();
  Epopd(0,0);
  Return();
  d_6 :
  Epushd(0,1);
  MatchVard(0,1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  Epopd(0,1);
  Return();
  e_6 :
  Epushd(0,2);
  Tdupl();
  BuildStr("upto-test1");
  Rpush(d_2);
  goto c_6;
  d_2 :
  Tpop();
  Cpush(f_2);
  Tdupl();
  Cpush(h_2);
  BuildInt(5);
  Rpush(i_2);
  goto f_6;
  i_2 :
  MatchVard(0,1);
  Cpop();
  goto g_2;
  h_2 :
  BuildStr("  failed");
  Rpush(j_2);
  goto c_6;
  j_2 :
  Rpush(k_2);
  goto d_6;
  k_2 :
  g_2 :
  BuildInt(0);
  Tpush();
  BuildInt(1);
  Tpush();
  BuildInt(2);
  Tpush();
  BuildInt(3);
  Tpush();
  BuildInt(4);
  Tpush();
  BuildInt(5);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  MatchVard(0,2);
  Cpush(m_2);
  BuildVard(0,2);
  MatchVard(0,1);
  Cpop();
  goto l_2;
  m_2 :
  BuildVard(0,1);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  result not equal: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(n_2);
  goto s_5;
  n_2 :
  Tpop();
  Epopd(1,0);
  BuildVard(0,2);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  expected: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(o_2);
  goto s_5;
  o_2 :
  Tpop();
  Epopd(1,0);
  Rpush(p_2);
  goto d_6;
  p_2 :
  l_2 :
  Tpop();
  Rpush(g_3);
  goto z_5;
  g_3 :
  Cpop();
  goto e_2;
  f_2 :
  Rpush(o_3);
  goto b_6;
  o_3 :
  e_2 :
  Epopd(0,2);
  Return();
  f_6 :
  Epushd(0,0);
  Epushd(1,1);
  MatchVard(1,1);
  BuildVard(1,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(1,1);
  Rpush(p_3);
  j_12 :
  Cpush(r_3);
  Epushd(1,2);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(1,2);
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(1,1);
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  Tdupl();
  BuildVard(1,2);
  Tpush();
  BuildInt(0);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(s_3);
  goto g_6;
  s_3 :
  Tpop();
  BuildVard(1,1);
  Epopd(1,2);
  Cpop();
  goto q_3;
  r_3 :
  Epushd(1,2);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(1,1);
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(1,2);
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  Epushd(2,1);
  BuildVard(1,1);
  Tpush();
  BuildInt(1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(t_3);
  goto i_6;
  t_3 :
  MatchVard(2,1);
  BuildVard(2,1);
  Tpush();
  BuildVard(1,1);
  Tpush();
  BuildVard(1,2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(2,1);
  Epopd(1,2);
  Rpush(u_3);
  goto j_12;
  u_3 :
  q_3 :
  Return();
  p_3 :
  Epopd(0,0);
  Return();
  g_6 :
  Epushd(0,0);
  Cpush(v_3);
  Tdupl();
  Rpush(w_3);
  goto h_6;
  w_3 :
  Cpop();
  Crestore();
  Cjump();
  v_3 :
  Epopd(0,0);
  Return();
  h_6 :
  Epushd(0,0);
  _ST_geq();
  Epopd(0,0);
  Return();
  i_6 :
  Epushd(0,0);
  _ST_minus();
  Epopd(0,0);
  Return();
  j_6 :
  Epushd(0,2);
  Tdupl();
  BuildStr("upto-test2");
  Rpush(x_3);
  goto c_6;
  x_3 :
  Tpop();
  Cpush(z_3);
  Tdupl();
  Cpush(b_4);
  BuildInt(0);
  Tpush();
  BuildInt(3);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(u_4);
  goto i_6;
  u_4 :
  Rpush(v_4);
  goto f_6;
  v_4 :
  MatchVard(0,1);
  Cpop();
  goto a_4;
  b_4 :
  BuildStr("  failed");
  Rpush(w_4);
  goto c_6;
  w_4 :
  Rpush(x_4);
  goto d_6;
  x_4 :
  a_4 :
  BuildFun("Nil",0);
  MatchVard(0,2);
  Cpush(z_4);
  BuildVard(0,2);
  MatchVard(0,1);
  Cpop();
  goto y_4;
  z_4 :
  BuildVard(0,1);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  result not equal: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(a_5);
  goto s_5;
  a_5 :
  Tpop();
  Epopd(1,0);
  BuildVard(0,2);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  expected: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(b_5);
  goto s_5;
  b_5 :
  Tpop();
  Epopd(1,0);
  Rpush(c_5);
  goto d_6;
  c_5 :
  y_4 :
  Tpop();
  Rpush(d_5);
  goto z_5;
  d_5 :
  Cpop();
  goto y_3;
  z_3 :
  Rpush(e_5);
  goto b_6;
  e_5 :
  y_3 :
  Epopd(0,2);
  Return();
  f_5 :
DOIT_END
