#include <stratego.h>
#include <stratego-lib.h>
#include <stratego-ext.h>
DOIT_START
cur_rule_counter = 0;
  Rpush(a_6);
  goto main;
  main :
  Epushd(0,0);
  BuildStr("list-zip-test");
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("test suite: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(a_0);
  goto i_11;
  a_0 :
  Tpop();
  Epopd(1,0);
  Rpush(b_0);
  goto j_11;
  b_0 :
  Rpush(h_0);
  goto o_11;
  h_0 :
  Rpush(i_0);
  goto v_11;
  i_0 :
  Rpush(j_0);
  goto w_11;
  j_0 :
  Rpush(k_0);
  goto k_11;
  k_0 :
  Rpush(l_0);
  goto m_11;
  l_0 :
  Epopd(0,0);
  Return();
  i_11 :
  Epushd(0,0);
  _ST_printnl();
  Epopd(0,0);
  Return();
  j_11 :
  Epushd(0,0);
  BuildInt(0);
  Tpush();
  BuildInt(0);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(0,0);
  Return();
  k_11 :
  Epushd(0,0);
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("successes: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(m_0);
  goto i_11;
  m_0 :
  Tpop();
  Epopd(1,0);
  OneNextSon();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("failures: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(n_0);
  goto i_11;
  n_0 :
  Tpop();
  Epopd(1,0);
  OneNextSon();
  Rpush(o_0);
  goto l_11;
  o_0 :
  AllBuild();
  AllBuild();
  Epopd(0,0);
  Return();
  l_11 :
  MatchFun("TNil",0);
  Return();
  m_11 :
  Epushd(0,0);
  Cpush(q_0);
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  MatchInt(0);
  OneNextSon();
  Rpush(r_0);
  goto l_11;
  r_0 :
  AllBuild();
  AllBuild();
  BuildInt(0);
  Rpush(s_0);
  goto n_11;
  s_0 :
  Cpop();
  goto p_0;
  q_0 :
  BuildInt(1);
  Rpush(t_0);
  goto n_11;
  t_0 :
  p_0 :
  Epopd(0,0);
  Return();
  n_11 :
  Epushd(0,0);
  _ST_exit();
  Epopd(0,0);
  Return();
  o_11 :
  Epushd(0,2);
  Tdupl();
  BuildStr("tuple-zip-test");
  Rpush(u_0);
  goto s_11;
  u_0 :
  Tpop();
  Cpush(w_0);
  Tdupl();
  Cpush(y_0);
  BuildInt(1);
  Tpush();
  BuildInt(2);
  Tpush();
  BuildInt(3);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildInt(4);
  Tpush();
  BuildInt(5);
  Tpush();
  BuildInt(6);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildInt(7);
  Tpush();
  BuildInt(8);
  Tpush();
  BuildInt(9);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epushd(1,0);
  Rpush(z_0);
  l_4 :
  Cpush(l_1);
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  Epushd(4,0);
  Rpush(m_1);
  m_4 :
  Cpush(o_1);
  Rpush(p_1);
  goto l_11;
  p_1 :
  Cpop();
  goto n_1;
  o_1 :
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Epushd(5,2);
  MatchFun("Cons",2);
  Arg(0);
  MatchVard(5,2);
  Tpop();
  Arg(1);
  MatchVard(5,1);
  Tpop();
  BuildVard(5,2);
  Epopd(5,2);
  OneNextSon();
  Rpush(q_1);
  goto m_4;
  q_1 :
  AllBuild();
  n_1 :
  Return();
  m_1 :
  Epopd(4,0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,0);
  Rpush(r_1);
  n_4 :
  Cpush(t_1);
  Rpush(u_1);
  goto l_11;
  u_1 :
  Cpop();
  goto s_1;
  t_1 :
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Epushd(6,2);
  MatchFun("Cons",2);
  Arg(0);
  MatchVard(6,1);
  Tpop();
  Arg(1);
  MatchVard(6,2);
  Tpop();
  BuildVard(6,2);
  Epopd(6,2);
  OneNextSon();
  Rpush(v_1);
  goto n_4;
  v_1 :
  AllBuild();
  s_1 :
  Return();
  r_1 :
  Epopd(5,0);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Rpush(w_1);
  goto l_4;
  w_1 :
  OneNextSon();
  Rpush(x_1);
  goto l_11;
  x_1 :
  AllBuild();
  AllBuild();
  Epushd(2,2);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(2,1);
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(2,2);
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  BuildVard(2,1);
  Tpush();
  BuildVard(2,2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(2,2);
  Cpop();
  goto k_1;
  l_1 :
  Epushd(2,0);
  Rpush(y_1);
  o_4 :
  Cpush(a_2);
  Rpush(b_2);
  goto l_11;
  b_2 :
  Cpop();
  goto z_1;
  a_2 :
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Rpush(c_2);
  goto u_11;
  c_2 :
  OneNextSon();
  Rpush(d_2);
  goto o_4;
  d_2 :
  AllBuild();
  z_1 :
  Return();
  y_1 :
  Epopd(2,0);
  BuildFun("Nil",0);
  k_1 :
  Return();
  z_0 :
  Epopd(1,0);
  MatchVard(0,1);
  Cpop();
  goto x_0;
  y_0 :
  BuildStr("  failed");
  Rpush(e_2);
  goto s_11;
  e_2 :
  Rpush(f_2);
  goto t_11;
  f_2 :
  x_0 :
  BuildInt(1);
  Tpush();
  BuildInt(4);
  Tpush();
  BuildInt(7);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildInt(2);
  Tpush();
  BuildInt(5);
  Tpush();
  BuildInt(8);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildInt(3);
  Tpush();
  BuildInt(6);
  Tpush();
  BuildInt(9);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  MatchVard(0,2);
  Cpush(h_2);
  BuildVard(0,2);
  MatchVard(0,1);
  Cpop();
  goto g_2;
  h_2 :
  BuildVard(0,1);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  result not equal: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(i_2);
  goto i_11;
  i_2 :
  Tpop();
  Epopd(1,0);
  BuildVard(0,2);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  expected: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(j_2);
  goto i_11;
  j_2 :
  Tpop();
  Epopd(1,0);
  Rpush(k_2);
  goto t_11;
  k_2 :
  g_2 :
  Tpop();
  Rpush(n_2);
  goto p_11;
  n_2 :
  Cpop();
  goto v_0;
  w_0 :
  Rpush(o_2);
  goto r_11;
  o_2 :
  v_0 :
  Epopd(0,2);
  Return();
  p_11 :
  Epushd(0,0);
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Epushd(1,1);
  MatchVard(1,1);
  BuildVard(1,1);
  Tpush();
  BuildInt(1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(p_2);
  goto q_11;
  p_2 :
  Epopd(1,1);
  OneNextSon();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  Rpush(q_2);
  goto l_11;
  q_2 :
  AllBuild();
  AllBuild();
  Epopd(0,0);
  Return();
  q_11 :
  Epushd(0,0);
  _ST_add();
  Epopd(0,0);
  Return();
  r_11 :
  Epushd(0,0);
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Epushd(1,1);
  MatchVard(1,1);
  BuildVard(1,1);
  Tpush();
  BuildInt(1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(r_2);
  goto q_11;
  r_2 :
  Epopd(1,1);
  OneNextSon();
  Rpush(s_2);
  goto l_11;
  s_2 :
  AllBuild();
  AllBuild();
  Epopd(0,0);
  Return();
  s_11 :
  Epushd(0,0);
  Tdupl();
  Epushd(1,1);
  MatchVard(1,1);
  Epushd(2,1);
  BuildVard(1,1);
  BuildFun("stderr",0);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(1,1);
  Epushd(4,1);
  MatchVard(4,1);
  BuildVard(4,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Epopd(4,1);
  MatchVard(3,1);
  BuildVard(2,1);
  Tpush();
  BuildVard(3,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(3,1);
  Epopd(2,1);
  Epopd(1,1);
  Rpush(t_2);
  goto i_11;
  t_2 :
  Tpop();
  Epopd(0,0);
  Return();
  t_11 :
  Epushd(0,1);
  MatchVard(0,1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  Epopd(0,1);
  Return();
  u_11 :
  MatchFun("Nil",0);
  Return();
  v_11 :
  Epushd(0,2);
  Tdupl();
  BuildStr("tuple-unzip-test");
  Rpush(u_2);
  goto s_11;
  u_2 :
  Tpop();
  Cpush(w_2);
  Tdupl();
  Cpush(y_2);
  BuildInt(1);
  Tpush();
  BuildInt(4);
  Tpush();
  BuildInt(7);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildInt(2);
  Tpush();
  BuildInt(5);
  Tpush();
  BuildInt(8);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildInt(3);
  Tpush();
  BuildInt(6);
  Tpush();
  BuildInt(9);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epushd(1,0);
  Rpush(z_2);
  o_8 :
  Cpush(b_3);
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  Epushd(4,0);
  Rpush(c_3);
  p_8 :
  Cpush(e_3);
  Rpush(f_3);
  goto u_11;
  f_3 :
  Cpop();
  goto d_3;
  e_3 :
  MatchFun("Cons",2);
  TravInit();
  OneNextSon();
  Epushd(5,2);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(5,2);
  Tpop();
  Arg(1);
  MatchVard(5,1);
  Tpop();
  BuildVard(5,2);
  Epopd(5,2);
  OneNextSon();
  Rpush(g_3);
  goto p_8;
  g_3 :
  AllBuild();
  d_3 :
  Return();
  c_3 :
  Epopd(4,0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,0);
  Rpush(h_3);
  q_8 :
  Cpush(j_3);
  Rpush(k_3);
  goto u_11;
  k_3 :
  Cpop();
  goto i_3;
  j_3 :
  MatchFun("Cons",2);
  TravInit();
  OneNextSon();
  Epushd(6,2);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(6,1);
  Tpop();
  Arg(1);
  MatchVard(6,2);
  Tpop();
  BuildVard(6,2);
  Epopd(6,2);
  OneNextSon();
  Rpush(l_3);
  goto q_8;
  l_3 :
  AllBuild();
  i_3 :
  Return();
  h_3 :
  Epopd(5,0);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Rpush(m_3);
  goto o_8;
  m_3 :
  OneNextSon();
  Rpush(n_3);
  goto l_11;
  n_3 :
  AllBuild();
  AllBuild();
  Epushd(2,2);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(2,1);
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(2,2);
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  BuildVard(2,1);
  Tpush();
  BuildVard(2,2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(2,2);
  Cpop();
  goto a_3;
  b_3 :
  Epushd(2,0);
  Rpush(o_3);
  v_8 :
  Cpush(q_3);
  Rpush(r_3);
  goto u_11;
  r_3 :
  Cpop();
  goto p_3;
  q_3 :
  MatchFun("Cons",2);
  TravInit();
  OneNextSon();
  Rpush(p_4);
  goto l_11;
  p_4 :
  OneNextSon();
  Rpush(r_4);
  goto v_8;
  r_4 :
  AllBuild();
  p_3 :
  Return();
  o_3 :
  Epopd(2,0);
  BuildFun("TNil",0);
  a_3 :
  Return();
  z_2 :
  Epopd(1,0);
  MatchVard(0,1);
  Cpop();
  goto x_2;
  y_2 :
  BuildStr("  failed");
  Rpush(t_4);
  goto s_11;
  t_4 :
  Rpush(u_4);
  goto t_11;
  u_4 :
  x_2 :
  BuildInt(1);
  Tpush();
  BuildInt(2);
  Tpush();
  BuildInt(3);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildInt(4);
  Tpush();
  BuildInt(5);
  Tpush();
  BuildInt(6);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildInt(7);
  Tpush();
  BuildInt(8);
  Tpush();
  BuildInt(9);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  MatchVard(0,2);
  Cpush(w_4);
  BuildVard(0,2);
  MatchVard(0,1);
  Cpop();
  goto v_4;
  w_4 :
  BuildVard(0,1);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  result not equal: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(b_5);
  goto i_11;
  b_5 :
  Tpop();
  Epopd(1,0);
  BuildVard(0,2);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  expected: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(c_5);
  goto i_11;
  c_5 :
  Tpop();
  Epopd(1,0);
  Rpush(d_5);
  goto t_11;
  d_5 :
  v_4 :
  Tpop();
  Rpush(e_5);
  goto p_11;
  e_5 :
  Cpop();
  goto v_2;
  w_2 :
  Rpush(f_5);
  goto r_11;
  f_5 :
  v_2 :
  Epopd(0,2);
  Return();
  w_11 :
  Epushd(0,2);
  Tdupl();
  BuildStr("nzip0-test");
  Rpush(g_5);
  goto s_11;
  g_5 :
  Tpop();
  Cpush(i_5);
  Tdupl();
  Cpush(k_5);
  BuildStr("a");
  Tpush();
  BuildStr("b");
  Tpush();
  BuildStr("c");
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epushd(1,1);
  MatchVard(1,1);
  BuildInt(0);
  Tpush();
  BuildVard(1,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(l_5);
  h_11 :
  Cpush(n_5);
  Epushd(2,1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(2,1);
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchFun("Nil",0);
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  BuildFun("Nil",0);
  Epopd(2,1);
  Cpop();
  goto m_5;
  n_5 :
  Epushd(2,3);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(2,2);
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchFun("Cons",2);
  Arg(0);
  MatchVard(2,1);
  Tpop();
  Arg(1);
  MatchVard(2,3);
  Tpop();
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  Epushd(3,1);
  BuildVard(2,2);
  Tpush();
  BuildInt(1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(o_5);
  goto x_11;
  o_5 :
  MatchVard(3,1);
  BuildVard(2,2);
  Tpush();
  BuildVard(2,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildVard(3,1);
  Tpush();
  BuildVard(2,3);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(3,1);
  Epopd(2,3);
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Rpush(p_5);
  goto h_11;
  p_5 :
  OneNextSon();
  Rpush(q_5);
  goto l_11;
  q_5 :
  AllBuild();
  AllBuild();
  Epushd(2,2);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(2,1);
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(2,2);
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  BuildVard(2,1);
  Tpush();
  BuildVard(2,2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(2,2);
  m_5 :
  Return();
  l_5 :
  Epopd(1,1);
  MatchVard(0,1);
  Cpop();
  goto j_5;
  k_5 :
  BuildStr("  failed");
  Rpush(r_5);
  goto s_11;
  r_5 :
  Rpush(s_5);
  goto t_11;
  s_5 :
  j_5 :
  BuildInt(0);
  Tpush();
  BuildStr("a");
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildInt(1);
  Tpush();
  BuildStr("b");
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildInt(2);
  Tpush();
  BuildStr("c");
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  MatchVard(0,2);
  Cpush(u_5);
  BuildVard(0,2);
  MatchVard(0,1);
  Cpop();
  goto t_5;
  u_5 :
  BuildVard(0,1);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  result not equal: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(v_5);
  goto i_11;
  v_5 :
  Tpop();
  Epopd(1,0);
  BuildVard(0,2);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  expected: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(w_5);
  goto i_11;
  w_5 :
  Tpop();
  Epopd(1,0);
  Rpush(x_5);
  goto t_11;
  x_5 :
  t_5 :
  Tpop();
  Rpush(y_5);
  goto p_11;
  y_5 :
  Cpop();
  goto h_5;
  i_5 :
  Rpush(z_5);
  goto r_11;
  z_5 :
  h_5 :
  Epopd(0,2);
  Return();
  x_11 :
  Epushd(0,0);
  _ST_plus();
  Epopd(0,0);
  Return();
  a_6 :
DOIT_END
