#include <stratego.h>
#include <stratego-lib.h>
#include <stratego-ext.h>
DOIT_START
cur_rule_counter = 0;
  Rpush(j_3);
  goto main;
  main :
  Epushd(0,0);
  BuildStr("as-pattern-test");
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("test suite: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(a_0);
  goto q_4;
  a_0 :
  Tpop();
  Epopd(1,0);
  Rpush(b_0);
  goto r_4;
  b_0 :
  Rpush(h_0);
  goto w_4;
  h_0 :
  Rpush(i_0);
  goto c_5;
  i_0 :
  Rpush(j_0);
  goto s_4;
  j_0 :
  Rpush(k_0);
  goto u_4;
  k_0 :
  Epopd(0,0);
  Return();
  q_4 :
  Epushd(0,0);
  _ST_printnl();
  Epopd(0,0);
  Return();
  r_4 :
  Epushd(0,0);
  BuildInt(0);
  Tpush();
  BuildInt(0);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(0,0);
  Return();
  s_4 :
  Epushd(0,0);
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("successes: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(l_0);
  goto q_4;
  l_0 :
  Tpop();
  Epopd(1,0);
  OneNextSon();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("failures: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(m_0);
  goto q_4;
  m_0 :
  Tpop();
  Epopd(1,0);
  OneNextSon();
  Rpush(n_0);
  goto t_4;
  n_0 :
  AllBuild();
  AllBuild();
  Epopd(0,0);
  Return();
  t_4 :
  MatchFun("TNil",0);
  Return();
  u_4 :
  Epushd(0,0);
  Cpush(p_0);
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  MatchInt(0);
  OneNextSon();
  Rpush(q_0);
  goto t_4;
  q_0 :
  AllBuild();
  AllBuild();
  BuildInt(0);
  Rpush(r_0);
  goto v_4;
  r_0 :
  Cpop();
  goto o_0;
  p_0 :
  BuildInt(1);
  Rpush(s_0);
  goto v_4;
  s_0 :
  o_0 :
  Epopd(0,0);
  Return();
  v_4 :
  Epushd(0,0);
  _ST_exit();
  Epopd(0,0);
  Return();
  w_4 :
  Epushd(0,2);
  Tdupl();
  BuildStr("as-pattern1");
  Rpush(t_0);
  goto a_5;
  t_0 :
  Tpop();
  Cpush(v_0);
  Tdupl();
  Cpush(x_0);
  BuildFun("B",0);
  Tpush();
  BuildFun("A",0);
  Tpush();
  BuildFun("C",0);
  Tpush();
  BuildFun("G",2);
  Tpush();
  BuildFun("F",2);
  Epushd(1,3);
  MatchFun("F",2);
  Arg(0);
  MatchVard(1,1);
  Tpop();
  Arg(1);
  MatchVard(1,2);
  MatchFun("G",2);
  Arg(0);
  MatchFun("A",0);
  Tpop();
  Arg(1);
  MatchVard(1,3);
  Tpop();
  Tpop();
  BuildVard(1,1);
  Tpush();
  BuildVard(1,2);
  Tpush();
  BuildVard(1,3);
  Tpush();
  BuildFun("H",3);
  Epopd(1,3);
  MatchVard(0,1);
  Cpop();
  goto w_0;
  x_0 :
  BuildStr("  failed");
  Rpush(y_0);
  goto a_5;
  y_0 :
  Rpush(z_0);
  goto b_5;
  z_0 :
  w_0 :
  BuildFun("B",0);
  Tpush();
  BuildFun("A",0);
  Tpush();
  BuildFun("C",0);
  Tpush();
  BuildFun("G",2);
  Tpush();
  BuildFun("C",0);
  Tpush();
  BuildFun("H",3);
  MatchVard(0,2);
  Cpush(l_1);
  BuildVard(0,2);
  MatchVard(0,1);
  Cpop();
  goto c_1;
  l_1 :
  BuildVard(0,1);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  result not equal: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(m_1);
  goto q_4;
  m_1 :
  Tpop();
  Epopd(1,0);
  BuildVard(0,2);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  expected: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(n_1);
  goto q_4;
  n_1 :
  Tpop();
  Epopd(1,0);
  Rpush(q_1);
  goto b_5;
  q_1 :
  c_1 :
  Tpop();
  Rpush(r_1);
  goto x_4;
  r_1 :
  Cpop();
  goto u_0;
  v_0 :
  Rpush(s_1);
  goto z_4;
  s_1 :
  u_0 :
  Epopd(0,2);
  Return();
  x_4 :
  Epushd(0,0);
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Epushd(1,1);
  MatchVard(1,1);
  BuildVard(1,1);
  Tpush();
  BuildInt(1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(t_1);
  goto y_4;
  t_1 :
  Epopd(1,1);
  OneNextSon();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  Rpush(u_1);
  goto t_4;
  u_1 :
  AllBuild();
  AllBuild();
  Epopd(0,0);
  Return();
  y_4 :
  Epushd(0,0);
  _ST_add();
  Epopd(0,0);
  Return();
  z_4 :
  Epushd(0,0);
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Epushd(1,1);
  MatchVard(1,1);
  BuildVard(1,1);
  Tpush();
  BuildInt(1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(v_1);
  goto y_4;
  v_1 :
  Epopd(1,1);
  OneNextSon();
  Rpush(w_1);
  goto t_4;
  w_1 :
  AllBuild();
  AllBuild();
  Epopd(0,0);
  Return();
  a_5 :
  Epushd(0,0);
  Tdupl();
  Epushd(1,1);
  MatchVard(1,1);
  Epushd(2,1);
  BuildVard(1,1);
  BuildFun("stderr",0);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(1,1);
  Epushd(4,1);
  MatchVard(4,1);
  BuildVard(4,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Epopd(4,1);
  MatchVard(3,1);
  BuildVard(2,1);
  Tpush();
  BuildVard(3,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(3,1);
  Epopd(2,1);
  Epopd(1,1);
  Rpush(x_1);
  goto q_4;
  x_1 :
  Tpop();
  Epopd(0,0);
  Return();
  b_5 :
  Epushd(0,1);
  MatchVard(0,1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  Epopd(0,1);
  Return();
  c_5 :
  Epushd(0,2);
  Tdupl();
  BuildStr("as-pattern2");
  Rpush(y_1);
  goto a_5;
  y_1 :
  Tpop();
  Cpush(a_2);
  Tdupl();
  Cpush(c_2);
  BuildFun("B",0);
  Tpush();
  BuildFun("C",0);
  Tpush();
  BuildFun("B",0);
  Tpush();
  BuildFun("G",2);
  Tpush();
  BuildFun("F",2);
  Cpush(e_2);
  Epushd(1,3);
  MatchFun("F",2);
  Arg(0);
  MatchVard(1,1);
  Tpop();
  Arg(1);
  MatchVard(1,2);
  MatchFun("G",2);
  Arg(0);
  MatchFun("A",0);
  Tpop();
  Arg(1);
  MatchVard(1,3);
  Tpop();
  Tpop();
  BuildVard(1,1);
  Tpush();
  BuildVard(1,2);
  Tpush();
  BuildVard(1,3);
  Tpush();
  BuildFun("H",3);
  Epopd(1,3);
  Cpop();
  goto d_2;
  e_2 :
  Epushd(1,2);
  MatchFun("F",2);
  Arg(0);
  MatchVard(1,1);
  Tpop();
  Arg(1);
  MatchFun("G",2);
  Arg(0);
  MatchVard(1,2);
  Tpop();
  Arg(1);
  MatchFun("B",0);
  Tpop();
  Tpop();
  BuildVard(1,1);
  Tpush();
  BuildVard(1,2);
  Tpush();
  BuildFun("B",0);
  Tpush();
  BuildFun("H",3);
  Epopd(1,2);
  d_2 :
  MatchVard(0,1);
  Cpop();
  goto b_2;
  c_2 :
  BuildStr("  failed");
  Rpush(f_2);
  goto a_5;
  f_2 :
  Rpush(g_2);
  goto b_5;
  g_2 :
  b_2 :
  BuildFun("B",0);
  Tpush();
  BuildFun("C",0);
  Tpush();
  BuildFun("B",0);
  Tpush();
  BuildFun("H",3);
  MatchVard(0,2);
  Cpush(b_3);
  BuildVard(0,2);
  MatchVard(0,1);
  Cpop();
  goto v_2;
  b_3 :
  BuildVard(0,1);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  result not equal: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(c_3);
  goto q_4;
  c_3 :
  Tpop();
  Epopd(1,0);
  BuildVard(0,2);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  expected: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(d_3);
  goto q_4;
  d_3 :
  Tpop();
  Epopd(1,0);
  Rpush(e_3);
  goto b_5;
  e_3 :
  v_2 :
  Tpop();
  Rpush(f_3);
  goto x_4;
  f_3 :
  Cpop();
  goto z_1;
  a_2 :
  Rpush(i_3);
  goto z_4;
  i_3 :
  z_1 :
  Epopd(0,2);
  Return();
  j_3 :
DOIT_END
