#include <stratego.h>
#include <stratego-lib.h>
#include <stratego-ext.h>
DOIT_START
cur_rule_counter = 0;
  Rpush(v_1);
  goto main;
  main :
  Epushd(0,0);
  BuildStr("congruence-env-test");
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("test suite: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(a_0);
  goto v_32;
  a_0 :
  Tpop();
  Epopd(1,0);
  Rpush(b_0);
  goto w_32;
  b_0 :
  Rpush(c_0);
  goto b_33;
  c_0 :
  Rpush(d_0);
  goto h_33;
  d_0 :
  Rpush(e_0);
  goto x_32;
  e_0 :
  Rpush(f_0);
  goto z_32;
  f_0 :
  Epopd(0,0);
  Return();
  v_32 :
  Epushd(0,0);
  _ST_printnl();
  Epopd(0,0);
  Return();
  w_32 :
  Epushd(0,0);
  BuildInt(0);
  Tpush();
  BuildInt(0);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(0,0);
  Return();
  x_32 :
  Epushd(0,0);
  MatchFun("TCons");
  TravInit();
  OneNextSon();
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("successes: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(g_0);
  goto v_32;
  g_0 :
  Tpop();
  Epopd(1,0);
  OneNextSon();
  MatchFun("TCons");
  TravInit();
  OneNextSon();
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("failures: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(h_0);
  goto v_32;
  h_0 :
  Tpop();
  Epopd(1,0);
  OneNextSon();
  Rpush(i_0);
  goto y_32;
  i_0 :
  AllBuild();
  AllBuild();
  Epopd(0,0);
  Return();
  y_32 :
  MatchFun("TNil");
  Return();
  z_32 :
  Epushd(0,0);
  Cpush(k_0);
  MatchFun("TCons");
  TravInit();
  OneNextSon();
  OneNextSon();
  MatchFun("TCons");
  TravInit();
  OneNextSon();
  MatchInt(0);
  OneNextSon();
  Rpush(l_0);
  goto y_32;
  l_0 :
  AllBuild();
  AllBuild();
  BuildInt(0);
  Rpush(m_0);
  goto a_33;
  m_0 :
  Cpop();
  goto j_0;
  k_0 :
  BuildInt(1);
  Rpush(n_0);
  goto a_33;
  n_0 :
  j_0 :
  Epopd(0,0);
  Return();
  a_33 :
  Epushd(0,0);
  _ST_exit();
  Epopd(0,0);
  Return();
  b_33 :
  Epushd(0,2);
  Tdupl();
  BuildStr("congruence-dist-test");
  Rpush(o_0);
  goto f_33;
  o_0 :
  Tpop();
  Cpush(q_0);
  Tdupl();
  Cpush(s_0);
  BuildFun("Id",0);
  Tpush();
  BuildFun("Id",0);
  Tpush();
  BuildFun("Id",0);
  Tpush();
  BuildFun("If",3);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Pair",2);
  Epushd(1,7);
  MatchFun("Pair");
  Arg(0);
  MatchFun("If");
  Arg(0);
  MatchVard(1,2);
  Tpop();
  Arg(1);
  MatchVard(1,3);
  Tpop();
  Arg(2);
  MatchVard(1,4);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(1,1);
  Tpop();
  Tdupl();
  BuildVard(1,2);
  Tpush();
  BuildVard(1,1);
  Tpush();
  BuildFun("Pair",2);
  MatchVard(1,5);
  BuildVard(1,3);
  Tpush();
  BuildVard(1,1);
  Tpush();
  BuildFun("Pair",2);
  MatchVard(1,6);
  BuildVard(1,4);
  Tpush();
  BuildVard(1,1);
  Tpush();
  BuildFun("Pair",2);
  MatchVard(1,7);
  Tpop();
  BuildVard(1,5);
  Tpush();
  BuildVard(1,6);
  Tpush();
  BuildVard(1,7);
  Tpush();
  BuildFun("If",3);
  Epopd(1,7);
  MatchVard(0,1);
  Cpop();
  goto r_0;
  s_0 :
  BuildStr("  failed");
  Rpush(t_0);
  goto f_33;
  t_0 :
  Rpush(u_0);
  goto g_33;
  u_0 :
  r_0 :
  BuildFun("Id",0);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Pair",2);
  Tpush();
  BuildFun("Id",0);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Pair",2);
  Tpush();
  BuildFun("Id",0);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Pair",2);
  Tpush();
  BuildFun("If",3);
  MatchVard(0,2);
  Cpush(w_0);
  BuildVard(0,2);
  MatchVard(0,1);
  Cpop();
  goto v_0;
  w_0 :
  BuildVard(0,1);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  result not equal: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(x_0);
  goto v_32;
  x_0 :
  Tpop();
  Epopd(1,0);
  BuildVard(0,2);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  expected: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(y_0);
  goto v_32;
  y_0 :
  Tpop();
  Epopd(1,0);
  Rpush(z_0);
  goto g_33;
  z_0 :
  v_0 :
  Tpop();
  Rpush(a_1);
  goto c_33;
  a_1 :
  Cpop();
  goto p_0;
  q_0 :
  Rpush(b_1);
  goto e_33;
  b_1 :
  p_0 :
  Epopd(0,2);
  Return();
  c_33 :
  Epushd(0,0);
  MatchFun("TCons");
  TravInit();
  OneNextSon();
  Epushd(1,1);
  MatchVard(1,1);
  BuildVard(1,1);
  Tpush();
  BuildInt(1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(c_1);
  goto d_33;
  c_1 :
  Epopd(1,1);
  OneNextSon();
  MatchFun("TCons");
  TravInit();
  OneNextSon();
  OneNextSon();
  Rpush(d_1);
  goto y_32;
  d_1 :
  AllBuild();
  AllBuild();
  Epopd(0,0);
  Return();
  d_33 :
  Epushd(0,0);
  _ST_add();
  Epopd(0,0);
  Return();
  e_33 :
  Epushd(0,0);
  MatchFun("TCons");
  TravInit();
  OneNextSon();
  OneNextSon();
  MatchFun("TCons");
  TravInit();
  OneNextSon();
  Epushd(1,1);
  MatchVard(1,1);
  BuildVard(1,1);
  Tpush();
  BuildInt(1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(e_1);
  goto d_33;
  e_1 :
  Epopd(1,1);
  OneNextSon();
  Rpush(f_1);
  goto y_32;
  f_1 :
  AllBuild();
  AllBuild();
  Epopd(0,0);
  Return();
  f_33 :
  Epushd(0,0);
  Tdupl();
  Epushd(1,1);
  MatchVard(1,1);
  Epushd(2,1);
  BuildVard(1,1);
  BuildFun("stderr",0);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(1,1);
  Epushd(4,1);
  MatchVard(4,1);
  BuildVard(4,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Epopd(4,1);
  MatchVard(3,1);
  BuildVard(2,1);
  Tpush();
  BuildVard(3,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(3,1);
  Epopd(2,1);
  Epopd(1,1);
  Rpush(g_1);
  goto v_32;
  g_1 :
  Tpop();
  Epopd(0,0);
  Return();
  g_33 :
  Epushd(0,1);
  MatchVard(0,1);
  MatchFun("TCons");
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Arg(1);
  MatchFun("TCons");
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Arg(1);
  MatchFun("TNil");
  Tpop();
  Tpop();
  Epopd(0,1);
  Return();
  h_33 :
  Epushd(0,2);
  Tdupl();
  BuildStr("congruence-thread-test");
  Rpush(h_1);
  goto f_33;
  h_1 :
  Tpop();
  Cpush(j_1);
  Tdupl();
  Cpush(l_1);
  BuildFun("Id",0);
  Tpush();
  BuildFun("Id",0);
  Tpush();
  BuildFun("Id",0);
  Tpush();
  BuildFun("If",3);
  Tpush();
  BuildFun("Zero",0);
  Tpush();
  BuildFun("Pair",2);
  Epushd(1,10);
  MatchFun("Pair");
  Arg(0);
  MatchFun("If");
  Arg(0);
  MatchVard(1,5);
  Tpop();
  Arg(1);
  MatchVard(1,6);
  Tpop();
  Arg(2);
  MatchVard(1,7);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(1,1);
  Tpop();
  Tdupl();
  BuildVard(1,5);
  Tpush();
  BuildVard(1,1);
  Tpush();
  BuildFun("Pair",2);
  Epushd(2,1);
  MatchFun("Pair");
  Arg(0);
  MatchFun("Id");
  Tpop();
  Arg(1);
  MatchVard(2,1);
  Tpop();
  BuildFun("Id",0);
  Tpush();
  BuildVard(2,1);
  Tpush();
  BuildFun("Succ",1);
  Tpush();
  BuildFun("Pair",2);
  Epopd(2,1);
  MatchFun("Pair");
  Arg(0);
  MatchVard(1,8);
  Tpop();
  Arg(1);
  MatchVard(1,2);
  Tpop();
  BuildVard(1,6);
  Tpush();
  BuildVard(1,2);
  Tpush();
  BuildFun("Pair",2);
  Epushd(2,1);
  MatchFun("Pair");
  Arg(0);
  MatchFun("Id");
  Tpop();
  Arg(1);
  MatchVard(2,1);
  Tpop();
  BuildFun("Id",0);
  Tpush();
  BuildVard(2,1);
  Tpush();
  BuildFun("Succ",1);
  Tpush();
  BuildFun("Pair",2);
  Epopd(2,1);
  MatchFun("Pair");
  Arg(0);
  MatchVard(1,9);
  Tpop();
  Arg(1);
  MatchVard(1,3);
  Tpop();
  BuildVard(1,7);
  Tpush();
  BuildVard(1,3);
  Tpush();
  BuildFun("Pair",2);
  Epushd(2,1);
  MatchFun("Pair");
  Arg(0);
  MatchFun("Id");
  Tpop();
  Arg(1);
  MatchVard(2,1);
  Tpop();
  BuildFun("Id",0);
  Tpush();
  BuildVard(2,1);
  Tpush();
  BuildFun("Succ",1);
  Tpush();
  BuildFun("Pair",2);
  Epopd(2,1);
  MatchFun("Pair");
  Arg(0);
  MatchVard(1,10);
  Tpop();
  Arg(1);
  MatchVard(1,4);
  Tpop();
  Tpop();
  BuildVard(1,8);
  Tpush();
  BuildVard(1,9);
  Tpush();
  BuildVard(1,10);
  Tpush();
  BuildFun("If",3);
  Tpush();
  BuildVard(1,4);
  Tpush();
  BuildFun("Pair",2);
  Epopd(1,10);
  MatchVard(0,1);
  Cpop();
  goto k_1;
  l_1 :
  BuildStr("  failed");
  Rpush(m_1);
  goto f_33;
  m_1 :
  Rpush(n_1);
  goto g_33;
  n_1 :
  k_1 :
  BuildFun("Id",0);
  Tpush();
  BuildFun("Id",0);
  Tpush();
  BuildFun("Id",0);
  Tpush();
  BuildFun("If",3);
  Tpush();
  BuildFun("Zero",0);
  Tpush();
  BuildFun("Succ",1);
  Tpush();
  BuildFun("Succ",1);
  Tpush();
  BuildFun("Succ",1);
  Tpush();
  BuildFun("Pair",2);
  MatchVard(0,2);
  Cpush(p_1);
  BuildVard(0,2);
  MatchVard(0,1);
  Cpop();
  goto o_1;
  p_1 :
  BuildVard(0,1);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  result not equal: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(q_1);
  goto v_32;
  q_1 :
  Tpop();
  Epopd(1,0);
  BuildVard(0,2);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  expected: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(r_1);
  goto v_32;
  r_1 :
  Tpop();
  Epopd(1,0);
  Rpush(s_1);
  goto g_33;
  s_1 :
  o_1 :
  Tpop();
  Rpush(t_1);
  goto c_33;
  t_1 :
  Cpop();
  goto i_1;
  j_1 :
  Rpush(u_1);
  goto e_33;
  u_1 :
  i_1 :
  Epopd(0,2);
  Return();
  v_1 :
DOIT_END
