#include <stratego.h>
#include <stratego-lib.h>
#include <stratego-ext.h>
DOIT_START
cur_rule_counter = 0;
  Rpush(j_4);
  goto main;
  main :
  Epushd(0,0);
  BuildStr("match-arity");
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("test suite: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(a_0);
  goto i_35;
  a_0 :
  Tpop();
  Epopd(1,0);
  Rpush(b_0);
  goto j_35;
  b_0 :
  Rpush(c_0);
  goto o_35;
  c_0 :
  Rpush(d_0);
  goto u_35;
  d_0 :
  Rpush(e_0);
  goto v_35;
  e_0 :
  Rpush(f_0);
  goto w_35;
  f_0 :
  Rpush(g_0);
  goto x_35;
  g_0 :
  Rpush(h_0);
  goto y_35;
  h_0 :
  Rpush(i_0);
  goto k_35;
  i_0 :
  Rpush(j_0);
  goto m_35;
  j_0 :
  Epopd(0,0);
  Return();
  i_35 :
  Epushd(0,0);
  _ST_printnl();
  Epopd(0,0);
  Return();
  j_35 :
  Epushd(0,0);
  BuildInt(0);
  Tpush();
  BuildInt(0);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(0,0);
  Return();
  k_35 :
  Epushd(0,0);
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("successes: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(k_0);
  goto i_35;
  k_0 :
  Tpop();
  Epopd(1,0);
  OneNextSon();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("failures: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(l_0);
  goto i_35;
  l_0 :
  Tpop();
  Epopd(1,0);
  OneNextSon();
  Rpush(m_0);
  goto l_35;
  m_0 :
  AllBuild();
  AllBuild();
  Epopd(0,0);
  Return();
  l_35 :
  MatchFun("TNil",0);
  Return();
  m_35 :
  Epushd(0,0);
  Cpush(o_0);
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  MatchInt(0);
  OneNextSon();
  Rpush(p_0);
  goto l_35;
  p_0 :
  AllBuild();
  AllBuild();
  BuildInt(0);
  Rpush(q_0);
  goto n_35;
  q_0 :
  Cpop();
  goto n_0;
  o_0 :
  BuildInt(1);
  Rpush(r_0);
  goto n_35;
  r_0 :
  n_0 :
  Epopd(0,0);
  Return();
  n_35 :
  Epushd(0,0);
  _ST_exit();
  Epopd(0,0);
  Return();
  o_35 :
  Epushd(0,2);
  Tdupl();
  BuildStr("match-arity1");
  Rpush(s_0);
  goto s_35;
  s_0 :
  Tpop();
  Cpush(u_0);
  Tdupl();
  Cpush(w_0);
  BuildFun("Skip",0);
  Tpush();
  BuildFun("Skip",0);
  Tpush();
  BuildFun("Skip",0);
  Tpush();
  BuildFun("If",3);
  Cpush(x_0);
  Tdupl();
  Epushd(1,2);
  MatchFun("If",2);
  Arg(0);
  MatchVard(1,1);
  Tpop();
  Arg(1);
  MatchVard(1,2);
  Tpop();
  BuildVard(1,1);
  Tpush();
  BuildVard(1,2);
  Tpush();
  BuildFun("Skip",0);
  Tpush();
  BuildFun("If",3);
  Epopd(1,2);
  Cpop();
  Crestore();
  Cjump();
  x_0 :
  MatchVard(0,1);
  Cpop();
  goto v_0;
  w_0 :
  BuildStr("  failed");
  Rpush(y_0);
  goto s_35;
  y_0 :
  Rpush(z_0);
  goto t_35;
  z_0 :
  v_0 :
  BuildFun("Skip",0);
  Tpush();
  BuildFun("Skip",0);
  Tpush();
  BuildFun("Skip",0);
  Tpush();
  BuildFun("If",3);
  MatchVard(0,2);
  Cpush(b_1);
  BuildVard(0,2);
  MatchVard(0,1);
  Cpop();
  goto a_1;
  b_1 :
  BuildVard(0,1);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  result not equal: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(c_1);
  goto i_35;
  c_1 :
  Tpop();
  Epopd(1,0);
  BuildVard(0,2);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  expected: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(d_1);
  goto i_35;
  d_1 :
  Tpop();
  Epopd(1,0);
  Rpush(e_1);
  goto t_35;
  e_1 :
  a_1 :
  Tpop();
  Rpush(f_1);
  goto p_35;
  f_1 :
  Cpop();
  goto t_0;
  u_0 :
  Rpush(g_1);
  goto r_35;
  g_1 :
  t_0 :
  Epopd(0,2);
  Return();
  p_35 :
  Epushd(0,0);
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Epushd(1,1);
  MatchVard(1,1);
  BuildVard(1,1);
  Tpush();
  BuildInt(1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(h_1);
  goto q_35;
  h_1 :
  Epopd(1,1);
  OneNextSon();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  Rpush(i_1);
  goto l_35;
  i_1 :
  AllBuild();
  AllBuild();
  Epopd(0,0);
  Return();
  q_35 :
  Epushd(0,0);
  _ST_add();
  Epopd(0,0);
  Return();
  r_35 :
  Epushd(0,0);
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Epushd(1,1);
  MatchVard(1,1);
  BuildVard(1,1);
  Tpush();
  BuildInt(1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(j_1);
  goto q_35;
  j_1 :
  Epopd(1,1);
  OneNextSon();
  Rpush(k_1);
  goto l_35;
  k_1 :
  AllBuild();
  AllBuild();
  Epopd(0,0);
  Return();
  s_35 :
  Epushd(0,0);
  Tdupl();
  Epushd(1,1);
  MatchVard(1,1);
  Epushd(2,1);
  BuildVard(1,1);
  BuildFun("stderr",0);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(1,1);
  Epushd(4,1);
  MatchVard(4,1);
  BuildVard(4,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Epopd(4,1);
  MatchVard(3,1);
  BuildVard(2,1);
  Tpush();
  BuildVard(3,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(3,1);
  Epopd(2,1);
  Epopd(1,1);
  Rpush(l_1);
  goto i_35;
  l_1 :
  Tpop();
  Epopd(0,0);
  Return();
  t_35 :
  Epushd(0,1);
  MatchVard(0,1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  Epopd(0,1);
  Return();
  u_35 :
  Epushd(0,2);
  Tdupl();
  BuildStr("match-arity2");
  Rpush(m_1);
  goto s_35;
  m_1 :
  Tpop();
  Cpush(o_1);
  Tdupl();
  Cpush(q_1);
  BuildFun("Skip",0);
  Tpush();
  BuildFun("Skip",0);
  Tpush();
  BuildFun("If",2);
  Cpush(r_1);
  Tdupl();
  Epushd(1,2);
  MatchFun("If",3);
  Arg(0);
  MatchVard(1,1);
  Tpop();
  Arg(1);
  MatchVard(1,2);
  Tpop();
  Arg(2);
  MatchFun("Skip",0);
  Tpop();
  BuildVard(1,1);
  Tpush();
  BuildVard(1,2);
  Tpush();
  BuildFun("If",2);
  Epopd(1,2);
  Cpop();
  Crestore();
  Cjump();
  r_1 :
  MatchVard(0,1);
  Cpop();
  goto p_1;
  q_1 :
  BuildStr("  failed");
  Rpush(s_1);
  goto s_35;
  s_1 :
  Rpush(t_1);
  goto t_35;
  t_1 :
  p_1 :
  BuildFun("Skip",0);
  Tpush();
  BuildFun("Skip",0);
  Tpush();
  BuildFun("If",2);
  MatchVard(0,2);
  Cpush(v_1);
  BuildVard(0,2);
  MatchVard(0,1);
  Cpop();
  goto u_1;
  v_1 :
  BuildVard(0,1);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  result not equal: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(w_1);
  goto i_35;
  w_1 :
  Tpop();
  Epopd(1,0);
  BuildVard(0,2);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  expected: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(x_1);
  goto i_35;
  x_1 :
  Tpop();
  Epopd(1,0);
  Rpush(y_1);
  goto t_35;
  y_1 :
  u_1 :
  Tpop();
  Rpush(z_1);
  goto p_35;
  z_1 :
  Cpop();
  goto n_1;
  o_1 :
  Rpush(a_2);
  goto r_35;
  a_2 :
  n_1 :
  Epopd(0,2);
  Return();
  v_35 :
  Epushd(0,2);
  Tdupl();
  BuildStr("match-arity3");
  Rpush(b_2);
  goto s_35;
  b_2 :
  Tpop();
  Cpush(d_2);
  Tdupl();
  Cpush(f_2);
  BuildFun("Skip",0);
  Tpush();
  BuildFun("Skip",0);
  Tpush();
  BuildFun("If",2);
  Epushd(1,2);
  MatchFun("If",2);
  Arg(0);
  MatchVard(1,1);
  Tpop();
  Arg(1);
  MatchVard(1,2);
  Tpop();
  BuildVard(1,1);
  Tpush();
  BuildVard(1,2);
  Tpush();
  BuildFun("Skip",0);
  Tpush();
  BuildFun("If",3);
  Epopd(1,2);
  MatchVard(0,1);
  Cpop();
  goto e_2;
  f_2 :
  BuildStr("  failed");
  Rpush(g_2);
  goto s_35;
  g_2 :
  Rpush(h_2);
  goto t_35;
  h_2 :
  e_2 :
  BuildFun("Skip",0);
  Tpush();
  BuildFun("Skip",0);
  Tpush();
  BuildFun("Skip",0);
  Tpush();
  BuildFun("If",3);
  MatchVard(0,2);
  Cpush(j_2);
  BuildVard(0,2);
  MatchVard(0,1);
  Cpop();
  goto i_2;
  j_2 :
  BuildVard(0,1);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  result not equal: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(k_2);
  goto i_35;
  k_2 :
  Tpop();
  Epopd(1,0);
  BuildVard(0,2);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  expected: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(l_2);
  goto i_35;
  l_2 :
  Tpop();
  Epopd(1,0);
  Rpush(m_2);
  goto t_35;
  m_2 :
  i_2 :
  Tpop();
  Rpush(n_2);
  goto p_35;
  n_2 :
  Cpop();
  goto c_2;
  d_2 :
  Rpush(o_2);
  goto r_35;
  o_2 :
  c_2 :
  Epopd(0,2);
  Return();
  w_35 :
  Epushd(0,2);
  Tdupl();
  BuildStr("match-arity4");
  Rpush(p_2);
  goto s_35;
  p_2 :
  Tpop();
  Cpush(r_2);
  Tdupl();
  Cpush(t_2);
  BuildFun("Skip",0);
  Tpush();
  BuildFun("Skip",0);
  Tpush();
  BuildFun("Skip",0);
  Tpush();
  BuildFun("If",3);
  Epushd(1,2);
  MatchFun("If",3);
  Arg(0);
  MatchVard(1,1);
  Tpop();
  Arg(1);
  MatchVard(1,2);
  Tpop();
  Arg(2);
  MatchFun("Skip",0);
  Tpop();
  BuildVard(1,1);
  Tpush();
  BuildVard(1,2);
  Tpush();
  BuildFun("If",2);
  Epopd(1,2);
  MatchVard(0,1);
  Cpop();
  goto s_2;
  t_2 :
  BuildStr("  failed");
  Rpush(u_2);
  goto s_35;
  u_2 :
  Rpush(v_2);
  goto t_35;
  v_2 :
  s_2 :
  BuildFun("Skip",0);
  Tpush();
  BuildFun("Skip",0);
  Tpush();
  BuildFun("If",2);
  MatchVard(0,2);
  Cpush(x_2);
  BuildVard(0,2);
  MatchVard(0,1);
  Cpop();
  goto w_2;
  x_2 :
  BuildVard(0,1);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  result not equal: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(y_2);
  goto i_35;
  y_2 :
  Tpop();
  Epopd(1,0);
  BuildVard(0,2);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  expected: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(z_2);
  goto i_35;
  z_2 :
  Tpop();
  Epopd(1,0);
  Rpush(a_3);
  goto t_35;
  a_3 :
  w_2 :
  Tpop();
  Rpush(b_3);
  goto p_35;
  b_3 :
  Cpop();
  goto q_2;
  r_2 :
  Rpush(c_3);
  goto r_35;
  c_3 :
  q_2 :
  Epopd(0,2);
  Return();
  x_35 :
  Epushd(0,2);
  Tdupl();
  BuildStr("match-arity5");
  Rpush(d_3);
  goto s_35;
  d_3 :
  Tpop();
  Cpush(f_3);
  Tdupl();
  Cpush(h_3);
  BuildFun("Skip",0);
  Tpush();
  BuildFun("Skip",0);
  Tpush();
  BuildFun("Skip",0);
  Tpush();
  BuildFun("If",3);
  Cpush(j_3);
  Epushd(1,2);
  MatchFun("If",2);
  Arg(0);
  MatchVard(1,1);
  Tpop();
  Arg(1);
  MatchVard(1,2);
  Tpop();
  BuildVard(1,1);
  Tpush();
  BuildVard(1,2);
  Tpush();
  BuildFun("Skip",0);
  Tpush();
  BuildFun("If",3);
  Epopd(1,2);
  Cpop();
  goto i_3;
  j_3 :
  Epushd(1,2);
  MatchFun("If",3);
  Arg(0);
  MatchVard(1,1);
  Tpop();
  Arg(1);
  MatchVard(1,2);
  Tpop();
  Arg(2);
  MatchFun("Skip",0);
  Tpop();
  BuildVard(1,1);
  Tpush();
  BuildVard(1,2);
  Tpush();
  BuildFun("If",2);
  Epopd(1,2);
  i_3 :
  MatchVard(0,1);
  Cpop();
  goto g_3;
  h_3 :
  BuildStr("  failed");
  Rpush(k_3);
  goto s_35;
  k_3 :
  Rpush(l_3);
  goto t_35;
  l_3 :
  g_3 :
  BuildFun("Skip",0);
  Tpush();
  BuildFun("Skip",0);
  Tpush();
  BuildFun("If",2);
  MatchVard(0,2);
  Cpush(n_3);
  BuildVard(0,2);
  MatchVard(0,1);
  Cpop();
  goto m_3;
  n_3 :
  BuildVard(0,1);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  result not equal: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(o_3);
  goto i_35;
  o_3 :
  Tpop();
  Epopd(1,0);
  BuildVard(0,2);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  expected: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(p_3);
  goto i_35;
  p_3 :
  Tpop();
  Epopd(1,0);
  Rpush(q_3);
  goto t_35;
  q_3 :
  m_3 :
  Tpop();
  Rpush(r_3);
  goto p_35;
  r_3 :
  Cpop();
  goto e_3;
  f_3 :
  Rpush(s_3);
  goto r_35;
  s_3 :
  e_3 :
  Epopd(0,2);
  Return();
  y_35 :
  Epushd(0,2);
  Tdupl();
  BuildStr("match-arity6");
  Rpush(t_3);
  goto s_35;
  t_3 :
  Tpop();
  Cpush(v_3);
  Tdupl();
  Cpush(x_3);
  BuildFun("Skip",0);
  Tpush();
  BuildFun("Skip",0);
  Tpush();
  BuildFun("If",2);
  Cpush(z_3);
  Epushd(1,2);
  MatchFun("If",2);
  Arg(0);
  MatchVard(1,1);
  Tpop();
  Arg(1);
  MatchVard(1,2);
  Tpop();
  BuildVard(1,1);
  Tpush();
  BuildVard(1,2);
  Tpush();
  BuildFun("Skip",0);
  Tpush();
  BuildFun("If",3);
  Epopd(1,2);
  Cpop();
  goto y_3;
  z_3 :
  Epushd(1,2);
  MatchFun("If",3);
  Arg(0);
  MatchVard(1,1);
  Tpop();
  Arg(1);
  MatchVard(1,2);
  Tpop();
  Arg(2);
  MatchFun("Skip",0);
  Tpop();
  BuildVard(1,1);
  Tpush();
  BuildVard(1,2);
  Tpush();
  BuildFun("If",2);
  Epopd(1,2);
  y_3 :
  MatchVard(0,1);
  Cpop();
  goto w_3;
  x_3 :
  BuildStr("  failed");
  Rpush(a_4);
  goto s_35;
  a_4 :
  Rpush(b_4);
  goto t_35;
  b_4 :
  w_3 :
  BuildFun("Skip",0);
  Tpush();
  BuildFun("Skip",0);
  Tpush();
  BuildFun("Skip",0);
  Tpush();
  BuildFun("If",3);
  MatchVard(0,2);
  Cpush(d_4);
  BuildVard(0,2);
  MatchVard(0,1);
  Cpop();
  goto c_4;
  d_4 :
  BuildVard(0,1);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  result not equal: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(e_4);
  goto i_35;
  e_4 :
  Tpop();
  Epopd(1,0);
  BuildVard(0,2);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  expected: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(f_4);
  goto i_35;
  f_4 :
  Tpop();
  Epopd(1,0);
  Rpush(g_4);
  goto t_35;
  g_4 :
  c_4 :
  Tpop();
  Rpush(h_4);
  goto p_35;
  h_4 :
  Cpop();
  goto u_3;
  v_3 :
  Rpush(i_4);
  goto r_35;
  i_4 :
  u_3 :
  Epopd(0,2);
  Return();
  j_4 :
DOIT_END
