#include <stratego.h>
#include <stratego-lib.h>
#include <stratego-ext.h>
DOIT_START
cur_rule_counter = 0;
  Rpush(b_24);
  goto main;
  main :
  Epushd(0,0);
  Epushd(1,0);
  MatchFun("Cons",2);
  TravInit();
  OneNextSon();
  Epushd(2,1);
  MatchVard(2,1);
  BuildVard(2,1);
  Tpush();
  BuildFun("Program",1);
  Epopd(2,1);
  OneNextSon();
  Rpush(w_2);
  h_0 :
  Cpush(y_2);
  Cpush(a_3);
  Rpush(b_3);
  goto p_11;
  b_3 :
  Cpop();
  goto z_2;
  a_3 :
  Rpush(f_3);
  goto q_11;
  f_3 :
  MatchFun("Cons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  Rpush(h_3);
  goto h_0;
  h_3 :
  AllBuild();
  z_2 :
  Cpop();
  goto x_2;
  y_2 :
  Epushd(2,2);
  MatchFun("Cons",2);
  Arg(0);
  MatchVard(2,1);
  Tpop();
  Arg(1);
  MatchVard(2,2);
  Tpop();
  BuildVard(2,1);
  Tpush();
  BuildFun("Undefined",1);
  Tpush();
  BuildVard(2,2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(2,2);
  x_2 :
  Return();
  w_2 :
  AllBuild();
  Epopd(1,0);
  Cpush(j_3);
  Rpush(k_3);
  goto r_11;
  k_3 :
  Cpop();
  goto i_3;
  j_3 :
  Cpush(m_3);
  Rpush(q_3);
  goto w_11;
  q_3 :
  Epushd(1,1);
  Tdupl();
  Rpush(r_3);
  goto y_11;
  r_3 :
  Tpop();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Rpush(s_3);
  goto f_12;
  s_3 :
  OneNextSon();
  Rpush(t_3);
  goto e_12;
  t_3 :
  AllBuild();
  AllBuild();
  Tdupl();
  Rpush(v_3);
  goto y_11;
  v_3 :
  MatchVard(1,1);
  Tpop();
  Epushd(2,2);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(2,1);
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(2,2);
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  BuildVard(1,1);
  Tpush();
  BuildFun("Runtime",1);
  Tpush();
  BuildVard(2,1);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildVard(2,2);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(2,2);
  Epopd(1,1);
  Rpush(w_3);
  goto z_11;
  w_3 :
  Rpush(x_3);
  goto c_12;
  x_3 :
  Cpop();
  goto l_3;
  m_3 :
  Rpush(d_4);
  goto d_12;
  d_4 :
  l_3 :
  i_3 :
  Epopd(0,0);
  Return();
  p_11 :
  MatchFun("Nil",0);
  Return();
  q_11 :
  Epushd(0,0);
  Cpush(f_4);
  Epushd(1,2);
  MatchFun("Cons",2);
  Arg(0);
  MatchVard(1,2);
  Tpop();
  Arg(1);
  MatchVard(1,1);
  Tpop();
  Tdupl();
  BuildVard(1,2);
  MatchString("-S");
  Tpop();
  Epushd(2,1);
  BuildFun("TNil",0);
  BuildFun("Silent",0);
  MatchVard(2,1);
  BuildVard(2,1);
  Tpush();
  BuildVard(1,1);
  Tpush();
  BuildFun("Cons",2);
  Epopd(2,1);
  Epopd(1,2);
  Cpop();
  goto e_4;
  f_4 :
  Cpush(h_4);
  Epushd(1,2);
  MatchFun("Cons",2);
  Arg(0);
  MatchVard(1,2);
  Tpop();
  Arg(1);
  MatchVard(1,1);
  Tpop();
  Tdupl();
  BuildVard(1,2);
  MatchString("--silent");
  Tpop();
  Epushd(2,1);
  BuildFun("TNil",0);
  BuildFun("Silent",0);
  MatchVard(2,1);
  BuildVard(2,1);
  Tpush();
  BuildVard(1,1);
  Tpush();
  BuildFun("Cons",2);
  Epopd(2,1);
  Epopd(1,2);
  Cpop();
  goto g_4;
  h_4 :
  Cpush(j_4);
  Epushd(1,2);
  MatchFun("Cons",2);
  Arg(0);
  MatchVard(1,2);
  Tpop();
  Arg(1);
  MatchVard(1,1);
  Tpop();
  Tdupl();
  BuildVard(1,2);
  MatchString("--verbose");
  Tpop();
  Epushd(2,1);
  BuildFun("TNil",0);
  BuildFun("Verbose",0);
  MatchVard(2,1);
  BuildVard(2,1);
  Tpush();
  BuildVard(1,1);
  Tpush();
  BuildFun("Cons",2);
  Epopd(2,1);
  Epopd(1,2);
  Cpop();
  goto i_4;
  j_4 :
  Cpush(l_4);
  Epushd(1,2);
  MatchFun("Cons",2);
  Arg(0);
  MatchVard(1,2);
  Tpop();
  Arg(1);
  MatchVard(1,1);
  Tpop();
  Tdupl();
  BuildVard(1,2);
  MatchString("-v");
  Tpop();
  Epushd(2,1);
  BuildFun("TNil",0);
  BuildFun("Version",0);
  MatchVard(2,1);
  BuildVard(2,1);
  Tpush();
  BuildVard(1,1);
  Tpush();
  BuildFun("Cons",2);
  Epopd(2,1);
  Epopd(1,2);
  Cpop();
  goto k_4;
  l_4 :
  Cpush(n_4);
  Epushd(1,2);
  MatchFun("Cons",2);
  Arg(0);
  MatchVard(1,2);
  Tpop();
  Arg(1);
  MatchVard(1,1);
  Tpop();
  Tdupl();
  BuildVard(1,2);
  MatchString("--version");
  Tpop();
  Epushd(2,1);
  BuildFun("TNil",0);
  BuildFun("Version",0);
  MatchVard(2,1);
  BuildVard(2,1);
  Tpush();
  BuildVard(1,1);
  Tpush();
  BuildFun("Cons",2);
  Epopd(2,1);
  Epopd(1,2);
  Cpop();
  goto m_4;
  n_4 :
  Cpush(p_4);
  Epushd(1,3);
  MatchFun("Cons",2);
  Arg(0);
  MatchVard(1,3);
  Tpop();
  Arg(1);
  MatchFun("Cons",2);
  Arg(0);
  MatchVard(1,1);
  Tpop();
  Arg(1);
  MatchVard(1,2);
  Tpop();
  Tpop();
  Tdupl();
  BuildVard(1,3);
  MatchString("@version");
  Tpop();
  Epushd(2,1);
  BuildVard(1,1);
  Epushd(3,1);
  MatchVard(3,1);
  BuildVard(3,1);
  Tpush();
  BuildFun("DeclVersion",1);
  Epopd(3,1);
  MatchVard(2,1);
  BuildVard(2,1);
  Tpush();
  BuildVard(1,2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(2,1);
  Epopd(1,3);
  Cpop();
  goto o_4;
  p_4 :
  Cpush(i_5);
  Epushd(1,3);
  MatchFun("Cons",2);
  Arg(0);
  MatchVard(1,3);
  Tpop();
  Arg(1);
  MatchFun("Cons",2);
  Arg(0);
  MatchVard(1,1);
  Tpop();
  Arg(1);
  MatchVard(1,2);
  Tpop();
  Tpop();
  Tdupl();
  BuildVard(1,3);
  MatchString("-i");
  Tpop();
  Epushd(2,1);
  BuildVard(1,1);
  Epushd(3,1);
  MatchVard(3,1);
  BuildVard(3,1);
  Tpush();
  BuildFun("Input",1);
  Epopd(3,1);
  MatchVard(2,1);
  BuildVard(2,1);
  Tpush();
  BuildVard(1,2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(2,1);
  Epopd(1,3);
  Cpop();
  goto h_5;
  i_5 :
  Cpush(k_5);
  Epushd(1,3);
  MatchFun("Cons",2);
  Arg(0);
  MatchVard(1,3);
  Tpop();
  Arg(1);
  MatchFun("Cons",2);
  Arg(0);
  MatchVard(1,1);
  Tpop();
  Arg(1);
  MatchVard(1,2);
  Tpop();
  Tpop();
  Tdupl();
  BuildVard(1,3);
  MatchString("--input");
  Tpop();
  Epushd(2,1);
  BuildVard(1,1);
  Epushd(3,1);
  MatchVard(3,1);
  BuildVard(3,1);
  Tpush();
  BuildFun("Input",1);
  Epopd(3,1);
  MatchVard(2,1);
  BuildVard(2,1);
  Tpush();
  BuildVard(1,2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(2,1);
  Epopd(1,3);
  Cpop();
  goto j_5;
  k_5 :
  Cpush(m_5);
  Epushd(1,3);
  MatchFun("Cons",2);
  Arg(0);
  MatchVard(1,3);
  Tpop();
  Arg(1);
  MatchFun("Cons",2);
  Arg(0);
  MatchVard(1,1);
  Tpop();
  Arg(1);
  MatchVard(1,2);
  Tpop();
  Tpop();
  Tdupl();
  BuildVard(1,3);
  MatchString("-o");
  Tpop();
  Epushd(2,1);
  BuildVard(1,1);
  Epushd(3,1);
  MatchVard(3,1);
  BuildVard(3,1);
  Tpush();
  BuildFun("Output",1);
  Epopd(3,1);
  MatchVard(2,1);
  BuildVard(2,1);
  Tpush();
  BuildVard(1,2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(2,1);
  Epopd(1,3);
  Cpop();
  goto l_5;
  m_5 :
  Cpush(o_5);
  Epushd(1,3);
  MatchFun("Cons",2);
  Arg(0);
  MatchVard(1,3);
  Tpop();
  Arg(1);
  MatchFun("Cons",2);
  Arg(0);
  MatchVard(1,1);
  Tpop();
  Arg(1);
  MatchVard(1,2);
  Tpop();
  Tpop();
  Tdupl();
  BuildVard(1,3);
  MatchString("--output");
  Tpop();
  Epushd(2,1);
  BuildVard(1,1);
  Epushd(3,1);
  MatchVard(3,1);
  BuildVard(3,1);
  Tpush();
  BuildFun("Output",1);
  Epopd(3,1);
  MatchVard(2,1);
  BuildVard(2,1);
  Tpush();
  BuildVard(1,2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(2,1);
  Epopd(1,3);
  Cpop();
  goto n_5;
  o_5 :
  Epushd(1,10);
  MatchFun("Cons",2);
  Arg(0);
  MatchVard(1,2);
  MatchVard(1,4);
  MatchVard(1,6);
  MatchVard(1,8);
  MatchVard(1,10);
  Tpop();
  Arg(1);
  MatchVard(1,1);
  MatchVard(1,3);
  MatchVard(1,5);
  MatchVard(1,7);
  MatchVard(1,9);
  Tpop();
  Cpush(v_5);
  Rpush(w_5);
  goto a_0;
  w_5 :
  Cpop();
  goto u_5;
  v_5 :
  Cpush(y_5);
  Rpush(z_5);
  goto b_0;
  z_5 :
  Cpop();
  goto x_5;
  y_5 :
  Cpush(b_6);
  Rpush(c_6);
  goto c_0;
  c_6 :
  Cpop();
  goto a_6;
  b_6 :
  Cpush(e_6);
  Rpush(f_6);
  goto d_0;
  f_6 :
  Cpop();
  goto d_6;
  e_6 :
  Rpush(g_6);
  goto u_2;
  g_6 :
  d_6 :
  a_6 :
  x_5 :
  u_5 :
  goto t_5;
  u_2 :
  Tdupl();
  BuildVard(1,10);
  MatchString("-?");
  Tpop();
  Epushd(2,1);
  BuildFun("TNil",0);
  BuildFun("Help",0);
  MatchVard(2,1);
  BuildVard(2,1);
  Tpush();
  BuildVard(1,9);
  Tpush();
  BuildFun("Cons",2);
  Epopd(2,1);
  Return();
  t_5 :
  goto s_5;
  d_0 :
  Tdupl();
  BuildVard(1,8);
  MatchString("-h");
  Tpop();
  Epushd(2,1);
  BuildFun("TNil",0);
  BuildFun("Help",0);
  MatchVard(2,1);
  BuildVard(2,1);
  Tpush();
  BuildVard(1,7);
  Tpush();
  BuildFun("Cons",2);
  Epopd(2,1);
  Return();
  s_5 :
  goto r_5;
  c_0 :
  Tdupl();
  BuildVard(1,6);
  MatchString("--help");
  Tpop();
  Epushd(2,1);
  BuildFun("TNil",0);
  BuildFun("Help",0);
  MatchVard(2,1);
  BuildVard(2,1);
  Tpush();
  BuildVard(1,5);
  Tpush();
  BuildFun("Cons",2);
  Epopd(2,1);
  Return();
  r_5 :
  goto q_5;
  b_0 :
  Tdupl();
  BuildVard(1,4);
  MatchString("-s");
  Tpop();
  Epushd(2,1);
  BuildFun("TNil",0);
  BuildFun("Statistics",0);
  MatchVard(2,1);
  BuildVard(2,1);
  Tpush();
  BuildVard(1,3);
  Tpush();
  BuildFun("Cons",2);
  Epopd(2,1);
  Return();
  q_5 :
  goto p_5;
  a_0 :
  Tdupl();
  BuildVard(1,2);
  MatchString("-b");
  Tpop();
  Epushd(2,1);
  BuildFun("TNil",0);
  BuildFun("Binary",0);
  MatchVard(2,1);
  BuildVard(2,1);
  Tpush();
  BuildVard(1,1);
  Tpush();
  BuildFun("Cons",2);
  Epopd(2,1);
  Return();
  p_5 :
  Epopd(1,10);
  n_5 :
  l_5 :
  j_5 :
  h_5 :
  o_4 :
  m_4 :
  k_4 :
  i_4 :
  g_4 :
  e_4 :
  Epopd(0,0);
  Return();
  r_11 :
  Epushd(0,0);
  Epushd(1,0);
  Tdupl();
  h_6 :
  MatchFun("Cons",2);
  Cpush(i_6);
  Arg(0);
  Cpush(l_6);
  Rpush(m_6);
  goto s_11;
  m_6 :
  Cpop();
  goto k_6;
  l_6 :
  MatchFun("Undefined",1);
  k_6 :
  Tpop();
  Cpop();
  goto j_6;
  i_6 :
  Arg(1);
  Tdrop();
  goto h_6;
  j_6 :
  Tpop();
  Epopd(1,0);
  Rpush(n_6);
  goto t_11;
  n_6 :
  Epopd(0,0);
  Return();
  s_11 :
  MatchFun("Help",0);
  Return();
  t_11 :
  Epushd(0,1);
  Tdupl();
  Epushd(1,0);
  Tdupl();
  o_6 :
  MatchFun("Cons",2);
  Cpush(p_6);
  Arg(0);
  MatchFun("Program",1);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Tpop();
  Cpop();
  goto q_6;
  p_6 :
  Arg(1);
  Tdrop();
  goto o_6;
  q_6 :
  Tpop();
  Epopd(1,0);
  BuildFun("stderr",0);
  Tpush();
  BuildStr("usage : ");
  Tpush();
  BuildVard(0,1);
  Tpush();
  BuildStr(" [-S] [-i file] [-o file] [-b] [-s] [--help|-h|-?]");
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(r_6);
  goto u_11;
  r_6 :
  BuildInt(1);
  Rpush(s_6);
  goto v_11;
  s_6 :
  Tpop();
  Epopd(0,1);
  Return();
  u_11 :
  Epushd(0,0);
  _ST_printnl();
  Epopd(0,0);
  Return();
  v_11 :
  Epushd(0,0);
  _ST_exit();
  Epopd(0,0);
  Return();
  w_11 :
  Epushd(0,1);
  Cpush(u_6);
  Epushd(1,0);
  Tdupl();
  v_6 :
  MatchFun("Cons",2);
  Cpush(w_6);
  Arg(0);
  MatchFun("Input",1);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Tpop();
  Cpop();
  goto x_6;
  w_6 :
  Arg(1);
  Tdrop();
  goto v_6;
  x_6 :
  Tpop();
  Epopd(1,0);
  Cpop();
  goto t_6;
  u_6 :
  BuildFun("stdin",0);
  MatchVard(0,1);
  t_6 :
  Epushd(1,1);
  MatchVard(1,1);
  Epushd(2,1);
  BuildVard(1,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(1,1);
  BuildVard(0,1);
  Rpush(y_6);
  goto x_11;
  y_6 :
  MatchVard(3,1);
  BuildVard(2,1);
  Tpush();
  BuildVard(3,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(3,1);
  Epopd(2,1);
  Epopd(1,1);
  Epopd(0,1);
  Return();
  x_11 :
  Epushd(0,0);
  _ST_ReadFromFile();
  Epopd(0,0);
  Return();
  y_11 :
  Epushd(0,0);
  _ST_dtime();
  Epopd(0,0);
  Return();
  z_11 :
  Epushd(0,1);
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Cpush(q_7);
  Epushd(1,0);
  Tdupl();
  t_7 :
  MatchFun("Cons",2);
  Cpush(u_7);
  Arg(0);
  MatchFun("Output",1);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Tpop();
  Cpop();
  goto b_8;
  u_7 :
  Arg(1);
  Tdrop();
  goto t_7;
  b_8 :
  Tpop();
  Epopd(1,0);
  Cpop();
  goto z_6;
  q_7 :
  BuildFun("stdout",0);
  MatchVard(0,1);
  z_6 :
  OneNextSon();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  Rpush(c_8);
  goto e_12;
  c_8 :
  AllBuild();
  AllBuild();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Epushd(1,1);
  MatchVard(1,1);
  Epushd(2,1);
  BuildVard(1,1);
  BuildVard(0,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(1,1);
  MatchVard(3,1);
  BuildVard(2,1);
  Tpush();
  BuildVard(3,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(3,1);
  Epopd(2,1);
  Epopd(1,1);
  OneNextSon();
  Rpush(d_8);
  goto e_12;
  d_8 :
  AllBuild();
  AllBuild();
  Cpush(g_8);
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Epushd(1,0);
  Tdupl();
  h_8 :
  MatchFun("Cons",2);
  Cpush(i_8);
  Arg(0);
  MatchFun("Binary",0);
  Tpop();
  Cpop();
  goto j_8;
  i_8 :
  Arg(1);
  Tdrop();
  goto h_8;
  j_8 :
  Tpop();
  Epopd(1,0);
  OneNextSon();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Rpush(k_8);
  goto a_12;
  k_8 :
  OneNextSon();
  Rpush(u_8);
  goto e_12;
  u_8 :
  AllBuild();
  AllBuild();
  Cpop();
  goto f_8;
  g_8 :
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Rpush(v_8);
  goto b_12;
  v_8 :
  OneNextSon();
  Rpush(r_9);
  goto e_12;
  r_9 :
  AllBuild();
  AllBuild();
  f_8 :
  Epopd(0,1);
  Return();
  a_12 :
  Epushd(0,0);
  _ST_WriteToBinaryFile();
  Epopd(0,0);
  Return();
  b_12 :
  Epushd(0,0);
  _ST_WriteToTextFile();
  Epopd(0,0);
  Return();
  c_12 :
  Epushd(0,2);
  Tdupl();
  Epushd(1,0);
  Cpush(u_9);
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Cpush(v_9);
  Tdupl();
  Epushd(2,0);
  Tdupl();
  j_10 :
  MatchFun("Cons",2);
  Cpush(k_10);
  Arg(0);
  MatchFun("Silent",0);
  Tpop();
  Cpop();
  goto l_10;
  k_10 :
  Arg(1);
  Tdrop();
  goto j_10;
  l_10 :
  Tpop();
  Epopd(2,0);
  Cpop();
  Crestore();
  Cjump();
  v_9 :
  OneNextSon();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  Rpush(m_10);
  goto e_12;
  m_10 :
  AllBuild();
  AllBuild();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Epushd(2,0);
  Tdupl();
  n_10 :
  MatchFun("Cons",2);
  Cpush(q_10);
  Arg(0);
  MatchFun("Runtime",1);
  Arg(0);
  MatchVard(0,2);
  Tpop();
  Tpop();
  Cpop();
  goto r_10;
  q_10 :
  Arg(1);
  Tdrop();
  goto n_10;
  r_10 :
  Tpop();
  Epopd(2,0);
  OneNextSon();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  Rpush(s_10);
  goto e_12;
  s_10 :
  AllBuild();
  AllBuild();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  Epushd(2,0);
  Tdupl();
  t_10 :
  MatchFun("Cons",2);
  Cpush(u_10);
  Arg(0);
  MatchFun("Program",1);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Tpop();
  Cpop();
  goto v_10;
  u_10 :
  Arg(1);
  Tdrop();
  goto t_10;
  v_10 :
  Tpop();
  Epopd(2,0);
  OneNextSon();
  MatchFun("TCons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  Rpush(w_10);
  goto e_12;
  w_10 :
  AllBuild();
  AllBuild();
  BuildFun("stderr",0);
  Tpush();
  BuildVard(0,1);
  Tpush();
  BuildStr(" (");
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildStr(" secs)");
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(x_10);
  goto u_11;
  x_10 :
  Cpop();
  goto t_9;
  u_9 :
  t_9 :
  Epopd(1,0);
  Tpop();
  BuildInt(0);
  Rpush(y_10);
  goto v_11;
  y_10 :
  Epopd(0,2);
  Return();
  d_12 :
  Epushd(0,0);
  BuildFun("stderr",0);
  Tpush();
  BuildStr("rewriting failed");
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(z_10);
  goto u_11;
  z_10 :
  BuildInt(1);
  Rpush(f_11);
  goto v_11;
  f_11 :
  Epopd(0,0);
  Return();
  e_12 :
  MatchFun("TNil",0);
  Return();
  f_12 :
  Epushd(0,0);
  Epushd(1,0);
  Rpush(g_11);
  u_3 :
  Cpush(i_11);
  Rpush(j_11);
  goto p_11;
  j_11 :
  Cpop();
  goto h_11;
  i_11 :
  MatchFun("Cons",2);
  TravInit();
  OneNextSon();
  Epushd(2,1);
  MatchVard(2,1);
  BuildVard(2,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildInt(0);
  Tpush();
  BuildFun("Instr",3);
  Rpush(k_11);
  z_3 :
  Epushd(3,0);
  Cpush(w_12);
  l_11 :
  Cpush(y_12);
  Rpush(z_12);
  goto g_12;
  z_12 :
  Cpop();
  goto x_12;
  y_12 :
  Rpush(a_13);
  goto m_12;
  a_13 :
  x_12 :
  Tduplinv();
  goto l_11;
  w_12 :
  Epopd(3,0);
  AllInit();
  b_13 :
  AllNextSon(&&c_13);
  Rpush(d_13);
  goto z_3;
  d_13 :
  goto b_13;
  c_13 :
  AllBuild();
  Return();
  k_11 :
  Epopd(2,1);
  OneNextSon();
  Rpush(e_13);
  goto u_3;
  e_13 :
  AllBuild();
  h_11 :
  Return();
  g_11 :
  Epopd(1,0);
  Rpush(f_13);
  goto t_12;
  f_13 :
  Rpush(g_13);
  goto u_12;
  g_13 :
  Epushd(1,2);
  MatchVard(1,1);
  Tdupl();
  Rpush(h_13);
  goto h_12;
  h_13 :
  MatchVard(1,2);
  Tpop();
  BuildVard(1,2);
  Tpush();
  BuildFun("Rpush",1);
  Tpush();
  BuildStr("main");
  Tpush();
  BuildFun("Goto",1);
  Tpush();
  BuildVard(1,1);
  Tpush();
  BuildFun("Block",1);
  Tpush();
  BuildVard(1,2);
  Tpush();
  BuildFun("Label",1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Block",1);
  Epopd(1,2);
  Epopd(0,0);
  Return();
  g_12 :
  Cpush(j_13);
  Epushd(0,6);
  MatchFun("Instr",3);
  TravInit();
  OneNextSon();
  Cpush(l_13);
  Epushd(1,1);
  MatchFun("Rec",2);
  TravInit();
  OneNextSon();
  MatchVard(1,1);
  OneNextSon();
  MatchFun("LChoice",2);
  TravInit();
  OneNextSon();
  Epushd(2,0);
  Cpush(n_13);
  m_13 :
  Epushd(3,3);
  MatchFun("Seq",2);
  Arg(0);
  MatchVard(3,1);
  Tpop();
  Arg(1);
  MatchFun("Seq",2);
  Arg(0);
  MatchVard(3,2);
  Tpop();
  Arg(1);
  MatchVard(3,3);
  Tpop();
  Tpop();
  BuildVard(3,1);
  Tpush();
  BuildVard(3,2);
  Tpush();
  BuildFun("Seq",2);
  Tpush();
  BuildVard(3,3);
  Tpush();
  BuildFun("Seq",2);
  Epopd(3,3);
  Tduplinv();
  goto m_13;
  n_13 :
  Epopd(2,0);
  MatchFun("Seq",2);
  TravInit();
  OneNextSon();
  Cpush(o_13);
  Tdupl();
  Epushd(2,0);
  Rpush(u_13);
  p_13 :
  Cpush(q_13);
  MatchFun("SVar",1);
  TravInit();
  OneNextSon();
  MatchVard(1,1);
  AllBuild();
  Cpop();
  goto t_13;
  q_13 :
  IsAppl();
  MatchTravInit();
  r_13 :
  OneMatchNextSon();
  Cpush(r_13);
  Rpush(s_13);
  goto p_13;
  s_13 :
  Cpop();
  MatchTravEnd();
  t_13 :
  Return();
  u_13 :
  Epopd(2,0);
  Cpop();
  Crestore();
  Cjump();
  o_13 :
  MatchVard(0,1);
  OneNextSon();
  MatchFun("Call",2);
  TravInit();
  OneNextSon();
  MatchFun("SVar",1);
  TravInit();
  OneNextSon();
  MatchVard(1,1);
  AllBuild();
  OneNextSon();
  Rpush(v_13);
  goto p_11;
  v_13 :
  AllBuild();
  AllBuild();
  OneNextSon();
  Cpush(w_13);
  Tdupl();
  Epushd(2,0);
  Rpush(c_14);
  x_13 :
  Cpush(y_13);
  MatchFun("SVar",1);
  TravInit();
  OneNextSon();
  MatchVard(1,1);
  AllBuild();
  Cpop();
  goto b_14;
  y_13 :
  IsAppl();
  MatchTravInit();
  z_13 :
  OneMatchNextSon();
  Cpush(z_13);
  Rpush(a_14);
  goto x_13;
  a_14 :
  Cpop();
  MatchTravEnd();
  b_14 :
  Return();
  c_14 :
  Epopd(2,0);
  Cpop();
  Crestore();
  Cjump();
  w_13 :
  MatchVard(0,2);
  AllBuild();
  AllBuild();
  Epopd(1,1);
  Cpop();
  goto k_13;
  l_13 :
  Epushd(1,3);
  MatchFun("Rec",2);
  TravInit();
  OneNextSon();
  MatchVard(1,1);
  OneNextSon();
  MatchFun("LChoice",2);
  TravInit();
  OneNextSon();
  Epushd(2,0);
  Cpush(e_14);
  d_14 :
  Epushd(3,3);
  MatchFun("Seq",2);
  Arg(0);
  MatchVard(3,1);
  Tpop();
  Arg(1);
  MatchFun("Seq",2);
  Arg(0);
  MatchVard(3,2);
  Tpop();
  Arg(1);
  MatchVard(3,3);
  Tpop();
  Tpop();
  BuildVard(3,1);
  Tpush();
  BuildVard(3,2);
  Tpush();
  BuildFun("Seq",2);
  Tpush();
  BuildVard(3,3);
  Tpush();
  BuildFun("Seq",2);
  Epopd(3,3);
  Tduplinv();
  goto d_14;
  e_14 :
  Epopd(2,0);
  MatchFun("Seq",2);
  Arg(0);
  MatchVard(1,2);
  Tpop();
  Arg(1);
  MatchFun("Seq",2);
  Arg(0);
  MatchFun("Call",2);
  Arg(0);
  MatchFun("SVar",1);
  Arg(0);
  MatchVard(1,1);
  Tpop();
  Tpop();
  Arg(1);
  MatchFun("Nil",0);
  Tpop();
  Tpop();
  Arg(1);
  MatchFun("Countrule",1);
  Arg(0);
  MatchVard(1,3);
  Tpop();
  Tpop();
  Tpop();
  BuildVard(1,2);
  Tpush();
  BuildVard(1,3);
  Tpush();
  BuildFun("CountRule",1);
  Tpush();
  BuildFun("Seq",2);
  Tpush();
  BuildVard(1,1);
  Tpush();
  BuildFun("SVar",1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Call",2);
  Tpush();
  BuildFun("Seq",2);
  MatchFun("Seq",2);
  TravInit();
  OneNextSon();
  Cpush(f_14);
  Tdupl();
  Epushd(2,0);
  Rpush(l_14);
  g_14 :
  Cpush(h_14);
  MatchFun("SVar",1);
  TravInit();
  OneNextSon();
  MatchVard(1,1);
  AllBuild();
  Cpop();
  goto k_14;
  h_14 :
  IsAppl();
  MatchTravInit();
  i_14 :
  OneMatchNextSon();
  Cpush(i_14);
  Rpush(j_14);
  goto g_14;
  j_14 :
  Cpop();
  MatchTravEnd();
  k_14 :
  Return();
  l_14 :
  Epopd(2,0);
  Cpop();
  Crestore();
  Cjump();
  f_14 :
  MatchVard(0,1);
  OneNextSon();
  AllBuild();
  OneNextSon();
  Cpush(m_14);
  Tdupl();
  Epushd(2,0);
  Rpush(s_14);
  n_14 :
  Cpush(o_14);
  MatchFun("SVar",1);
  TravInit();
  OneNextSon();
  MatchVard(1,1);
  AllBuild();
  Cpop();
  goto r_14;
  o_14 :
  IsAppl();
  MatchTravInit();
  p_14 :
  OneMatchNextSon();
  Cpush(p_14);
  Rpush(q_14);
  goto n_14;
  q_14 :
  Cpop();
  MatchTravEnd();
  r_14 :
  Return();
  s_14 :
  Epopd(2,0);
  Cpop();
  Crestore();
  Cjump();
  m_14 :
  MatchVard(0,2);
  AllBuild();
  AllBuild();
  Epopd(1,3);
  k_13 :
  OneNextSon();
  MatchVard(0,3);
  OneNextSon();
  MatchVard(0,4);
  AllBuild();
  Tdupl();
  Rpush(t_14);
  goto h_12;
  t_14 :
  MatchVard(0,5);
  Rpush(u_14);
  goto h_12;
  u_14 :
  MatchVard(0,6);
  Tpop();
  BuildVard(0,6);
  Tpush();
  BuildFun("Cpush",1);
  Tpush();
  BuildVard(0,5);
  Tpush();
  BuildFun("Label",1);
  Tpush();
  BuildVard(0,1);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildFun("Tduplinv",0);
  Tpush();
  BuildVard(0,5);
  Tpush();
  BuildFun("Goto",1);
  Tpush();
  BuildVard(0,6);
  Tpush();
  BuildFun("Label",1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Block",1);
  Epopd(0,6);
  Cpop();
  goto i_13;
  j_13 :
  Cpush(w_14);
  Epushd(0,0);
  Rpush(x_14);
  goto i_12;
  x_14 :
  Epopd(0,0);
  Cpop();
  goto v_14;
  w_14 :
  Epushd(0,0);
  Rpush(y_14);
  goto k_12;
  y_14 :
  Epopd(0,0);
  v_14 :
  i_13 :
  Return();
  h_12 :
  Epushd(0,0);
  _ST_new();
  Epopd(0,0);
  Return();
  i_12 :
  Epushd(0,9);
  MatchFun("Instr",3);
  TravInit();
  OneNextSon();
  Epushd(1,1);
  MatchFun("Rec",2);
  TravInit();
  OneNextSon();
  MatchVard(1,1);
  OneNextSon();
  MatchFun("LChoice",2);
  TravInit();
  OneNextSon();
  MatchVard(0,1);
  Rpush(z_14);
  goto j_12;
  z_14 :
  OneNextSon();
  MatchFun("One",1);
  TravInit();
  OneNextSon();
  MatchFun("Call",2);
  TravInit();
  OneNextSon();
  MatchFun("SVar",1);
  TravInit();
  OneNextSon();
  MatchVard(1,1);
  AllBuild();
  OneNextSon();
  Rpush(a_15);
  goto p_11;
  a_15 :
  AllBuild();
  AllBuild();
  AllBuild();
  AllBuild();
  Epopd(1,1);
  OneNextSon();
  MatchVard(0,2);
  OneNextSon();
  MatchVard(0,3);
  AllBuild();
  Tdupl();
  Rpush(b_15);
  goto h_12;
  b_15 :
  MatchVard(0,4);
  Rpush(c_15);
  goto h_12;
  c_15 :
  MatchVard(0,5);
  Rpush(d_15);
  goto h_12;
  d_15 :
  MatchVard(0,6);
  Rpush(e_15);
  goto h_12;
  e_15 :
  MatchVard(0,7);
  Rpush(f_15);
  goto h_12;
  f_15 :
  MatchVard(0,8);
  Rpush(g_15);
  goto h_12;
  g_15 :
  MatchVard(0,9);
  Tpop();
  BuildVard(0,9);
  Tpush();
  BuildFun("Rpush",1);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Label",1);
  Tpush();
  BuildVard(0,5);
  Tpush();
  BuildFun("Cpush",1);
  Tpush();
  BuildVard(0,1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildFun("Cpop",0);
  Tpush();
  BuildVard(0,8);
  Tpush();
  BuildFun("Goto",1);
  Tpush();
  BuildVard(0,5);
  Tpush();
  BuildFun("Label",1);
  Tpush();
  BuildFun("IsAppl",0);
  Tpush();
  BuildFun("MatchTravInit",0);
  Tpush();
  BuildVard(0,6);
  Tpush();
  BuildFun("Label",1);
  Tpush();
  BuildFun("OneMatchNextSon",0);
  Tpush();
  BuildVard(0,6);
  Tpush();
  BuildFun("Cpush",1);
  Tpush();
  BuildVard(0,7);
  Tpush();
  BuildFun("Rpush",1);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Goto",1);
  Tpush();
  BuildVard(0,7);
  Tpush();
  BuildFun("Label",1);
  Tpush();
  BuildFun("Cpop",0);
  Tpush();
  BuildFun("MatchTravEnd",0);
  Tpush();
  BuildVard(0,8);
  Tpush();
  BuildFun("Label",1);
  Tpush();
  BuildFun("Return",0);
  Tpush();
  BuildVard(0,9);
  Tpush();
  BuildFun("Label",1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Block",1);
  Epopd(0,9);
  Return();
  j_12 :
  Epushd(0,0);
  Cpush(h_15);
  Tdupl();
  Epushd(1,0);
  Rpush(n_15);
  i_15 :
  Cpush(j_15);
  MatchFun("Build",1);
  Cpop();
  goto m_15;
  j_15 :
  IsAppl();
  MatchTravInit();
  k_15 :
  OneMatchNextSon();
  Cpush(k_15);
  Rpush(l_15);
  goto i_15;
  l_15 :
  Cpop();
  MatchTravEnd();
  m_15 :
  Return();
  n_15 :
  Epopd(1,0);
  Cpop();
  Crestore();
  Cjump();
  h_15 :
  Epopd(0,0);
  Return();
  k_12 :
  Epushd(0,6);
  MatchFun("Instr",3);
  TravInit();
  OneNextSon();
  Cpush(p_15);
  Epushd(1,1);
  MatchFun("Rec",2);
  TravInit();
  OneNextSon();
  MatchVard(1,1);
  OneNextSon();
  MatchFun("LChoice",2);
  TravInit();
  OneNextSon();
  MatchFun("Cong",2);
  TravInit();
  OneNextSon();
  MatchString("Cons");
  OneNextSon();
  MatchFun("Cons",2);
  TravInit();
  OneNextSon();
  MatchVard(0,1);
  Rpush(q_15);
  goto j_12;
  q_15 :
  OneNextSon();
  MatchFun("Cons",2);
  TravInit();
  OneNextSon();
  Rpush(r_15);
  goto l_12;
  r_15 :
  OneNextSon();
  Rpush(s_15);
  goto p_11;
  s_15 :
  AllBuild();
  AllBuild();
  AllBuild();
  OneNextSon();
  MatchFun("Cong",2);
  TravInit();
  OneNextSon();
  MatchString("Cons");
  OneNextSon();
  MatchFun("Cons",2);
  TravInit();
  OneNextSon();
  Rpush(t_15);
  goto l_12;
  t_15 :
  OneNextSon();
  MatchFun("Cons",2);
  TravInit();
  OneNextSon();
  MatchFun("Call",2);
  TravInit();
  OneNextSon();
  MatchFun("SVar",1);
  TravInit();
  OneNextSon();
  MatchVard(1,1);
  AllBuild();
  OneNextSon();
  Rpush(u_15);
  goto p_11;
  u_15 :
  AllBuild();
  OneNextSon();
  Rpush(v_15);
  goto p_11;
  v_15 :
  AllBuild();
  AllBuild();
  AllBuild();
  AllBuild();
  AllBuild();
  Epopd(1,1);
  Cpop();
  goto o_15;
  p_15 :
  Epushd(1,1);
  MatchFun("Rec",2);
  TravInit();
  OneNextSon();
  MatchVard(1,1);
  OneNextSon();
  MatchFun("LChoice",2);
  TravInit();
  OneNextSon();
  MatchFun("Seq",2);
  TravInit();
  OneNextSon();
  MatchFun("Cong",2);
  TravInit();
  OneNextSon();
  MatchString("Cons");
  OneNextSon();
  MatchFun("Cons",2);
  TravInit();
  OneNextSon();
  MatchVard(0,1);
  Rpush(w_15);
  goto j_12;
  w_15 :
  OneNextSon();
  MatchFun("Cons",2);
  TravInit();
  OneNextSon();
  Rpush(x_15);
  goto l_12;
  x_15 :
  OneNextSon();
  Rpush(y_15);
  goto p_11;
  y_15 :
  AllBuild();
  AllBuild();
  AllBuild();
  OneNextSon();
  MatchFun("CountRule",1);
  TravInit();
  OneNextSon();
  MatchString("Cons");
  AllBuild();
  AllBuild();
  OneNextSon();
  MatchFun("Seq",2);
  TravInit();
  OneNextSon();
  MatchFun("Cong",2);
  TravInit();
  OneNextSon();
  MatchString("Cons");
  OneNextSon();
  MatchFun("Cons",2);
  TravInit();
  OneNextSon();
  Rpush(z_15);
  goto l_12;
  z_15 :
  OneNextSon();
  MatchFun("Cons",2);
  TravInit();
  OneNextSon();
  MatchFun("Call",2);
  TravInit();
  OneNextSon();
  MatchFun("SVar",1);
  TravInit();
  OneNextSon();
  MatchVard(1,1);
  AllBuild();
  OneNextSon();
  Rpush(a_16);
  goto p_11;
  a_16 :
  AllBuild();
  OneNextSon();
  Rpush(b_16);
  goto p_11;
  b_16 :
  AllBuild();
  AllBuild();
  AllBuild();
  OneNextSon();
  MatchFun("CountRule",1);
  TravInit();
  OneNextSon();
  MatchString("Cons");
  AllBuild();
  AllBuild();
  AllBuild();
  AllBuild();
  Epopd(1,1);
  o_15 :
  OneNextSon();
  MatchVard(0,2);
  OneNextSon();
  MatchVard(0,3);
  AllBuild();
  Tdupl();
  Rpush(c_16);
  goto h_12;
  c_16 :
  MatchVard(0,4);
  Rpush(d_16);
  goto h_12;
  d_16 :
  MatchVard(0,5);
  Rpush(e_16);
  goto h_12;
  e_16 :
  MatchVard(0,6);
  Tpop();
  BuildFun("Tdupl",0);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Label",1);
  Tpush();
  BuildStr("Cons");
  Tpush();
  BuildInt(2);
  Tpush();
  BuildFun("MatchFun",2);
  Tpush();
  BuildVard(0,5);
  Tpush();
  BuildFun("Cpush",1);
  Tpush();
  BuildInt(0);
  Tpush();
  BuildFun("Arg",1);
  Tpush();
  BuildVard(0,1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildFun("Tpop",0);
  Tpush();
  BuildFun("Cpop",0);
  Tpush();
  BuildVard(0,6);
  Tpush();
  BuildFun("Goto",1);
  Tpush();
  BuildVard(0,5);
  Tpush();
  BuildFun("Label",1);
  Tpush();
  BuildInt(1);
  Tpush();
  BuildFun("Arg",1);
  Tpush();
  BuildFun("Tdrop",0);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Goto",1);
  Tpush();
  BuildVard(0,6);
  Tpush();
  BuildFun("Label",1);
  Tpush();
  BuildFun("Tpop",0);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Block",1);
  Epopd(0,6);
  Return();
  l_12 :
  MatchFun("Id",0);
  Return();
  m_12 :
  Cpush(g_16);
  Epushd(0,2);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("Id",0);
  Tpop();
  Arg(1);
  MatchVard(0,1);
  Tpop();
  Arg(2);
  MatchVard(0,2);
  Tpop();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Block",1);
  Epopd(0,2);
  Cpop();
  goto f_16;
  g_16 :
  Cpush(i_16);
  Epushd(0,2);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("Fail",0);
  Tpop();
  Arg(1);
  MatchVard(0,1);
  Tpop();
  Arg(2);
  MatchVard(0,2);
  Tpop();
  BuildStr("fail");
  Tpush();
  BuildFun("Goto",1);
  Epopd(0,2);
  Cpop();
  goto h_16;
  i_16 :
  Cpush(k_16);
  Epushd(0,3);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("Test",1);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,2);
  Tpop();
  Arg(2);
  MatchVard(0,3);
  Tpop();
  BuildFun("Tdupl",0);
  Tpush();
  BuildVard(0,1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildFun("Tpop",0);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Block",1);
  Epopd(0,3);
  Cpop();
  goto j_16;
  k_16 :
  Cpush(m_16);
  Epushd(0,4);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("Not",1);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,2);
  Tpop();
  Arg(2);
  MatchVard(0,3);
  Tpop();
  Tdupl();
  Rpush(n_16);
  goto h_12;
  n_16 :
  MatchVard(0,4);
  Tpop();
  BuildVard(0,4);
  Tpush();
  BuildFun("Cpush",1);
  Tpush();
  BuildFun("Tdupl",0);
  Tpush();
  BuildVard(0,1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildFun("Cpop",0);
  Tpush();
  BuildFun("Crestore",0);
  Tpush();
  BuildFun("Cjump",0);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Label",1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Block",1);
  Epopd(0,4);
  Cpop();
  goto l_16;
  m_16 :
  Cpush(p_16);
  Epushd(0,4);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("Seq",2);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Arg(1);
  MatchVard(0,2);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,3);
  Tpop();
  Arg(2);
  MatchVard(0,4);
  Tpop();
  BuildVard(0,1);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Block",1);
  Epopd(0,4);
  Cpop();
  goto o_16;
  p_16 :
  Cpush(r_16);
  Epushd(0,6);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("LChoice",2);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Arg(1);
  MatchVard(0,2);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,3);
  Tpop();
  Arg(2);
  MatchVard(0,4);
  Tpop();
  Tdupl();
  Rpush(s_16);
  goto h_12;
  s_16 :
  MatchVard(0,5);
  Rpush(t_16);
  goto h_12;
  t_16 :
  MatchVard(0,6);
  Tpop();
  BuildVard(0,6);
  Tpush();
  BuildFun("Cpush",1);
  Tpush();
  BuildVard(0,1);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildFun("Cpop",0);
  Tpush();
  BuildVard(0,5);
  Tpush();
  BuildFun("Goto",1);
  Tpush();
  BuildVard(0,6);
  Tpush();
  BuildFun("Label",1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildVard(0,5);
  Tpush();
  BuildFun("Label",1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Block",1);
  Epopd(0,6);
  Cpop();
  goto q_16;
  r_16 :
  Cpush(v_16);
  Epushd(0,6);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("Choice",2);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Arg(1);
  MatchVard(0,2);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,3);
  Tpop();
  Arg(2);
  MatchVard(0,4);
  Tpop();
  Tdupl();
  Rpush(w_16);
  goto h_12;
  w_16 :
  MatchVard(0,5);
  Rpush(x_16);
  goto h_12;
  x_16 :
  MatchVard(0,6);
  Tpop();
  BuildVard(0,6);
  Tpush();
  BuildFun("Cpush",1);
  Tpush();
  BuildVard(0,1);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildFun("Cpop",0);
  Tpush();
  BuildVard(0,5);
  Tpush();
  BuildFun("Goto",1);
  Tpush();
  BuildVard(0,6);
  Tpush();
  BuildFun("Label",1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildVard(0,5);
  Tpush();
  BuildFun("Label",1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Block",1);
  Epopd(0,6);
  Cpop();
  goto u_16;
  v_16 :
  Cpush(z_16);
  Epushd(0,4);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("Down",2);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Arg(1);
  MatchVard(0,2);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,3);
  Tpop();
  Arg(2);
  MatchVard(0,4);
  Tpop();
  BuildVard(0,1);
  Tpush();
  BuildFun("Arg",1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Block",1);
  Epopd(0,4);
  Cpop();
  goto y_16;
  z_16 :
  Cpush(b_17);
  Epushd(0,3);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("Up",1);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,2);
  Tpop();
  Arg(2);
  MatchVard(0,3);
  Tpop();
  BuildFun("Tpop",0);
  Tpush();
  BuildVard(0,1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Block",1);
  Epopd(0,3);
  Cpop();
  goto a_17;
  b_17 :
  Cpush(d_17);
  Epushd(0,3);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("Accept",1);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,2);
  Tpop();
  Arg(2);
  MatchVard(0,3);
  Tpop();
  BuildVard(0,1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildFun("Instr",3);
  Epopd(0,3);
  Cpop();
  goto c_17;
  d_17 :
  Cpush(f_17);
  Epushd(0,4);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("MatchVars",3);
  Arg(0);
  MatchFun("Nil",0);
  Tpop();
  Arg(1);
  MatchVard(0,1);
  Tpop();
  Arg(2);
  MatchVard(0,2);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,3);
  Tpop();
  Arg(2);
  MatchVard(0,4);
  Tpop();
  BuildVard(0,2);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Instr",3);
  Epopd(0,4);
  Cpop();
  goto e_17;
  f_17 :
  Cpush(h_17);
  Epushd(0,9);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("MatchVars",3);
  Arg(0);
  MatchFun("Cons",2);
  Arg(0);
  MatchVard(0,4);
  Tpop();
  Arg(1);
  MatchVard(0,1);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,2);
  Tpop();
  Arg(2);
  MatchVard(0,3);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,5);
  Tpop();
  Arg(2);
  MatchVard(0,6);
  Tpop();
  Tdupl();
  BuildVard(0,4);
  Tpush();
  BuildVard(0,5);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epushd(1,4);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(1,1);
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(1,4);
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  Tdupl();
  BuildVard(1,4);
  Epushd(2,0);
  Rpush(i_17);
  e_8 :
  Cpush(k_17);
  MatchFun("Cons",2);
  TravInit();
  OneNextSon();
  Epushd(3,2);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(3,1);
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(3,2);
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  Epushd(4,1);
  BuildVard(1,1);
  Tpush();
  BuildVard(3,2);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(l_17);
  goto p_12;
  l_17 :
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,2);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(1,2);
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(1,3);
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  OneNextSon();
  AllBuild();
  Cpop();
  goto j_17;
  k_17 :
  MatchFun("Cons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  Rpush(m_17);
  goto e_8;
  m_17 :
  AllBuild();
  j_17 :
  Return();
  i_17 :
  Epopd(2,0);
  Tpop();
  BuildVard(1,2);
  Tpush();
  BuildVard(1,3);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(1,4);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(0,7);
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(0,8);
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  Cpush(o_17);
  BuildVard(0,7);
  Tpush();
  BuildVard(0,6);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(p_17);
  goto r_12;
  p_17 :
  BuildVard(0,8);
  Tpush();
  BuildFun("MatchVar",1);
  Cpop();
  goto n_17;
  o_17 :
  BuildVard(0,7);
  Tpush();
  BuildVard(0,8);
  Tpush();
  BuildFun("MatchVard",2);
  MatchVard(0,9);
  n_17 :
  Tpop();
  BuildVard(0,9);
  Tpush();
  BuildVard(0,1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildFun("MatchVars",3);
  Tpush();
  BuildVard(0,5);
  Tpush();
  BuildVard(0,6);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Block",1);
  Epopd(0,9);
  Cpop();
  goto g_17;
  h_17 :
  Cpush(r_17);
  Epushd(0,7);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("MatchFunA",4);
  Arg(0);
  MatchFun("Fun",2);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Arg(1);
  MatchVard(0,2);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,3);
  Tpop();
  Arg(2);
  MatchVard(0,4);
  Tpop();
  Arg(3);
  MatchVard(0,5);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,6);
  Tpop();
  Arg(2);
  MatchVard(0,7);
  Tpop();
  BuildVard(0,1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildFun("MatchFun",2);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildVard(0,5);
  Tpush();
  BuildFun("MatchVars",3);
  Tpush();
  BuildVard(0,6);
  Tpush();
  BuildVard(0,7);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Block",1);
  Epopd(0,7);
  Cpop();
  goto q_17;
  r_17 :
  Cpush(t_17);
  Epushd(0,6);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("MatchFunA",4);
  Arg(0);
  MatchFun("Str",1);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,2);
  Tpop();
  Arg(2);
  MatchVard(0,3);
  Tpop();
  Arg(3);
  MatchVard(0,4);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,5);
  Tpop();
  Arg(2);
  MatchVard(0,6);
  Tpop();
  BuildVard(0,1);
  Tpush();
  BuildFun("MatchString",1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("MatchVars",3);
  Tpush();
  BuildVard(0,5);
  Tpush();
  BuildVard(0,6);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Block",1);
  Epopd(0,6);
  Cpop();
  goto s_17;
  t_17 :
  Cpush(v_17);
  Epushd(0,6);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("MatchFunA",4);
  Arg(0);
  MatchFun("Int",1);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,2);
  Tpop();
  Arg(2);
  MatchVard(0,3);
  Tpop();
  Arg(3);
  MatchVard(0,4);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,5);
  Tpop();
  Arg(2);
  MatchVard(0,6);
  Tpop();
  BuildVard(0,1);
  Tpush();
  BuildFun("MatchInt",1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("MatchVars",3);
  Tpush();
  BuildVard(0,5);
  Tpush();
  BuildVard(0,6);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Block",1);
  Epopd(0,6);
  Cpop();
  goto u_17;
  v_17 :
  Cpush(x_17);
  Epushd(0,6);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("MatchFunA",4);
  Arg(0);
  MatchFun("Real",1);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,2);
  Tpop();
  Arg(2);
  MatchVard(0,3);
  Tpop();
  Arg(3);
  MatchVard(0,4);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,5);
  Tpop();
  Arg(2);
  MatchVard(0,6);
  Tpop();
  BuildVard(0,1);
  Tpush();
  BuildFun("MatchReal",1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("MatchVars",3);
  Tpush();
  BuildVard(0,5);
  Tpush();
  BuildVard(0,6);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Block",1);
  Epopd(0,6);
  Cpop();
  goto w_17;
  x_17 :
  Cpush(z_17);
  Epushd(0,6);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("Case",1);
  Arg(0);
  MatchVard(0,5);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,1);
  Tpop();
  Arg(2);
  MatchVard(0,2);
  Tpop();
  Tdupl();
  Rpush(a_18);
  goto h_12;
  a_18 :
  MatchVard(0,3);
  Cpush(c_18);
  BuildVard(0,5);
  Epushd(1,0);
  Rpush(d_18);
  o_8 :
  Cpush(f_18);
  Epushd(2,1);
  MatchFun("Cons",2);
  TravInit();
  OneNextSon();
  MatchFun("MatchVars",3);
  MatchVard(0,4);
  OneNextSon();
  MatchVard(2,1);
  AllBuild();
  BuildVard(2,1);
  Epopd(2,1);
  Cpop();
  goto e_18;
  f_18 :
  MatchFun("Cons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  Rpush(g_18);
  goto o_8;
  g_18 :
  AllBuild();
  e_18 :
  Return();
  d_18 :
  Epopd(1,0);
  Cpop();
  goto b_18;
  c_18 :
  BuildFun("Fail",0);
  MatchVard(0,4);
  BuildVard(0,5);
  b_18 :
  MatchVard(0,6);
  Tpop();
  BuildVard(0,6);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildFun("Cases",2);
  Tpush();
  BuildVard(0,1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildVard(0,1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildFun("Label",1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Block",1);
  Epopd(0,6);
  Cpop();
  goto y_17;
  z_17 :
  Cpush(i_18);
  Epushd(0,3);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("Cases",2);
  Arg(0);
  MatchFun("Nil",0);
  Tpop();
  Arg(1);
  MatchVard(0,1);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,2);
  Tpop();
  Arg(2);
  MatchVard(0,3);
  Tpop();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Block",1);
  Epopd(0,3);
  Cpop();
  goto h_18;
  i_18 :
  Cpush(k_18);
  Epushd(0,9);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("Cases",2);
  Arg(0);
  MatchFun("Cons",2);
  Arg(0);
  MatchFun("MatchFunA",4);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Arg(1);
  MatchVard(0,2);
  Tpop();
  Arg(2);
  MatchVard(0,3);
  Tpop();
  Arg(3);
  MatchVard(0,4);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,5);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,6);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,7);
  Tpop();
  Arg(2);
  MatchVard(0,8);
  Tpop();
  Tdupl();
  Rpush(l_18);
  goto h_12;
  l_18 :
  MatchVard(0,9);
  Tpop();
  Epushd(1,1);
  BuildVard(0,1);
  Tpush();
  BuildVard(0,9);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(m_18);
  goto n_12;
  m_18 :
  MatchVard(1,1);
  BuildVard(1,1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("MatchVars",3);
  Tpush();
  BuildVard(0,7);
  Tpush();
  BuildVard(0,8);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildVard(0,6);
  Tpush();
  BuildFun("Goto",1);
  Tpush();
  BuildVard(0,9);
  Tpush();
  BuildFun("Label",1);
  Tpush();
  BuildVard(0,5);
  Tpush();
  BuildVard(0,6);
  Tpush();
  BuildFun("Cases",2);
  Tpush();
  BuildVard(0,7);
  Tpush();
  BuildVard(0,8);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Block",1);
  Epopd(1,1);
  Epopd(0,9);
  Cpop();
  goto j_18;
  k_18 :
  Cpush(o_18);
  Epushd(0,5);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("Rec",2);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Arg(1);
  MatchVard(0,2);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,3);
  Tpop();
  Arg(2);
  MatchVard(0,4);
  Tpop();
  Tdupl();
  Rpush(p_18);
  goto h_12;
  p_18 :
  MatchVard(0,5);
  Tpop();
  BuildVard(0,5);
  Tpush();
  BuildFun("Rpush",1);
  Tpush();
  BuildVard(0,1);
  Tpush();
  BuildFun("Label",1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildFun("Return",0);
  Tpush();
  BuildVard(0,5);
  Tpush();
  BuildFun("Label",1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Block",1);
  Epopd(0,5);
  Cpop();
  goto n_18;
  o_18 :
  Cpush(r_18);
  Epushd(0,4);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("Call",2);
  Arg(0);
  MatchFun("SVar",1);
  Arg(0);
  MatchVard(0,3);
  Tpop();
  Tpop();
  Arg(1);
  MatchFun("Nil",0);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,1);
  Tpop();
  Arg(2);
  MatchVard(0,2);
  Tpop();
  Tdupl();
  Rpush(s_18);
  goto h_12;
  s_18 :
  MatchVard(0,4);
  Tpop();
  BuildVard(0,4);
  Tpush();
  BuildFun("Rpush",1);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildFun("Goto",1);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Label",1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Block",1);
  Epopd(0,4);
  Cpop();
  goto q_18;
  r_18 :
  Cpush(u_18);
  Epushd(0,5);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("Let",2);
  Arg(0);
  MatchVard(0,2);
  Tpop();
  Arg(1);
  MatchVard(0,1);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,3);
  Tpop();
  Arg(2);
  MatchVard(0,4);
  Tpop();
  Tdupl();
  Rpush(v_18);
  goto h_12;
  v_18 :
  MatchVard(0,5);
  Tpop();
  BuildVard(0,1);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildVard(0,5);
  Tpush();
  BuildFun("Goto",1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildVard(0,5);
  Tpush();
  BuildFun("Label",1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Block",1);
  Epopd(0,5);
  Cpop();
  goto t_18;
  u_18 :
  Cpush(x_18);
  Epushd(0,4);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("SDef",3);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Arg(1);
  MatchFun("Nil",0);
  Tpop();
  Arg(2);
  MatchVard(0,2);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,3);
  Tpop();
  Arg(2);
  MatchVard(0,4);
  Tpop();
  BuildVard(0,1);
  Tpush();
  BuildFun("Label",1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildFun("Return",0);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Block",1);
  Epopd(0,4);
  Cpop();
  goto w_18;
  x_18 :
  Cpush(z_18);
  Epushd(0,4);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("Path",2);
  Arg(0);
  MatchVard(0,4);
  Tpop();
  Arg(1);
  MatchVard(0,1);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,2);
  Tpop();
  Arg(2);
  MatchVard(0,3);
  Tpop();
  BuildVard(0,4);
  Tpush();
  BuildFun("TpushIthSon",1);
  Tpush();
  BuildVard(0,1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("TputIthSon",1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Block",1);
  Epopd(0,4);
  Cpop();
  goto y_18;
  z_18 :
  Cpush(b_19);
  Epushd(0,4);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("Cong",2);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Arg(1);
  MatchVard(0,2);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,3);
  Tpop();
  Arg(2);
  MatchVard(0,4);
  Tpop();
  Epushd(1,1);
  BuildVard(0,2);
  Rpush(c_19);
  goto s_12;
  c_19 :
  MatchVard(1,1);
  BuildVard(0,1);
  Tpush();
  BuildVard(1,1);
  Tpush();
  BuildFun("MatchFun",2);
  Tpush();
  BuildFun("TravInit",0);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildFun("CongKids",1);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildFun("AllBuild",0);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Block",1);
  Epopd(1,1);
  Epopd(0,4);
  Cpop();
  goto a_19;
  b_19 :
  Cpush(e_19);
  Epushd(0,3);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("CongWld",1);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,2);
  Tpop();
  Arg(2);
  MatchVard(0,3);
  Tpop();
  BuildFun("TravInit",0);
  Tpush();
  BuildVard(0,1);
  Tpush();
  BuildFun("CongKids",1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildFun("AllBuild",0);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Block",1);
  Epopd(0,3);
  Cpop();
  goto d_19;
  e_19 :
  Cpush(g_19);
  Epushd(0,2);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("CongKids",1);
  Arg(0);
  MatchFun("Nil",0);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,1);
  Tpop();
  Arg(2);
  MatchVard(0,2);
  Tpop();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Block",1);
  Epopd(0,2);
  Cpop();
  goto f_19;
  g_19 :
  Cpush(i_19);
  Epushd(0,4);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("CongKids",1);
  Arg(0);
  MatchFun("Cons",2);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Arg(1);
  MatchVard(0,2);
  Tpop();
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,3);
  Tpop();
  Arg(2);
  MatchVard(0,4);
  Tpop();
  BuildFun("OneNextSon",0);
  Tpush();
  BuildVard(0,1);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildFun("CongKids",1);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Block",1);
  Epopd(0,4);
  Cpop();
  goto h_19;
  i_19 :
  Cpush(k_19);
  Epushd(0,5);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("All",1);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,2);
  Tpop();
  Arg(2);
  MatchVard(0,3);
  Tpop();
  Tdupl();
  Rpush(l_19);
  goto h_12;
  l_19 :
  MatchVard(0,4);
  Rpush(m_19);
  goto h_12;
  m_19 :
  MatchVard(0,5);
  Tpop();
  BuildFun("AllInit",0);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Label",1);
  Tpush();
  BuildVard(0,5);
  Tpush();
  BuildFun("AllNextSon",1);
  Tpush();
  BuildVard(0,1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Goto",1);
  Tpush();
  BuildVard(0,5);
  Tpush();
  BuildFun("Label",1);
  Tpush();
  BuildFun("AllBuild",0);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Block",1);
  Epopd(0,5);
  Cpop();
  goto j_19;
  k_19 :
  Cpush(o_19);
  Epushd(0,5);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("One",1);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,2);
  Tpop();
  Arg(2);
  MatchVard(0,3);
  Tpop();
  Tdupl();
  Rpush(p_19);
  goto h_12;
  p_19 :
  MatchVard(0,4);
  Rpush(q_19);
  goto h_12;
  q_19 :
  MatchVard(0,5);
  Tpop();
  BuildFun("IsAppl",0);
  Tpush();
  BuildFun("OneInit",0);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Label",1);
  Tpush();
  BuildFun("OneNextSon",0);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Cpush",1);
  Tpush();
  BuildVard(0,1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildFun("Cpop",0);
  Tpush();
  BuildFun("OneBuild",0);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Block",1);
  Epopd(0,5);
  Cpop();
  goto n_19;
  o_19 :
  Cpush(s_19);
  Epushd(0,5);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("Some",1);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,2);
  Tpop();
  Arg(2);
  MatchVard(0,3);
  Tpop();
  Tdupl();
  Rpush(t_19);
  goto h_12;
  t_19 :
  MatchVard(0,4);
  Rpush(u_19);
  goto h_12;
  u_19 :
  MatchVard(0,5);
  Tpop();
  BuildFun("IsAppl",0);
  Tpush();
  BuildFun("SomeInit",0);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Label",1);
  Tpush();
  BuildVard(0,5);
  Tpush();
  BuildFun("SomeNextSon",1);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Cpush",1);
  Tpush();
  BuildVard(0,1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildFun("Cpop",0);
  Tpush();
  BuildFun("CounterOK",0);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Goto",1);
  Tpush();
  BuildVard(0,5);
  Tpush();
  BuildFun("Label",1);
  Tpush();
  BuildFun("SomeBuild",0);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Block",1);
  Epopd(0,5);
  Cpop();
  goto r_19;
  s_19 :
  Cpush(w_19);
  Epushd(0,5);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("Thread",1);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,2);
  Tpop();
  Arg(2);
  MatchVard(0,3);
  Tpop();
  Tdupl();
  Rpush(x_19);
  goto h_12;
  x_19 :
  MatchVard(0,4);
  Rpush(y_19);
  goto h_12;
  y_19 :
  MatchVard(0,5);
  Tpop();
  BuildFun("ThreadInit",0);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Label",1);
  Tpush();
  BuildVard(0,5);
  Tpush();
  BuildFun("ThreadNextSon",1);
  Tpush();
  BuildVard(0,1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildFun("ThreadSetEnv",0);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Goto",1);
  Tpush();
  BuildVard(0,5);
  Tpush();
  BuildFun("Label",1);
  Tpush();
  BuildFun("ThreadBuild",0);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Block",1);
  Epopd(0,5);
  Cpop();
  goto v_19;
  w_19 :
  Cpush(a_20);
  Epushd(0,5);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("Scope",2);
  Arg(0);
  MatchVard(0,4);
  Tpop();
  Arg(1);
  MatchVard(0,1);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,2);
  Tpop();
  Arg(2);
  MatchVard(0,3);
  Tpop();
  Tdupl();
  BuildVard(0,4);
  Rpush(b_20);
  goto s_12;
  b_20 :
  MatchVard(0,5);
  Tpop();
  Epushd(1,1);
  BuildVard(0,3);
  Tpush();
  BuildInt(1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(c_20);
  goto o_12;
  c_20 :
  MatchVard(1,1);
  BuildVard(0,3);
  Tpush();
  BuildVard(0,5);
  Tpush();
  BuildFun("Epushd",2);
  Tpush();
  BuildVard(0,1);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildVard(1,1);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildVard(0,5);
  Tpush();
  BuildFun("Epopd",2);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Block",1);
  Epopd(1,1);
  Epopd(0,5);
  Cpop();
  goto z_19;
  a_20 :
  Cpush(e_20);
  Epushd(0,3);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("Where",1);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,2);
  Tpop();
  Arg(2);
  MatchVard(0,3);
  Tpop();
  BuildFun("Tdupl",0);
  Tpush();
  BuildVard(0,1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildFun("Tpop",0);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Block",1);
  Epopd(0,3);
  Cpop();
  goto d_20;
  e_20 :
  Cpush(g_20);
  Epushd(0,3);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("Prim",1);
  Arg(0);
  MatchVard(0,3);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,1);
  Tpop();
  Arg(2);
  MatchVard(0,2);
  Tpop();
  BuildVard(0,3);
  Tpush();
  BuildFun("Iprim",1);
  Epopd(0,3);
  Cpop();
  goto f_20;
  g_20 :
  Cpush(i_20);
  Epushd(0,4);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("Prim2",2);
  Arg(0);
  MatchVard(0,3);
  Tpop();
  Arg(1);
  MatchVard(0,4);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,1);
  Tpop();
  Arg(2);
  MatchVard(0,2);
  Tpop();
  BuildVard(0,3);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Iprim2",2);
  Epopd(0,4);
  Cpop();
  goto h_20;
  i_20 :
  Cpush(k_20);
  Epushd(0,3);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("CountRule",1);
  Arg(0);
  MatchVard(0,3);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,1);
  Tpop();
  Arg(2);
  MatchVard(0,2);
  Tpop();
  BuildVard(0,3);
  Tpush();
  BuildFun("ICountRule",1);
  Epopd(0,3);
  Cpop();
  goto j_20;
  k_20 :
  Cpush(m_20);
  Epushd(0,3);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("Build",1);
  Arg(0);
  MatchFun("Str",1);
  Arg(0);
  MatchVard(0,3);
  Tpop();
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,1);
  Tpop();
  Arg(2);
  MatchVard(0,2);
  Tpop();
  BuildVard(0,3);
  Tpush();
  BuildFun("BuildStr",1);
  Epopd(0,3);
  Cpop();
  goto l_20;
  m_20 :
  Cpush(o_20);
  Epushd(0,3);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("Build",1);
  Arg(0);
  MatchFun("Int",1);
  Arg(0);
  MatchVard(0,3);
  Tpop();
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,1);
  Tpop();
  Arg(2);
  MatchVard(0,2);
  Tpop();
  BuildVard(0,3);
  Tpush();
  BuildFun("BuildInt",1);
  Epopd(0,3);
  Cpop();
  goto n_20;
  o_20 :
  Cpush(q_20);
  Epushd(0,3);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("Build",1);
  Arg(0);
  MatchFun("Real",1);
  Arg(0);
  MatchVard(0,3);
  Tpop();
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,1);
  Tpop();
  Arg(2);
  MatchVard(0,2);
  Tpop();
  BuildVard(0,3);
  Tpush();
  BuildFun("BuildReal",1);
  Epopd(0,3);
  Cpop();
  goto p_20;
  q_20 :
  Cpush(s_20);
  Epushd(0,6);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("Build",1);
  Arg(0);
  MatchFun("Var",1);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,2);
  Tpop();
  Arg(2);
  MatchVard(0,3);
  Tpop();
  Tdupl();
  BuildVard(0,1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epushd(1,4);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(1,1);
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(1,4);
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  Tdupl();
  BuildVard(1,4);
  Epushd(2,0);
  Rpush(t_20);
  s_9 :
  Cpush(v_20);
  MatchFun("Cons",2);
  TravInit();
  OneNextSon();
  Epushd(3,2);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(3,1);
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(3,2);
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  Epushd(4,1);
  BuildVard(1,1);
  Tpush();
  BuildVard(3,2);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(w_20);
  goto p_12;
  w_20 :
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,2);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(1,2);
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(1,3);
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  OneNextSon();
  AllBuild();
  Cpop();
  goto u_20;
  v_20 :
  MatchFun("Cons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  Rpush(x_20);
  goto s_9;
  x_20 :
  AllBuild();
  u_20 :
  Return();
  t_20 :
  Epopd(2,0);
  Tpop();
  BuildVard(1,2);
  Tpush();
  BuildVard(1,3);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(1,4);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(0,4);
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(0,5);
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  Cpush(z_20);
  BuildVard(0,4);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(a_21);
  goto r_12;
  a_21 :
  BuildVard(0,5);
  Tpush();
  BuildFun("BuildVar",1);
  Cpop();
  goto y_20;
  z_20 :
  BuildVard(0,4);
  Tpush();
  BuildVard(0,5);
  Tpush();
  BuildFun("BuildVard",2);
  MatchVard(0,6);
  y_20 :
  Tpop();
  BuildVard(0,6);
  Epopd(0,6);
  Cpop();
  goto r_20;
  s_20 :
  Cpush(c_21);
  Epushd(0,3);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("Build",1);
  Arg(0);
  MatchFun("BuildDefault",1);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,2);
  Tpop();
  Arg(2);
  MatchVard(0,3);
  Tpop();
  BuildVard(0,1);
  Tpush();
  BuildFun("Build",1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildFun("Instr",3);
  Epopd(0,3);
  Cpop();
  goto b_21;
  c_21 :
  Cpush(e_21);
  Epushd(0,4);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("Build",1);
  Arg(0);
  MatchFun("Op",2);
  Arg(0);
  MatchVard(0,3);
  Tpop();
  Arg(1);
  MatchVard(0,4);
  Tpop();
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,1);
  Tpop();
  Arg(2);
  MatchVard(0,2);
  Tpop();
  Epushd(1,1);
  BuildVard(0,4);
  Rpush(f_21);
  goto s_12;
  f_21 :
  MatchVard(1,1);
  BuildVard(0,4);
  Tpush();
  BuildVard(0,1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildFun("BuildKids",3);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildVard(1,1);
  Tpush();
  BuildFun("BuildFun",2);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Block",1);
  Epopd(1,1);
  Epopd(0,4);
  Cpop();
  goto d_21;
  e_21 :
  Cpush(h_21);
  Epushd(0,2);
  MatchFun("BuildKids",3);
  Arg(0);
  MatchFun("Nil",0);
  Tpop();
  Arg(1);
  MatchVard(0,1);
  Tpop();
  Arg(2);
  MatchVard(0,2);
  Tpop();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Block",1);
  Epopd(0,2);
  Cpop();
  goto g_21;
  h_21 :
  Cpush(j_21);
  Epushd(0,4);
  MatchFun("BuildKids",3);
  Arg(0);
  MatchFun("Cons",2);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Arg(1);
  MatchVard(0,2);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,3);
  Tpop();
  Arg(2);
  MatchVard(0,4);
  Tpop();
  BuildVard(0,1);
  Tpush();
  BuildFun("Build",1);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildFun("Tpush",0);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("BuildKids",3);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Block",1);
  Epopd(0,4);
  Cpop();
  goto i_21;
  j_21 :
  Cpush(l_21);
  Epushd(0,4);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("Build",1);
  Arg(0);
  MatchFun("App",2);
  Arg(0);
  MatchVard(0,2);
  Tpop();
  Arg(1);
  MatchVard(0,1);
  Tpop();
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,3);
  Tpop();
  Arg(2);
  MatchVard(0,4);
  Tpop();
  BuildVard(0,1);
  Tpush();
  BuildFun("Build",1);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Block",1);
  Epopd(0,4);
  Cpop();
  goto k_21;
  l_21 :
  Cpush(n_21);
  Epushd(0,2);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("GetAnn",0);
  Tpop();
  Arg(1);
  MatchVard(0,1);
  Tpop();
  Arg(2);
  MatchVard(0,2);
  Tpop();
  BuildFun("GetAnn",0);
  Epopd(0,2);
  Cpop();
  goto m_21;
  n_21 :
  Cpush(p_21);
  Epushd(0,4);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("AnnBuild",2);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Arg(1);
  MatchVard(0,2);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,3);
  Tpop();
  Arg(2);
  MatchVard(0,4);
  Tpop();
  BuildFun("Tpush",0);
  Tpush();
  BuildVard(0,1);
  Tpush();
  BuildFun("Build",1);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildFun("Tpush",0);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildFun("Build",1);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildFun("SetAnn",0);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Block",1);
  Epopd(0,4);
  Cpop();
  goto o_21;
  p_21 :
  Epushd(0,3);
  MatchFun("Instr",3);
  Arg(0);
  MatchFun("AnnRemove",1);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,2);
  Tpop();
  Arg(2);
  MatchVard(0,3);
  Tpop();
  BuildFun("Tpush",0);
  Tpush();
  BuildVard(0,1);
  Tpush();
  BuildFun("Build",1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildFun("Instr",3);
  Tpush();
  BuildFun("RemoveAnn",0);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Block",1);
  Epopd(0,3);
  o_21 :
  m_21 :
  k_21 :
  i_21 :
  g_21 :
  d_21 :
  b_21 :
  r_20 :
  p_20 :
  n_20 :
  l_20 :
  j_20 :
  h_20 :
  f_20 :
  d_20 :
  z_19 :
  v_19 :
  r_19 :
  n_19 :
  j_19 :
  h_19 :
  f_19 :
  d_19 :
  a_19 :
  y_18 :
  w_18 :
  t_18 :
  q_18 :
  n_18 :
  j_18 :
  h_18 :
  y_17 :
  w_17 :
  u_17 :
  s_17 :
  q_17 :
  g_17 :
  e_17 :
  c_17 :
  a_17 :
  y_16 :
  u_16 :
  q_16 :
  o_16 :
  l_16 :
  j_16 :
  h_16 :
  f_16 :
  Return();
  n_12 :
  Cpush(r_21);
  Epushd(0,3);
  MatchFun("TCons",2);
  Arg(0);
  MatchFun("Fun",2);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Arg(1);
  MatchVard(0,2);
  Tpop();
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(0,3);
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  BuildVard(0,1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildFun("MatchFunFC",3);
  Epopd(0,3);
  Cpop();
  goto q_21;
  r_21 :
  Cpush(t_21);
  Epushd(0,2);
  MatchFun("TCons",2);
  Arg(0);
  MatchFun("Int",1);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(0,2);
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  BuildVard(0,1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildFun("MatchIntFC",2);
  Epopd(0,2);
  Cpop();
  goto s_21;
  t_21 :
  Cpush(v_21);
  Epushd(0,2);
  MatchFun("TCons",2);
  Arg(0);
  MatchFun("Real",1);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(0,2);
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  BuildVard(0,1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildFun("MatchRealFC",2);
  Epopd(0,2);
  Cpop();
  goto u_21;
  v_21 :
  Epushd(0,2);
  MatchFun("TCons",2);
  Arg(0);
  MatchFun("Str",1);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(0,2);
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  BuildVard(0,1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildFun("MatchStringFC",2);
  Epopd(0,2);
  u_21 :
  s_21 :
  q_21 :
  Return();
  o_12 :
  Epushd(0,0);
  _ST_add();
  Epopd(0,0);
  Return();
  p_12 :
  Epushd(0,0);
  Epushd(1,2);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(1,1);
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(1,2);
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  BuildInt(1);
  Tpush();
  BuildVard(1,1);
  Tpush();
  BuildVard(1,2);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(1,2);
  Rpush(w_21);
  i_56 :
  Cpush(y_21);
  Epushd(1,3);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(1,3);
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(1,1);
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchFun("Cons",2);
  Arg(0);
  MatchVard(1,1);
  Tpop();
  Arg(1);
  MatchVard(1,2);
  Tpop();
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  Tpop();
  BuildVard(1,3);
  Epopd(1,3);
  Cpop();
  goto x_21;
  y_21 :
  Epushd(1,4);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(1,2);
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(1,3);
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchFun("Cons",2);
  Arg(0);
  MatchVard(1,1);
  Tpop();
  Arg(1);
  MatchVard(1,4);
  Tpop();
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  Tpop();
  Epushd(2,1);
  BuildVard(1,2);
  Tpush();
  BuildInt(1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(z_21);
  goto q_12;
  z_21 :
  MatchVard(2,1);
  BuildVard(2,1);
  Tpush();
  BuildVard(1,3);
  Tpush();
  BuildVard(1,4);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(2,1);
  Epopd(1,4);
  Rpush(a_22);
  goto i_56;
  a_22 :
  x_21 :
  Return();
  w_21 :
  Epopd(0,0);
  Return();
  q_12 :
  Epushd(0,0);
  _ST_plus();
  Epopd(0,0);
  Return();
  r_12 :
  Epushd(0,1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Arg(1);
  MatchFun("TCons",2);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Arg(1);
  MatchFun("TNil",0);
  Tpop();
  Tpop();
  Epopd(0,1);
  Return();
  s_12 :
  Epushd(0,0);
  Rpush(b_22);
  r_56 :
  Cpush(d_22);
  Rpush(e_22);
  goto p_11;
  e_22 :
  BuildInt(0);
  Cpop();
  goto c_22;
  d_22 :
  Epushd(1,2);
  MatchFun("Cons",2);
  Arg(0);
  MatchVard(1,1);
  Tpop();
  Arg(1);
  MatchVard(1,2);
  Tpop();
  BuildVard(1,2);
  Epopd(1,2);
  Rpush(f_22);
  goto r_56;
  f_22 :
  Epushd(1,1);
  MatchVard(1,1);
  BuildVard(1,1);
  Tpush();
  BuildInt(1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(g_22);
  goto q_12;
  g_22 :
  Epopd(1,1);
  c_22 :
  Return();
  b_22 :
  Epopd(0,0);
  Return();
  t_12 :
  Epushd(0,0);
  Rpush(h_22);
  u_47 :
  Epushd(1,0);
  Cpush(j_22);
  Cpush(l_22);
  Rpush(m_22);
  goto p_11;
  m_22 :
  Cpop();
  goto k_22;
  l_22 :
  Cpush(o_22);
  MatchFun("Block",1);
  TravInit();
  OneNextSon();
  Rpush(p_22);
  goto u_47;
  p_22 :
  AllBuild();
  Cpop();
  goto n_22;
  o_22 :
  MatchFun("Cons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  Rpush(q_22);
  goto u_47;
  q_22 :
  AllBuild();
  Rpush(r_22);
  e_11 :
  Epushd(2,0);
  Cpush(t_22);
  Cpush(v_22);
  Epushd(3,1);
  MatchFun("Cons",2);
  Arg(0);
  MatchFun("Block",1);
  Arg(0);
  MatchFun("Nil",0);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(3,1);
  Tpop();
  BuildVard(3,1);
  Epopd(3,1);
  Cpop();
  goto u_22;
  v_22 :
  Epushd(3,3);
  MatchFun("Cons",2);
  Arg(0);
  MatchFun("Block",1);
  Arg(0);
  MatchFun("Cons",2);
  Arg(0);
  MatchVard(3,1);
  Tpop();
  Arg(1);
  MatchVard(3,2);
  Tpop();
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(3,3);
  Tpop();
  BuildVard(3,1);
  Tpush();
  BuildVard(3,2);
  Tpush();
  BuildFun("Block",1);
  Tpush();
  BuildVard(3,3);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(3,3);
  MatchFun("Cons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  Rpush(w_22);
  goto e_11;
  w_22 :
  AllBuild();
  Rpush(x_22);
  goto e_11;
  x_22 :
  u_22 :
  Cpop();
  goto s_22;
  t_22 :
  s_22 :
  Epopd(2,0);
  Return();
  r_22 :
  n_22 :
  k_22 :
  Cpop();
  goto i_22;
  j_22 :
  i_22 :
  Epopd(1,0);
  Return();
  h_22 :
  Epopd(0,0);
  Return();
  u_12 :
  Epushd(0,0);
  Cpush(z_22);
  MatchFun("Block",1);
  TravInit();
  OneNextSon();
  Epushd(1,0);
  Rpush(a_23);
  m_11 :
  Epushd(2,0);
  Cpush(c_23);
  b_23 :
  Rpush(d_23);
  goto v_12;
  d_23 :
  Tduplinv();
  goto b_23;
  c_23 :
  Epopd(2,0);
  Cpush(f_23);
  Rpush(g_23);
  goto p_11;
  g_23 :
  Cpop();
  goto e_23;
  f_23 :
  MatchFun("Cons",2);
  TravInit();
  OneNextSon();
  OneNextSon();
  Rpush(h_23);
  goto m_11;
  h_23 :
  AllBuild();
  e_23 :
  Epushd(2,0);
  Cpush(j_23);
  i_23 :
  Rpush(k_23);
  goto v_12;
  k_23 :
  Tduplinv();
  goto i_23;
  j_23 :
  Epopd(2,0);
  Return();
  a_23 :
  Epopd(1,0);
  AllBuild();
  Cpop();
  goto y_22;
  z_22 :
  y_22 :
  Epopd(0,0);
  Return();
  v_12 :
  Cpush(m_23);
  Epushd(0,2);
  MatchFun("Cons",2);
  Arg(0);
  MatchFun("MatchVar",1);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Tpop();
  Arg(1);
  MatchFun("Cons",2);
  Arg(0);
  MatchFun("BuildVar",1);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,2);
  Tpop();
  Tpop();
  BuildVard(0,1);
  Tpush();
  BuildFun("MatchVar",1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(0,2);
  Cpop();
  goto l_23;
  m_23 :
  Cpush(o_23);
  Epushd(0,3);
  MatchFun("Cons",2);
  Arg(0);
  MatchFun("MatchFun",2);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Arg(1);
  MatchVard(0,2);
  Tpop();
  Tpop();
  Arg(1);
  MatchFun("Cons",2);
  Arg(0);
  MatchFun("TravInit",0);
  Tpop();
  Arg(1);
  MatchFun("Cons",2);
  Arg(0);
  MatchFun("AllBuild",0);
  Tpop();
  Arg(1);
  MatchVard(0,3);
  Tpop();
  Tpop();
  Tpop();
  BuildVard(0,1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildFun("MatchFun",2);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildFun("Cons",2);
  Epopd(0,3);
  Cpop();
  goto n_23;
  o_23 :
  Cpush(q_23);
  Epushd(0,1);
  MatchFun("Cons",2);
  Arg(0);
  MatchFun("Epush",1);
  Arg(0);
  MatchInt(0);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,1);
  Tpop();
  BuildVard(0,1);
  Epopd(0,1);
  Cpop();
  goto p_23;
  q_23 :
  Cpush(s_23);
  Epushd(0,1);
  MatchFun("Cons",2);
  Arg(0);
  MatchFun("Epop",1);
  Arg(0);
  MatchInt(0);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,1);
  Tpop();
  BuildVard(0,1);
  Epopd(0,1);
  Cpop();
  goto r_23;
  s_23 :
  Cpush(u_23);
  Epushd(0,3);
  MatchFun("Cons",2);
  Arg(0);
  MatchFun("Epush",1);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Tpop();
  Arg(1);
  MatchFun("Cons",2);
  Arg(0);
  MatchFun("Epush",1);
  Arg(0);
  MatchVard(0,2);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,3);
  Tpop();
  Tpop();
  Epushd(1,1);
  BuildVard(0,1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(v_23);
  goto q_12;
  v_23 :
  MatchVard(1,1);
  BuildVard(1,1);
  Tpush();
  BuildFun("Epush",1);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildFun("Cons",2);
  Epopd(1,1);
  Epopd(0,3);
  Cpop();
  goto t_23;
  u_23 :
  Cpush(x_23);
  Epushd(0,3);
  MatchFun("Cons",2);
  Arg(0);
  MatchFun("Epop",1);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Tpop();
  Arg(1);
  MatchFun("Cons",2);
  Arg(0);
  MatchFun("Epop",1);
  Arg(0);
  MatchVard(0,2);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,3);
  Tpop();
  Tpop();
  Epushd(1,1);
  BuildVard(0,1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(y_23);
  goto q_12;
  y_23 :
  MatchVard(1,1);
  BuildVard(1,1);
  Tpush();
  BuildFun("Epop",1);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildFun("Cons",2);
  Epopd(1,1);
  Epopd(0,3);
  Cpop();
  goto w_23;
  x_23 :
  Cpush(a_24);
  Epushd(0,2);
  MatchFun("Cons",2);
  Arg(0);
  MatchFun("Arg",1);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Tpop();
  Arg(1);
  MatchFun("Cons",2);
  Arg(0);
  MatchFun("Tpop",0);
  Tpop();
  Arg(1);
  MatchVard(0,2);
  Tpop();
  Tpop();
  BuildVard(0,2);
  Epopd(0,2);
  Cpop();
  goto z_23;
  a_24 :
  Epushd(0,2);
  MatchFun("Cons",2);
  Arg(0);
  MatchFun("Goto",1);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Tpop();
  Arg(1);
  MatchFun("Cons",2);
  Arg(0);
  MatchFun("Label",1);
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Tpop();
  Arg(1);
  MatchVard(0,2);
  Tpop();
  Tpop();
  BuildVard(0,1);
  Tpush();
  BuildFun("Label",1);
  Tpush();
  BuildVard(0,2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(0,2);
  z_23 :
  w_23 :
  t_23 :
  r_23 :
  p_23 :
  n_23 :
  l_23 :
  Return();
  b_24 :
DOIT_END
