#!/bin/sh

# creating default dependency files 

for file in `cat dependencies` 
do
    rm -f $file
    touch $file
done

rm -f config.cache
rm -f acconfig.h
aclocal
autoconf
#acconfig
autoheader
automake -a
