#include <stratego.h>
#include <stratego-lib.h>
#include <stratego-ext.h>
DOIT_START
cur_rule_counter = 0;
  Rpush(k_5);
  goto main;
  main :
  Epushd(0,0);
  BuildStr("needed-defs-test");
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("test suite: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(n_0);
  goto o_60;
  n_0 :
  Tpop();
  Epopd(1,0);
  Rpush(o_0);
  goto p_60;
  o_0 :
  Rpush(p_0);
  goto u_60;
  p_0 :
  Rpush(q_0);
  goto q_60;
  q_0 :
  Rpush(r_0);
  goto s_60;
  r_0 :
  Epopd(0,0);
  Return();
  o_60 :
  Epushd(0,0);
  _ST_printnl();
  Epopd(0,0);
  Return();
  p_60 :
  Epushd(0,0);
  BuildInt(0);
  Tpush();
  BuildInt(0);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(0,0);
  Return();
  q_60 :
  Epushd(0,0);
  MatchFun("TCons");
  TravInit();
  OneNextSon();
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("successes: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(s_0);
  goto o_60;
  s_0 :
  Tpop();
  Epopd(1,0);
  OneNextSon();
  MatchFun("TCons");
  TravInit();
  OneNextSon();
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("failures: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(t_0);
  goto o_60;
  t_0 :
  Tpop();
  Epopd(1,0);
  OneNextSon();
  Rpush(u_0);
  goto r_60;
  u_0 :
  AllBuild();
  AllBuild();
  Epopd(0,0);
  Return();
  r_60 :
  MatchFun("TNil");
  Return();
  s_60 :
  Epushd(0,0);
  Cpush(w_0);
  MatchFun("TCons");
  TravInit();
  OneNextSon();
  OneNextSon();
  MatchFun("TCons");
  TravInit();
  OneNextSon();
  MatchInt(0);
  OneNextSon();
  Rpush(x_0);
  goto r_60;
  x_0 :
  AllBuild();
  AllBuild();
  BuildInt(0);
  Rpush(y_0);
  goto t_60;
  y_0 :
  Cpop();
  goto v_0;
  w_0 :
  BuildInt(1);
  Rpush(z_0);
  goto t_60;
  z_0 :
  v_0 :
  Epopd(0,0);
  Return();
  t_60 :
  Epushd(0,0);
  _ST_exit();
  Epopd(0,0);
  Return();
  u_60 :
  Epushd(0,2);
  Tdupl();
  BuildStr("define-congruence-test");
  Rpush(a_1);
  goto y_60;
  a_1 :
  Tpop();
  Cpush(c_1);
  Tdupl();
  Cpush(e_1);
  BuildStr("If");
  Tpush();
  BuildStr("T");
  Tpush();
  BuildInt(3);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(f_1);
  goto a_61;
  f_1 :
  MatchVard(0,1);
  Cpop();
  goto d_1;
  e_1 :
  BuildStr("  failed");
  Rpush(g_1);
  goto y_60;
  g_1 :
  Rpush(h_1);
  goto z_60;
  h_1 :
  d_1 :
  BuildStr("If");
  Tpush();
  BuildStr("T");
  Tpush();
  BuildFun("Mod",2);
  Tpush();
  BuildStr("e_0");
  Tpush();
  BuildStr("h_0");
  Tpush();
  BuildStr("k_0");
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildStr("d_0");
  Tpush();
  BuildStr("c_0");
  Tpush();
  BuildStr("b_0");
  Tpush();
  BuildStr("a_0");
  Tpush();
  BuildStr("f_0");
  Tpush();
  BuildStr("i_0");
  Tpush();
  BuildStr("l_0");
  Tpush();
  BuildStr("g_0");
  Tpush();
  BuildStr("j_0");
  Tpush();
  BuildStr("m_0");
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildStr("Pair");
  Tpush();
  BuildStr("If");
  Tpush();
  BuildStr("f_0");
  Tpush();
  BuildFun("Var",1);
  Tpush();
  BuildStr("i_0");
  Tpush();
  BuildFun("Var",1);
  Tpush();
  BuildStr("l_0");
  Tpush();
  BuildFun("Var",1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Op",2);
  Tpush();
  BuildStr("d_0");
  Tpush();
  BuildFun("Var",1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Op",2);
  Tpush();
  BuildStr("Pair");
  Tpush();
  BuildStr("If");
  Tpush();
  BuildStr("g_0");
  Tpush();
  BuildFun("Var",1);
  Tpush();
  BuildStr("j_0");
  Tpush();
  BuildFun("Var",1);
  Tpush();
  BuildStr("m_0");
  Tpush();
  BuildFun("Var",1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Op",2);
  Tpush();
  BuildStr("a_0");
  Tpush();
  BuildFun("Var",1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Op",2);
  Tpush();
  BuildStr("e_0");
  Tpush();
  BuildFun("SVar",1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Call",2);
  Tpush();
  BuildStr("Pair");
  Tpush();
  BuildStr("f_0");
  Tpush();
  BuildFun("Var",1);
  Tpush();
  BuildStr("d_0");
  Tpush();
  BuildFun("Var",1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Op",2);
  Tpush();
  BuildStr("Pair");
  Tpush();
  BuildStr("g_0");
  Tpush();
  BuildFun("Var",1);
  Tpush();
  BuildStr("c_0");
  Tpush();
  BuildFun("Var",1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Op",2);
  Tpush();
  BuildFun("BAM",3);
  Tpush();
  BuildStr("h_0");
  Tpush();
  BuildFun("SVar",1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Call",2);
  Tpush();
  BuildStr("Pair");
  Tpush();
  BuildStr("i_0");
  Tpush();
  BuildFun("Var",1);
  Tpush();
  BuildStr("c_0");
  Tpush();
  BuildFun("Var",1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Op",2);
  Tpush();
  BuildStr("Pair");
  Tpush();
  BuildStr("j_0");
  Tpush();
  BuildFun("Var",1);
  Tpush();
  BuildStr("b_0");
  Tpush();
  BuildFun("Var",1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Op",2);
  Tpush();
  BuildFun("BAM",3);
  Tpush();
  BuildStr("k_0");
  Tpush();
  BuildFun("SVar",1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Call",2);
  Tpush();
  BuildStr("Pair");
  Tpush();
  BuildStr("l_0");
  Tpush();
  BuildFun("Var",1);
  Tpush();
  BuildStr("b_0");
  Tpush();
  BuildFun("Var",1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Op",2);
  Tpush();
  BuildStr("Pair");
  Tpush();
  BuildStr("m_0");
  Tpush();
  BuildFun("Var",1);
  Tpush();
  BuildStr("a_0");
  Tpush();
  BuildFun("Var",1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Op",2);
  Tpush();
  BuildFun("BAM",3);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Seqs",1);
  Tpush();
  BuildFun("Rule",3);
  Tpush();
  BuildFun("SRule",1);
  Tpush();
  BuildFun("Scope",2);
  Tpush();
  BuildFun("SDef",3);
  MatchVard(0,2);
  Cpush(j_1);
  BuildVard(0,2);
  MatchVard(0,1);
  Cpop();
  goto i_1;
  j_1 :
  BuildVard(0,1);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  result not equal: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(k_1);
  goto o_60;
  k_1 :
  Tpop();
  Epopd(1,0);
  BuildVard(0,2);
  Epushd(1,0);
  Tdupl();
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  BuildFun("stderr",0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,1);
  MatchVard(5,1);
  Epushd(6,1);
  BuildFun("TNil",0);
  BuildStr("  expected: ");
  MatchVard(6,1);
  BuildVard(6,1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(6,1);
  Epopd(5,1);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  Rpush(l_1);
  goto o_60;
  l_1 :
  Tpop();
  Epopd(1,0);
  Rpush(m_1);
  goto z_60;
  m_1 :
  i_1 :
  Tpop();
  Rpush(n_1);
  goto v_60;
  n_1 :
  Cpop();
  goto b_1;
  c_1 :
  Rpush(o_1);
  goto x_60;
  o_1 :
  b_1 :
  Epopd(0,2);
  Return();
  v_60 :
  Epushd(0,0);
  MatchFun("TCons");
  TravInit();
  OneNextSon();
  Epushd(1,1);
  MatchVard(1,1);
  BuildVard(1,1);
  Tpush();
  BuildInt(1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(p_1);
  goto w_60;
  p_1 :
  Epopd(1,1);
  OneNextSon();
  MatchFun("TCons");
  TravInit();
  OneNextSon();
  OneNextSon();
  Rpush(q_1);
  goto r_60;
  q_1 :
  AllBuild();
  AllBuild();
  Epopd(0,0);
  Return();
  w_60 :
  Epushd(0,0);
  _ST_add();
  Epopd(0,0);
  Return();
  x_60 :
  Epushd(0,0);
  MatchFun("TCons");
  TravInit();
  OneNextSon();
  OneNextSon();
  MatchFun("TCons");
  TravInit();
  OneNextSon();
  Epushd(1,1);
  MatchVard(1,1);
  BuildVard(1,1);
  Tpush();
  BuildInt(1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(r_1);
  goto w_60;
  r_1 :
  Epopd(1,1);
  OneNextSon();
  Rpush(s_1);
  goto r_60;
  s_1 :
  AllBuild();
  AllBuild();
  Epopd(0,0);
  Return();
  y_60 :
  Epushd(0,0);
  Tdupl();
  Epushd(1,1);
  MatchVard(1,1);
  Epushd(2,1);
  BuildVard(1,1);
  BuildFun("stderr",0);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(1,1);
  Epushd(4,1);
  MatchVard(4,1);
  BuildVard(4,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Epopd(4,1);
  MatchVard(3,1);
  BuildVard(2,1);
  Tpush();
  BuildVard(3,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(3,1);
  Epopd(2,1);
  Epopd(1,1);
  Rpush(t_1);
  goto o_60;
  t_1 :
  Tpop();
  Epopd(0,0);
  Return();
  z_60 :
  Epushd(0,1);
  MatchVard(0,1);
  MatchFun("TCons");
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Arg(1);
  MatchFun("TCons");
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Arg(1);
  MatchFun("TNil");
  Tpop();
  Tpop();
  Epopd(0,1);
  Return();
  a_61 :
  Cpush(v_1);
  Epushd(0,9);
  MatchFun("TCons");
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Arg(1);
  MatchFun("TCons");
  Arg(0);
  MatchString("D");
  Tpop();
  Arg(1);
  MatchFun("TCons");
  Arg(0);
  MatchVard(0,2);
  Tpop();
  Arg(1);
  MatchFun("TNil");
  Tpop();
  Tpop();
  Tpop();
  Tdupl();
  Rpush(w_1);
  goto f_61;
  w_1 :
  MatchVard(0,3);
  BuildVard(0,2);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildFun("Var",1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epushd(1,2);
  MatchFun("TCons");
  Arg(0);
  MatchVard(1,1);
  Tpop();
  Arg(1);
  MatchFun("TCons");
  Arg(0);
  MatchVard(1,2);
  Tpop();
  Arg(1);
  MatchFun("TNil");
  Tpop();
  Tpop();
  BuildVard(1,1);
  Tpush();
  BuildVard(1,2);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(x_1);
  k_55 :
  Epushd(2,3);
  MatchFun("TCons");
  Arg(0);
  MatchVard(2,1);
  Tpop();
  Arg(1);
  MatchFun("TCons");
  Arg(0);
  MatchVard(2,2);
  Tpop();
  Arg(1);
  MatchFun("TCons");
  Arg(0);
  MatchVard(2,3);
  Tpop();
  Arg(1);
  MatchFun("TNil");
  Tpop();
  Tpop();
  Tpop();
  Tdupl();
  BuildVard(2,1);
  Tpush();
  BuildInt(1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(y_1);
  goto e_61;
  y_1 :
  Tpop();
  Epushd(3,1);
  BuildVard(2,1);
  Tpush();
  BuildInt(1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(z_1);
  goto d_61;
  z_1 :
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,2);
  Epushd(5,4);
  MatchVard(5,1);
  Tdupl();
  Rpush(a_2);
  goto f_61;
  a_2 :
  MatchVard(5,2);
  Rpush(b_2);
  goto f_61;
  b_2 :
  MatchVard(5,3);
  Rpush(c_2);
  goto f_61;
  c_2 :
  MatchVard(5,4);
  Tpop();
  BuildVard(5,2);
  Tpush();
  BuildFun("SVar",1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Call",2);
  Tpush();
  BuildStr("Pair");
  Tpush();
  BuildVard(5,3);
  Tpush();
  BuildFun("Var",1);
  Tpush();
  BuildVard(5,1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Op",2);
  Tpush();
  BuildVard(5,4);
  Tpush();
  BuildFun("Var",1);
  Tpush();
  BuildFun("BAM",3);
  Tpush();
  BuildVard(5,2);
  Tpush();
  BuildVard(5,3);
  Tpush();
  BuildVard(5,3);
  Tpush();
  BuildFun("Var",1);
  Tpush();
  BuildVard(5,4);
  Tpush();
  BuildVard(5,4);
  Tpush();
  BuildFun("Var",1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(5,4);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(2,2);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildVard(2,3);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,3);
  Cpush(e_2);
  Epushd(2,2);
  MatchFun("TCons");
  Arg(0);
  MatchInt(0);
  Tpop();
  Arg(1);
  MatchFun("TCons");
  Arg(0);
  MatchVard(2,1);
  Tpop();
  Arg(1);
  MatchFun("TCons");
  Arg(0);
  MatchVard(2,2);
  Tpop();
  Arg(1);
  MatchFun("TNil");
  Tpop();
  Tpop();
  Tpop();
  BuildVard(2,2);
  Epopd(2,2);
  Cpop();
  goto d_2;
  e_2 :
  Rpush(f_2);
  goto k_55;
  f_2 :
  d_2 :
  Return();
  x_1 :
  Epopd(1,2);
  Epushd(1,0);
  Rpush(g_2);
  y_55 :
  Cpush(i_2);
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  Epushd(4,0);
  Rpush(j_2);
  s_56 :
  Cpush(l_2);
  Rpush(m_2);
  goto b_61;
  m_2 :
  Cpop();
  goto k_2;
  l_2 :
  MatchFun("Cons");
  TravInit();
  OneNextSon();
  Epushd(5,2);
  MatchFun("TCons");
  Arg(0);
  MatchVard(5,2);
  Tpop();
  Arg(1);
  MatchVard(5,1);
  Tpop();
  BuildVard(5,2);
  Epopd(5,2);
  OneNextSon();
  Rpush(n_2);
  goto s_56;
  n_2 :
  AllBuild();
  k_2 :
  Return();
  j_2 :
  Epopd(4,0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,0);
  Rpush(o_2);
  v_56 :
  Cpush(q_2);
  Rpush(r_2);
  goto b_61;
  r_2 :
  Cpop();
  goto p_2;
  q_2 :
  MatchFun("Cons");
  TravInit();
  OneNextSon();
  Epushd(6,2);
  MatchFun("TCons");
  Arg(0);
  MatchVard(6,1);
  Tpop();
  Arg(1);
  MatchVard(6,2);
  Tpop();
  BuildVard(6,2);
  Epopd(6,2);
  OneNextSon();
  Rpush(s_2);
  goto v_56;
  s_2 :
  AllBuild();
  p_2 :
  Return();
  o_2 :
  Epopd(5,0);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  MatchFun("TCons");
  TravInit();
  OneNextSon();
  OneNextSon();
  MatchFun("TCons");
  TravInit();
  OneNextSon();
  Rpush(t_2);
  goto y_55;
  t_2 :
  OneNextSon();
  Rpush(u_2);
  goto r_60;
  u_2 :
  AllBuild();
  AllBuild();
  Epushd(2,2);
  MatchFun("TCons");
  Arg(0);
  MatchVard(2,1);
  Tpop();
  Arg(1);
  MatchFun("TCons");
  Arg(0);
  MatchVard(2,2);
  Tpop();
  Arg(1);
  MatchFun("TNil");
  Tpop();
  Tpop();
  BuildVard(2,1);
  Tpush();
  BuildVard(2,2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(2,2);
  Cpop();
  goto h_2;
  i_2 :
  Epushd(2,0);
  Rpush(v_2);
  w_56 :
  Cpush(x_2);
  Rpush(y_2);
  goto b_61;
  y_2 :
  Cpop();
  goto w_2;
  x_2 :
  MatchFun("Cons");
  TravInit();
  OneNextSon();
  Rpush(z_2);
  goto r_60;
  z_2 :
  OneNextSon();
  Rpush(a_3);
  goto w_56;
  a_3 :
  AllBuild();
  w_2 :
  Return();
  v_2 :
  Epopd(2,0);
  BuildFun("TNil",0);
  h_2 :
  Return();
  g_2 :
  Epopd(1,0);
  MatchFun("TCons");
  Arg(0);
  MatchVard(0,4);
  Tpop();
  Arg(1);
  MatchFun("TCons");
  Arg(0);
  MatchVard(0,5);
  Tpop();
  Arg(1);
  MatchFun("TCons");
  Arg(0);
  MatchVard(0,6);
  Tpop();
  Arg(1);
  MatchFun("TCons");
  Arg(0);
  MatchVard(0,7);
  Tpop();
  Arg(1);
  MatchFun("TCons");
  Arg(0);
  MatchVard(0,8);
  Tpop();
  Arg(1);
  MatchFun("TCons");
  Arg(0);
  MatchVard(0,9);
  Tpop();
  Arg(1);
  MatchFun("TNil");
  Tpop();
  Tpop();
  Tpop();
  Tpop();
  Tpop();
  Tpop();
  Tpop();
  Epushd(1,1);
  BuildVard(0,6);
  Tpush();
  BuildVard(0,8);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epushd(2,2);
  MatchFun("TCons");
  Arg(0);
  MatchVard(2,2);
  Tpop();
  Arg(1);
  MatchFun("TCons");
  Arg(0);
  MatchVard(2,1);
  Tpop();
  Arg(1);
  MatchFun("TNil");
  Tpop();
  Tpop();
  BuildVard(2,2);
  Epushd(3,0);
  Rpush(b_3);
  z_56 :
  Cpush(d_3);
  MatchFun("Cons");
  TravInit();
  OneNextSon();
  OneNextSon();
  Rpush(e_3);
  goto z_56;
  e_3 :
  AllBuild();
  Cpop();
  goto c_3;
  d_3 :
  Rpush(f_3);
  goto b_61;
  f_3 :
  BuildVard(2,1);
  c_3 :
  Return();
  b_3 :
  Epopd(3,0);
  Epopd(2,2);
  MatchVard(1,1);
  BuildVard(0,1);
  Tpush();
  BuildStr("D");
  Tpush();
  BuildFun("Mod",2);
  Tpush();
  BuildVard(0,5);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildVard(1,1);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildStr("Pair");
  Tpush();
  BuildVard(0,1);
  Tpush();
  BuildVard(0,7);
  Tpush();
  BuildFun("Op",2);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildFun("Var",1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Op",2);
  Tpush();
  BuildVard(0,1);
  Tpush();
  BuildVard(0,9);
  Tpush();
  BuildFun("Op",2);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Seqs",1);
  Tpush();
  BuildFun("Rule",3);
  Tpush();
  BuildFun("SRule",1);
  Tpush();
  BuildFun("Scope",2);
  Tpush();
  BuildFun("SDef",3);
  Epopd(1,1);
  Epopd(0,9);
  Cpop();
  goto u_1;
  v_1 :
  Epushd(0,11);
  MatchFun("TCons");
  Arg(0);
  MatchVard(0,1);
  Tpop();
  Arg(1);
  MatchFun("TCons");
  Arg(0);
  MatchString("T");
  Tpop();
  Arg(1);
  MatchFun("TCons");
  Arg(0);
  MatchVard(0,2);
  Tpop();
  Arg(1);
  MatchFun("TNil");
  Tpop();
  Tpop();
  Tpop();
  Tdupl();
  Rpush(g_3);
  goto y_60;
  g_3 :
  Epushd(1,1);
  BuildVard(0,2);
  Tpush();
  BuildInt(1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(h_3);
  goto w_60;
  h_3 :
  MatchVard(1,1);
  BuildVard(1,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(1,1);
  Epushd(1,2);
  MatchFun("TCons");
  Arg(0);
  MatchVard(1,1);
  Tpop();
  Arg(1);
  MatchFun("TCons");
  Arg(0);
  MatchVard(1,2);
  Tpop();
  Arg(1);
  MatchFun("TNil");
  Tpop();
  Tpop();
  BuildVard(1,1);
  Tpush();
  BuildVard(1,2);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(i_3);
  s_57 :
  Epushd(2,3);
  MatchFun("TCons");
  Arg(0);
  MatchVard(2,1);
  Tpop();
  Arg(1);
  MatchFun("TCons");
  Arg(0);
  MatchVard(2,2);
  Tpop();
  Arg(1);
  MatchFun("TCons");
  Arg(0);
  MatchVard(2,3);
  Tpop();
  Arg(1);
  MatchFun("TNil");
  Tpop();
  Tpop();
  Tpop();
  Tdupl();
  BuildVard(2,1);
  Tpush();
  BuildInt(1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(j_3);
  goto e_61;
  j_3 :
  Tpop();
  Epushd(3,1);
  BuildVard(2,1);
  Tpush();
  BuildInt(1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Rpush(k_3);
  goto d_61;
  k_3 :
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,2);
  Rpush(l_3);
  goto f_61;
  l_3 :
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(2,2);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildVard(2,3);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,3);
  Cpush(n_3);
  Epushd(2,2);
  MatchFun("TCons");
  Arg(0);
  MatchInt(0);
  Tpop();
  Arg(1);
  MatchFun("TCons");
  Arg(0);
  MatchVard(2,1);
  Tpop();
  Arg(1);
  MatchFun("TCons");
  Arg(0);
  MatchVard(2,2);
  Tpop();
  Arg(1);
  MatchFun("TNil");
  Tpop();
  Tpop();
  Tpop();
  BuildVard(2,2);
  Epopd(2,2);
  Cpop();
  goto m_3;
  n_3 :
  Rpush(o_3);
  goto s_57;
  o_3 :
  m_3 :
  Return();
  i_3 :
  Epopd(1,2);
  MatchFun("Cons");
  Arg(0);
  MatchVard(0,4);
  Tpop();
  Arg(1);
  MatchVard(0,5);
  Tpop();
  Rpush(p_3);
  goto y_60;
  p_3 :
  BuildVard(0,5);
  Rpush(q_3);
  goto g_61;
  q_3 :
  MatchVard(0,3);
  Rpush(r_3);
  goto y_60;
  r_3 :
  BuildVard(0,4);
  Tpush();
  BuildVard(0,5);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildVard(0,5);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epushd(1,0);
  Rpush(s_3);
  q_58 :
  Cpush(u_3);
  Epushd(2,0);
  MatchFun("TCons");
  Arg(0);
  Tpop();
  Arg(1);
  MatchFun("TCons");
  Arg(0);
  MatchFun("Nil");
  Tpop();
  Arg(1);
  MatchFun("TNil");
  Tpop();
  Tpop();
  BuildFun("Nil",0);
  Epopd(2,0);
  Cpop();
  goto t_3;
  u_3 :
  Epushd(2,4);
  MatchFun("TCons");
  Arg(0);
  MatchFun("Cons");
  Arg(0);
  MatchVard(2,1);
  Tpop();
  Arg(1);
  MatchVard(2,3);
  Tpop();
  Tpop();
  Arg(1);
  MatchFun("TCons");
  Arg(0);
  MatchFun("Cons");
  Arg(0);
  MatchVard(2,2);
  Tpop();
  Arg(1);
  MatchVard(2,4);
  Tpop();
  Tpop();
  Arg(1);
  MatchFun("TNil");
  Tpop();
  Tpop();
  BuildVard(2,1);
  Tpush();
  BuildVard(2,2);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildVard(2,3);
  Tpush();
  BuildVard(2,4);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(2,4);
  MatchFun("TCons");
  TravInit();
  OneNextSon();
  Epushd(2,5);
  MatchFun("TCons");
  Arg(0);
  MatchVard(2,1);
  Tpop();
  Arg(1);
  MatchFun("TCons");
  Arg(0);
  MatchVard(2,2);
  Tpop();
  Arg(1);
  MatchFun("TNil");
  Tpop();
  Tpop();
  Tdupl();
  Rpush(v_3);
  goto f_61;
  v_3 :
  MatchVard(2,3);
  Rpush(w_3);
  goto f_61;
  w_3 :
  MatchVard(2,4);
  Rpush(x_3);
  goto f_61;
  x_3 :
  MatchVard(2,5);
  Tpop();
  BuildVard(2,3);
  Tpush();
  BuildFun("SVar",1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Call",2);
  Tpush();
  BuildStr("Pair");
  Tpush();
  BuildVard(2,4);
  Tpush();
  BuildFun("Var",1);
  Tpush();
  BuildVard(2,1);
  Tpush();
  BuildFun("Var",1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Op",2);
  Tpush();
  BuildStr("Pair");
  Tpush();
  BuildVard(2,5);
  Tpush();
  BuildFun("Var",1);
  Tpush();
  BuildVard(2,2);
  Tpush();
  BuildFun("Var",1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Op",2);
  Tpush();
  BuildFun("BAM",3);
  Tpush();
  BuildVard(2,3);
  Tpush();
  BuildVard(2,4);
  Tpush();
  BuildVard(2,4);
  Tpush();
  BuildFun("Var",1);
  Tpush();
  BuildVard(2,5);
  Tpush();
  BuildVard(2,5);
  Tpush();
  BuildFun("Var",1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(2,5);
  OneNextSon();
  MatchFun("TCons");
  TravInit();
  OneNextSon();
  Rpush(y_3);
  goto q_58;
  y_3 :
  OneNextSon();
  Rpush(z_3);
  goto r_60;
  z_3 :
  AllBuild();
  AllBuild();
  Epushd(2,2);
  MatchFun("TCons");
  Arg(0);
  MatchVard(2,1);
  Tpop();
  Arg(1);
  MatchFun("TCons");
  Arg(0);
  MatchVard(2,2);
  Tpop();
  Arg(1);
  MatchFun("TNil");
  Tpop();
  Tpop();
  BuildVard(2,1);
  Tpush();
  BuildVard(2,2);
  Tpush();
  BuildFun("Cons",2);
  Epopd(2,2);
  t_3 :
  Return();
  s_3 :
  Epopd(1,0);
  Epushd(1,0);
  Rpush(a_4);
  j_59 :
  Cpush(c_4);
  Epushd(2,1);
  MatchVard(2,1);
  Epushd(3,1);
  BuildVard(2,1);
  Epushd(4,0);
  Rpush(d_4);
  d_60 :
  Cpush(f_4);
  Rpush(g_4);
  goto b_61;
  g_4 :
  Cpop();
  goto e_4;
  f_4 :
  MatchFun("Cons");
  TravInit();
  OneNextSon();
  Epushd(5,2);
  MatchFun("TCons");
  Arg(0);
  MatchVard(5,2);
  Tpop();
  Arg(1);
  MatchVard(5,1);
  Tpop();
  BuildVard(5,2);
  Epopd(5,2);
  OneNextSon();
  Rpush(h_4);
  goto d_60;
  h_4 :
  AllBuild();
  e_4 :
  Return();
  d_4 :
  Epopd(4,0);
  MatchVard(3,1);
  Epushd(4,1);
  BuildVard(2,1);
  Epushd(5,0);
  Rpush(i_4);
  g_60 :
  Cpush(k_4);
  Rpush(l_4);
  goto b_61;
  l_4 :
  Cpop();
  goto j_4;
  k_4 :
  MatchFun("Cons");
  TravInit();
  OneNextSon();
  Epushd(6,2);
  MatchFun("TCons");
  Arg(0);
  MatchVard(6,1);
  Tpop();
  Arg(1);
  MatchVard(6,2);
  Tpop();
  BuildVard(6,2);
  Epopd(6,2);
  OneNextSon();
  Rpush(m_4);
  goto g_60;
  m_4 :
  AllBuild();
  j_4 :
  Return();
  i_4 :
  Epopd(5,0);
  MatchVard(4,1);
  BuildVard(3,1);
  Tpush();
  BuildVard(4,1);
  Tpush();
  BuildFun("TNil",0);
  Tpush();
  BuildFun("TCons",2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(4,1);
  Epopd(3,1);
  Epopd(2,1);
  MatchFun("TCons");
  TravInit();
  OneNextSon();
  OneNextSon();
  MatchFun("TCons");
  TravInit();
  OneNextSon();
  Rpush(n_4);
  goto j_59;
  n_4 :
  OneNextSon();
  Rpush(o_4);
  goto r_60;
  o_4 :
  AllBuild();
  AllBuild();
  Epushd(2,2);
  MatchFun("TCons");
  Arg(0);
  MatchVard(2,1);
  Tpop();
  Arg(1);
  MatchFun("TCons");
  Arg(0);
  MatchVard(2,2);
  Tpop();
  Arg(1);
  MatchFun("TNil");
  Tpop();
  Tpop();
  BuildVard(2,1);
  Tpush();
  BuildVard(2,2);
  Tpush();
  BuildFun("TCons",2);
  Epopd(2,2);
  Cpop();
  goto b_4;
  c_4 :
  Epushd(2,0);
  Rpush(p_4);
  h_60 :
  Cpush(r_4);
  Rpush(s_4);
  goto b_61;
  s_4 :
  Cpop();
  goto q_4;
  r_4 :
  MatchFun("Cons");
  TravInit();
  OneNextSon();
  Rpush(t_4);
  goto r_60;
  t_4 :
  OneNextSon();
  Rpush(u_4);
  goto h_60;
  u_4 :
  AllBuild();
  q_4 :
  Return();
  p_4 :
  Epopd(2,0);
  BuildFun("TNil",0);
  b_4 :
  Return();
  a_4 :
  Epopd(1,0);
  MatchFun("TCons");
  Arg(0);
  MatchVard(0,6);
  Tpop();
  Arg(1);
  MatchFun("TCons");
  Arg(0);
  MatchVard(0,7);
  Tpop();
  Arg(1);
  MatchFun("TCons");
  Arg(0);
  MatchVard(0,8);
  Tpop();
  Arg(1);
  MatchFun("TCons");
  Arg(0);
  MatchVard(0,9);
  Tpop();
  Arg(1);
  MatchFun("TCons");
  Arg(0);
  MatchVard(0,10);
  Tpop();
  Arg(1);
  MatchFun("TCons");
  Arg(0);
  MatchVard(0,11);
  Tpop();
  Arg(1);
  MatchFun("TNil");
  Tpop();
  Tpop();
  Tpop();
  Tpop();
  Tpop();
  Tpop();
  Tpop();
  Epushd(1,1);
  BuildVard(0,5);
  Tpush();
  BuildVard(0,8);
  Tpush();
  BuildVard(0,10);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Rpush(v_4);
  goto c_61;
  v_4 :
  MatchVard(1,1);
  BuildVard(0,1);
  Tpush();
  BuildStr("T");
  Tpush();
  BuildFun("Mod",2);
  Tpush();
  BuildVard(0,7);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildVard(1,1);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildStr("Pair");
  Tpush();
  BuildVard(0,1);
  Tpush();
  BuildVard(0,9);
  Tpush();
  BuildFun("Op",2);
  Tpush();
  BuildVard(0,4);
  Tpush();
  BuildFun("Var",1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Op",2);
  Tpush();
  BuildStr("Pair");
  Tpush();
  BuildVard(0,1);
  Tpush();
  BuildVard(0,11);
  Tpush();
  BuildFun("Op",2);
  Tpush();
  BuildVard(0,3);
  Tpush();
  BuildFun("Var",1);
  Tpush();
  BuildFun("Nil",0);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Cons",2);
  Tpush();
  BuildFun("Op",2);
  Tpush();
  BuildVard(0,6);
  Tpush();
  BuildFun("Seqs",1);
  Tpush();
  BuildFun("Rule",3);
  Tpush();
  BuildFun("SRule",1);
  Tpush();
  BuildFun("Scope",2);
  Tpush();
  BuildFun("SDef",3);
  Epopd(1,1);
  Epopd(0,11);
  u_1 :
  Return();
  b_61 :
  MatchFun("Nil");
  Return();
  c_61 :
  Epushd(0,0);
  Rpush(w_4);
  e_39 :
  Cpush(y_4);
  Rpush(z_4);
  goto b_61;
  z_4 :
  Cpop();
  goto x_4;
  y_4 :
  Epushd(1,2);
  MatchFun("Cons");
  Arg(0);
  MatchVard(1,2);
  Tpop();
  Arg(1);
  MatchVard(1,1);
  Tpop();
  BuildVard(1,2);
  Epushd(2,0);
  Rpush(a_5);
  k_60 :
  Cpush(c_5);
  MatchFun("Cons");
  TravInit();
  OneNextSon();
  OneNextSon();
  Rpush(d_5);
  goto k_60;
  d_5 :
  AllBuild();
  Cpop();
  goto b_5;
  c_5 :
  Rpush(e_5);
  goto b_61;
  e_5 :
  BuildVard(1,1);
  Rpush(f_5);
  goto e_39;
  f_5 :
  b_5 :
  Return();
  a_5 :
  Epopd(2,0);
  Epopd(1,2);
  x_4 :
  Return();
  w_4 :
  Epopd(0,0);
  Return();
  d_61 :
  Epushd(0,0);
  _ST_subt();
  Epopd(0,0);
  Return();
  e_61 :
  Epushd(0,0);
  _ST_geq();
  Epopd(0,0);
  Return();
  f_61 :
  Epushd(0,0);
  _ST_new();
  Epopd(0,0);
  Return();
  g_61 :
  Epushd(0,0);
  Rpush(g_5);
  d_34 :
  Cpush(i_5);
  Epushd(1,1);
  MatchFun("Cons");
  Arg(0);
  MatchVard(1,1);
  Tpop();
  Arg(1);
  MatchFun("Nil");
  Tpop();
  BuildVard(1,1);
  Epopd(1,1);
  Cpop();
  goto h_5;
  i_5 :
  Epushd(1,2);
  MatchFun("Cons");
  Arg(0);
  MatchVard(1,1);
  Tpop();
  Arg(1);
  MatchVard(1,2);
  Tpop();
  BuildVard(1,2);
  Epopd(1,2);
  Rpush(j_5);
  goto d_34;
  j_5 :
  h_5 :
  Return();
  g_5 :
  Epopd(0,0);
  Return();
  k_5 :
DOIT_END
